import React,{useEffect,useMemo,useRef,useState} from 'react'
import type {WorkWindowApi,WorkWindowSnapshot,WorkSetValue,WorkWindowAction} from '../../shared/contracts/work-set.contract'
import {WorkReferencePanel} from '../components/gallery/WorkReferencePanel'
import {FocusView} from '../components/gallery/FocusView'
import {createNotebookSession} from '../components/library/canvas/notebook-session'
import '../components/gallery/tokens.css'
import '../components/gallery/gallery.css'
import '../components/library/canvas/library-canvas.css'
import './work-set-window.css'
const valueOf=(s:WorkWindowSnapshot):WorkSetValue=>({name:s.set.name,assetIds:s.set.assetIds,note:s.set.note,colors:s.set.colors,columns:s.set.columns})
export default function WorkSetWindow(){
 const nativeBackdrop=/Mac/.test(navigator.platform)
 const [systemDark,setSystemDark]=useState(()=>matchMedia('(prefers-color-scheme: dark)').matches)
 const [status,setStatus]=useState('')
 const statusTimer=useRef<ReturnType<typeof setTimeout>|null>(null)
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)'),changed=()=>setSystemDark(media.matches);media.addEventListener('change',changed);return()=>{media.removeEventListener('change',changed);if(statusTimer.current)clearTimeout(statusTimer.current)}},[])
 const feedback=(text:string)=>{setStatus(text);if(statusTimer.current)clearTimeout(statusTimer.current);statusTimer.current=setTimeout(()=>setStatus(''),2500)}
 const api=(window as unknown as {workWindowAPI?:WorkWindowApi}).workWindowAPI
 const [snapshot,setSnapshot]=useState<WorkWindowSnapshot|null>(null),[draft,setDraft]=useState<WorkSetValue|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[focus,setFocus]=useState<string|null>(null)
 const savingRef=useRef(false),stateRef=useRef<WorkWindowSnapshot|null>(null),draftRef=useRef<WorkSetValue|null>(null),baseRef=useRef(0),serial=useRef(0),alive=useRef(true)
 useEffect(()=>{alive.current=true;document.documentElement.classList.add('native-work-window');if(!api){setError('请从工作模式打开此窗口。');return}let received=0;const accept=(next:WorkWindowSnapshot|null)=>{if(!alive.current)return;if(!next){setSnapshot(null);setDraft(null);stateRef.current=null;return}const previous=stateRef.current,dirty=draftRef.current&&previous&&JSON.stringify(draftRef.current)!==JSON.stringify(valueOf(previous));if(!previous||previous.token!==next.token||!dirty){const d=next.draft||valueOf(next);draftRef.current=d;baseRef.current=next.draftRevision||next.set.revision;setDraft(d);}else if(next.set.revision!==baseRef.current&&!savingRef.current)setError('工作集已在其他位置更新。当前草稿保留，请核对后再保存或重新读取。');stateRef.current=next;setSnapshot(next)}
 const stop=api.onState(next=>{received++;accept(next)});const version=received;void api.inspect().then(r=>{if(version===received){if(r.success)accept(r.value);else setError(r.error)}}).catch(()=>setError('无法读取工作窗口。'))
 return()=>{alive.current=false;stop();document.documentElement.classList.remove('native-work-window')}
 },[api])
 const act=async(command:Omit<WorkWindowAction,'token'>)=>{const current=stateRef.current;if(!current||!api)return null;const token=current.token;try{const r=await api.act({token,...command} as WorkWindowAction);if(!alive.current||stateRef.current?.token!==token)return null;if(!r.success){setError(r.error);return null}return r.value}catch{if(alive.current)setError('操作失败，请重试。');return null}}
 const update=(next:WorkSetValue)=>{draftRef.current=next;serial.current++;setDraft(next);setError('');setStatus('');if(statusTimer.current)clearTimeout(statusTimer.current);void act({kind:'draft',expectedRevision:baseRef.current,value:next} as Omit<WorkWindowAction,'token'>)}
 const save=async()=>{if(!draftRef.current||!stateRef.current||savingRef.current)return;const submitted=structuredClone(draftRef.current),version=serial.current;savingRef.current=true;setSaving(true);const result=await act({kind:'save',expectedRevision:baseRef.current,value:submitted} as Omit<WorkWindowAction,'token'>);if(result&&alive.current){baseRef.current=result.set.revision;stateRef.current=result;setSnapshot(result);if(serial.current===version){draftRef.current=valueOf(result);setDraft(valueOf(result));setError('');feedback('已保存')}else {void act({kind:'draft',expectedRevision:result.set.revision,value:draftRef.current!} as Omit<WorkWindowAction,'token'>);setError('已保存此次内容，新编辑尚未保存。')}}savingRef.current=false;if(alive.current)setSaving(false)}
 const notebook=useMemo(()=>{const token=snapshot?.token,scope=snapshot?.scope;if(!token||!scope||!api)return null;const session=createNotebookSession(scope,()=>({notebookRead:r=>api.notebookRead({token,assetId:r.assetId}),notebookSave:r=>api.notebookSave({token,request:r})}));const dirty=()=>{void api.act({token,kind:'notes-dirty',dirty:session.hasUnsaved()})};return{...session,hold:(books:Parameters<typeof session.hold>[0])=>{session.hold(books);dirty()},setTransient:(pending:boolean)=>{session.setTransient?.(pending);dirty()},save:async(...args:Parameters<typeof session.save>)=>{try{await session.save(...args)}finally{dirty()}}}},[snapshot?.token,api])
 useEffect(()=>()=>notebook?.dispose(),[notebook])
 useEffect(()=>{const protect=(e:BeforeUnloadEvent)=>{const s=stateRef.current;if(s&&draftRef.current&&JSON.stringify(draftRef.current)!==JSON.stringify(valueOf(s))||notebook?.hasUnsaved()){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect)},[notebook])
 if(!snapshot||!draft)return <main className="native-work-empty">{error||'正在读取工作集…'}</main>
 const available=new Map(snapshot.assets.map(a=>[a.id,a])),src=(id:string)=>`dam-preview://preview/${[snapshot.scope.libraryIdentity,snapshot.scope.generation,id].map(encodeURIComponent).join('/')}`
 const items=draft.assetIds.map(id=>({id,title:available.get(id)?.title||'暂不可用的参考',src:src(id),unavailable:!available.has(id)})),focused=focus?available.get(focus):undefined,focusItems=items.filter(i=>!i.unavailable).map(i=>({...i,src:i.src,kind:'image' as const,pixelLabel:'预览像素 1:1'}))
 const move=(id:string,delta:number)=>{const ids=[...draft.assetIds],at=ids.indexOf(id),to=at+delta;if(to<0||to>=ids.length)return;[ids[at],ids[to]]=[ids[to],ids[at]];update({...draft,assetIds:ids})}
 return <main className={`gallery-design minimal-prototype native-work-surface ${(nativeBackdrop?systemDark:snapshot.theme==='dark')?'dark':''}`} data-native-backdrop={nativeBackdrop} onKeyDown={e=>{if(!e.defaultPrevented&&(e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(!focus)void save()}}} data-work-set-id={snapshot.set.id}>
 <WorkReferencePanel name={draft.name} items={items} note={draft.note} colors={draft.colors} pinned={snapshot.pinned} columns={draft.columns} fitColumns status={status} dirty={JSON.stringify(draft)!==JSON.stringify(valueOf(snapshot))} saving={saving} error={error||snapshot.layoutError} onPreview={setFocus} onInspect={setFocus} onRemove={id=>update({...draft,assetIds:draft.assetIds.filter(x=>x!==id)})} onMove={move} onAdd={()=>{void act({kind:'add-from-library'})}} onNote={note=>update({...draft,note})} onColors={colors=>update({...draft,colors})} onColumns={columns=>update({...draft,columns})} onPin={()=>{void act({kind:'pin',pinned:!snapshot.pinned} as Omit<WorkWindowAction,'token'>)}} onHide={()=>{void act({kind:'hide'})}} onSave={()=>void save()} onCopyColor={color=>{void navigator.clipboard.writeText(color).then(()=>feedback('已复制 '+color)).catch(()=>setError('复制失败，请重试。'))}} onRecover={()=>{void act({kind:'recover'})}} transferLabel="在资料库查看" onTransfer={id=>{void act({kind:'locate',assetId:id} as Omit<WorkWindowAction,'token'>)}} footerExtra={<button disabled={saving} title="关闭此窗口，保留工作集；未保存内容会先确认" aria-label={`关闭工作窗口 ${draft.name}`} onClick={()=>{const dirty=JSON.stringify(draft)!==JSON.stringify(valueOf(snapshot))||notebook?.hasUnsaved();if(dirty&&!window.confirm('关闭会放弃此窗口未保存的工作集和笔记草稿。继续吗？'))return;void act({kind:'close',discard:true} as Omit<WorkWindowAction,'token'>)}}>关闭窗口</button>} onRefresh={()=>{if(window.confirm('重新读取会放弃当前工作集草稿，是否继续？')){void act({kind:'discard-draft'}).then(r=>{if(r){draftRef.current=valueOf(r);baseRef.current=r.set.revision;setDraft(valueOf(r));setError('')}})}}}/>
 {focused&&notebook&&<FocusView asset={{id:focused.id,title:focused.title,src:src(focused.id),kind:'image',pixelLabel:'预览像素 1:1'}} items={focusItems} change={setFocus} close={()=>setFocus(null)} notebook={notebook} video={null} details={<div className="inspector-scroll"><h3>{focused.title}</h3><section className="detail-section"><p>{focused.aiCaption||'尚无画面描述'}</p><div className="tags">{focused.tags.map(t=><span key={t}>{t}</span>)}</div></section><button onClick={()=>{void act({kind:'locate',assetId:focused.id} as Omit<WorkWindowAction,'token'>)}}>在资料库检查与分析</button></div>}/>}
 </main>
}
