import React,{forwardRef,useEffect,useImperativeHandle,useRef,useState}from'react'
import{Hand,MousePointer2,Pencil,Square,Circle,Type,StickyNote,Plus,Minus,Maximize,Undo2,Redo2,Trash2,Save,X}from'lucide-react'
import type{GalleryAsset}from'./types'
import{NoteElement,NotePage,Notebook,Point,uid}from'./focus-notes'
export interface CanvasCommands{zoomBy:(factor:number)=>void;fit:()=>void;actual:()=>void;undo:()=>void;redo:()=>void;remove:()=>void;holdHand:(value:boolean)=>void;dismissOverlay:()=>boolean;canLeave:()=>boolean}
type Tool='hand'|'select'|'pen'|'rect'|'ellipse'|'text'|'sticky'
type Gesture={kind:'pan';x:number;y:number;px:number;py:number}|{kind:'draw';pageId:string;start:Point;element:NoteElement}
export const FocusCanvas=forwardRef<CanvasCommands,{asset:GalleryAsset;video:React.ReactNode;book:Notebook[string];update:(book:Notebook[string])=>void;save:()=>void;dirty:boolean;locked?:boolean;saveUnavailable?:string;onTransientChange?:(pending:boolean)=>void;media?:(onLoad:(image:HTMLImageElement)=>void)=>React.ReactNode}>(({asset,video,book,update,save,dirty,media,saveUnavailable,onTransientChange,locked=false},api)=>{
 const viewport=useRef<HTMLDivElement>(null),svg=useRef<SVGSVGElement>(null),gesture=useRef<Gesture|null>(null),history=useRef(new Map<string,{undo:NoteElement[][];redo:NoteElement[][]}>())
 const [size,setSize]=useState({w:800,h:600}),[natural,setNatural]=useState({w:480,h:560}),[view,setView]=useState({zoom:1,x:0,y:0}),[tool,setTool]=useState<Tool>('hand'),[heldHand,setHeldHand]=useState(false),[draft,setDraft]=useState<NoteElement|null>(null),[selected,setSelected]=useState<string|null>(null),[sticky,setSticky]=useState<string|null>(null),[color,setColor]=useState('#d96242'),[stroke,setStroke]=useState(3),[editor,setEditor]=useState<{kind:'text'|'sticky';x:number;y:number;id?:string;text:string}|null>(null)
 useEffect(()=>{onTransientChange?.(Boolean(editor||draft));return()=>onTransientChange?.(false)},[Boolean(editor),Boolean(draft),onTransientChange])
 const page=book.pages.find(p=>p.id===book.active),pageRef=useRef(page);pageRef.current=page
 const fitScale=Math.min(Math.max(1,size.w-36)/natural.w,Math.max(1,size.h-32)/natural.h),fw=natural.w*fitScale,fh=natural.h*fitScale
 const limit=(v:number)=>Math.max(.2,Math.min(8,v))
 const actual=()=>{const el=viewport.current;const img=el?.querySelector('img');const measured={w:el?.clientWidth||size.w,h:el?.clientHeight||size.h};const pixels={w:img?.naturalWidth||natural.w,h:img?.naturalHeight||natural.h};const scale=Math.min(Math.max(1,measured.w-36)/pixels.w,Math.max(1,measured.h-32)/pixels.h);setSize(measured);setNatural(pixels);setView({zoom:limit(1/scale),x:0,y:0})}
 const fit=()=>setView({zoom:1,x:0,y:0})
 const zoomBy=(factor:number)=>setView(v=>({...v,zoom:limit(v.zoom*factor)}))
 const replace=(elements:NoteElement[],remember=true)=>{if(!page)return;if(remember){const h=history.current.get(page.id)||{undo:[],redo:[]};h.undo=[...h.undo,page.elements].slice(-50);h.redo=[];history.current.set(page.id,h)}update({...book,pages:book.pages.map(p=>p.id===page.id?{...p,elements}:p)})}
 const undo=()=>{if(!page)return;const h=history.current.get(page.id);if(!h?.undo.length)return;const prev=h.undo.pop()!;h.redo.push(page.elements);replace(prev,false);setSelected(null)}
 const redo=()=>{if(!page)return;const h=history.current.get(page.id);if(!h?.redo.length)return;const next=h.redo.pop()!;h.undo.push(page.elements);replace(next,false);setSelected(null)}
 const remove=()=>{if(page&&selected){replace(page.elements.filter(e=>e.id!==selected));setSelected(null);setSticky(null)}}
 useImperativeHandle(api,()=>({zoomBy,fit,actual,undo,redo,remove,holdHand:setHeldHand,canLeave:()=>!editor&&gesture.current?.kind!=='draw',dismissOverlay:()=>{if(editor){setEditor(null);return true}if(sticky){setSticky(null);return true}return false}}))
 useEffect(()=>{const el=viewport.current;if(!el)return;const measure=()=>setSize({w:el.clientWidth,h:el.clientHeight});const observer=new ResizeObserver(measure);observer.observe(el);measure();const wheel=(e:WheelEvent)=>{e.preventDefault();const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;setView(v=>{const zoom=limit(v.zoom*Math.exp(-e.deltaY*.002));return{zoom,x:x-(x-v.x)*zoom/v.zoom,y:y-(y-v.y)*zoom/v.zoom}})};el.addEventListener('wheel',wheel,{passive:false});return()=>{observer.disconnect();el.removeEventListener('wheel',wheel)}},[])
 useEffect(()=>{gesture.current=null;setDraft(null);setSelected(null);setSticky(null);setEditor(null)},[book.active])
 const point=(e:React.PointerEvent):Point=>{const matrix=svg.current?.getScreenCTM();if(!matrix)return{x:0,y:0};const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());return{x:Math.max(0,Math.min(1000,p.x)),y:Math.max(0,Math.min(1000,p.y))}}
 const panStart=(e:React.PointerEvent)=>{if(e.button!==0&&e.button!==1)return;if((e.target as HTMLElement).closest?.('button,input,textarea,video,.annotation-editor,.sticky-popover'))return;if(!heldHand&&(e.target as Element).closest?.('[data-note-element=sticky]'))return;viewport.current?.focus({preventScroll:true});if(tool==='hand'||heldHand||e.button===1){e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);gesture.current={kind:'pan',x:e.clientX,y:e.clientY,px:view.x,py:view.y}}}
 const drawStart=(e:React.PointerEvent<SVGSVGElement>)=>{if(e.button!==0||!page||tool==='hand'||heldHand)return;e.preventDefault();e.stopPropagation();const p=point(e);if(tool==='text'||tool==='sticky'){setEditor({kind:tool,...p,text:''});return}if(tool==='select'){setSelected(null);setSticky(null);return}e.currentTarget.setPointerCapture(e.pointerId);const element:NoteElement={id:uid(),kind:tool,...p,width:0,height:0,points:tool==='pen'?[p]:undefined,color,stroke};gesture.current={kind:'draw',pageId:page.id,start:p,element};setDraft(element)}
 const move=(e:React.PointerEvent)=>{const g=gesture.current;if(!g)return;if(g.kind==='pan'){setView(v=>({...v,x:g.px+e.clientX-g.x,y:g.py+e.clientY-g.y}));return}const p=point(e);if(g.pageId!==pageRef.current?.id)return;let element:NoteElement;if(g.element.kind==='pen'){const points=g.element.points||[];if(points.length>=2000)return;const last=points[points.length-1];if(last&&Math.hypot(last.x-p.x,last.y-p.y)<1)return;element={...g.element,points:[...points,p]}}else element={...g.element,x:Math.min(g.start.x,p.x),y:Math.min(g.start.y,p.y),width:Math.abs(g.start.x-p.x),height:Math.abs(g.start.y-p.y)};gesture.current={...g,element};setDraft(element)}
 const finish=()=>{const g=gesture.current;gesture.current=null;setDraft(null);if(g?.kind!=='draw'||g.pageId!==pageRef.current?.id)return;const el=g.element;if(el.kind==='pen'?(el.points?.length||0)<2:(el.width||0)<3||(el.height||0)<3)return;replace([...(page?.elements||[]),el]);setSelected(el.id)}
 const showEditor=(el:NoteElement)=>{if(el.kind==='text'||el.kind==='sticky')setEditor({kind:el.kind,x:el.x,y:el.y,id:el.id,text:el.text||''})}
 const drawElement=(el:NoteElement,isDraft=false)=>{const selectedStroke=selected===el.id?el.stroke+1:el.stroke;const props={stroke:el.color,strokeWidth:selectedStroke,fill:'none',vectorEffect:'non-scaling-stroke' as const};let content:React.ReactNode
  if(el.kind==='pen')content=<polyline points={el.points?.map(p=>`${p.x},${p.y}`).join(' ')} {...props} strokeLinecap="round" strokeLinejoin="round"/>
  else if(el.kind==='rect')content=<rect x={el.x} y={el.y} width={el.width} height={el.height} {...props}/>
  else if(el.kind==='ellipse')content=<ellipse cx={el.x+(el.width||0)/2} cy={el.y+(el.height||0)/2} rx={(el.width||0)/2} ry={(el.height||0)/2} {...props}/>
  else if(el.kind==='text')content=<text x={el.x} y={el.y} fill={el.color} fontSize="30" fontFamily="system-ui,sans-serif">{(el.text||'').split('\n').map((line,i)=><tspan key={i} x={el.x} dy={i?38:0}>{line}</tspan>)}</text>
  else{const n=(page?.elements.filter(e=>e.kind==='sticky').findIndex(e=>e.id===el.id)||0)+1;content=<><circle cx={el.x} cy={el.y} r="23" fill="#f0ce79"/><text x={el.x} y={el.y+8} fill="#4a3916" fontSize="24" textAnchor="middle" fontFamily="system-ui">{n}</text></>}
  return <g key={el.id} data-note-element={isDraft?undefined:el.kind} role={el.kind==='sticky'?'button':undefined} tabIndex={el.kind==='sticky'?0:undefined} aria-label={el.kind==='sticky'?`显示便签 ${(page?.elements.filter(e=>e.kind==='sticky').findIndex(e=>e.id===el.id)||0)+1}`:undefined} onPointerDown={e=>{if(tool==='select'||el.kind==='sticky'){e.stopPropagation();setSelected(el.id);if(el.kind==='sticky')setSticky(sticky===el.id?null:el.id)}}} onDoubleClick={e=>{e.stopPropagation();showEditor(el)}} onKeyDown={e=>{if(el.kind==='sticky'&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.stopPropagation();setSelected(el.id);setSticky(el.id)}}} style={{cursor:el.kind==='sticky'?'pointer':tool==='select'?'pointer':'inherit',pointerEvents:isDraft?'none':'auto'}}>{content}</g>}
 const selectedSticky=page?.elements.find(e=>e.id===sticky&&e.kind==='sticky')
 const addPage=()=>{if(editor||gesture.current)return;let n=book.pages.length+1;while(book.pages.some(p=>p.name===`笔记 ${n}`))n++;const next:NotePage={id:uid(),name:`笔记 ${n}`,elements:[]};update({pages:[...book.pages,next],active:next.id});setTool('pen')}
 const h=page?history.current.get(page.id):null
 return <div className="focus-canvas" data-active-note={page?.id||'original'} {...(locked?{inert:''}:{})} aria-busy={locked||undefined}>
  <div className="canvas-tools"><div><button aria-label="缩小图片" title="缩小（-）" onClick={()=>zoomBy(1/1.2)}><Minus/></button><button aria-label="放大图片" title="放大（+）" onClick={()=>zoomBy(1.2)}><Plus/></button><button className="zoom-value" aria-label={asset.pixelLabel||"原始尺寸"} title={`${asset.pixelLabel||"原始尺寸"}（1）`} onClick={actual}>{Math.round(view.zoom*fitScale*100)}%</button><button aria-label="适应窗口" title="适应窗口（0）" onClick={fit}><Maximize/></button></div><div className="annotation-tools">{[{id:'hand',label:'移动画布',Icon:Hand},{id:'select',label:'选择标注',Icon:MousePointer2},{id:'pen',label:'画笔',Icon:Pencil},{id:'rect',label:'矩形',Icon:Square},{id:'ellipse',label:'椭圆',Icon:Circle},{id:'text',label:'文字',Icon:Type},{id:'sticky',label:'便签',Icon:StickyNote}].map(({id,label,Icon})=><button key={id} disabled={id!=='hand'&&(!page||asset.kind==='video')} className={tool===id?'active':''} aria-label={label} title={label} onClick={()=>{setTool(id as Tool);setSelected(null);setEditor(null)}}><Icon/></button>)}</div>{page&&asset.kind!=='video'&&<div><input type="color" aria-label="标注颜色" value={color} onChange={e=>setColor(e.target.value)}/><select aria-label="画笔粗细" value={stroke} onChange={e=>setStroke(Number(e.target.value))}>{[2,3,5,8].map(n=><option key={n} value={n}>{n}px</option>)}</select><button aria-label="撤销标注" disabled={!h?.undo.length} onClick={undo}><Undo2/></button><button aria-label="重做标注" disabled={!h?.redo.length} onClick={redo}><Redo2/></button><button aria-label="删除选中标注" disabled={!selected} onClick={remove}><Trash2/></button></div>}<button className="note-save" disabled={Boolean(saveUnavailable)} title={saveUnavailable} onClick={save}><Save size={14}/>保存笔记{dirty&&<span aria-hidden="true">•</span>}</button></div>
  <div className={`canvas-viewport ${tool==='hand'||heldHand?'hand-tool':'draw-tool'}`} ref={viewport} tabIndex={0} aria-label="图片标注画布" onPointerDownCapture={panStart} onPointerMove={move} onPointerUp={finish} onPointerCancel={()=>{gesture.current=null;setDraft(null)}} data-zoom={view.zoom} data-pan-x={view.x} data-pan-y={view.y}>
   {asset.kind==='video'?<div className="canvas-video">{video}<p>视频使用参考帧；绘图笔记先用于静态预览。</p></div>:<div className="canvas-image-frame" style={{width:fw,height:fh,transform:`translate(-50%,-50%) translate(${view.x}px,${view.y}px) scale(${view.zoom})`}}>{media?media(image=>setNatural({w:image.naturalWidth,h:image.naturalHeight})):<img src={asset.src} alt={asset.title} draggable={false} onLoad={e=>setNatural({w:e.currentTarget.naturalWidth,h:e.currentTarget.naturalHeight})}/>}<svg ref={svg} viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="笔记绘图层" onPointerDown={drawStart}>{page?.elements.map(e=>drawElement(e))}{draft&&drawElement(draft,true)}</svg></div>}
   {!page&&asset.kind!=='video'&&<span className="canvas-help">滚轮或 + / − 缩放 · 拖动查看 · 0 适应 · 1 {asset.pixelLabel||"原始尺寸"}</span>}
   {selectedSticky&&<div className="sticky-popover" role="dialog" aria-label="便签内容" style={{left:Math.max(12,Math.min(size.w-252,size.w/2+view.x+(selectedSticky.x/1000-.5)*fw*view.zoom+18)),top:Math.max(12,Math.min(size.h-180,size.h/2+view.y+(selectedSticky.y/1000-.5)*fh*view.zoom+18))}}><header><strong>便签</strong><button aria-label="关闭便签" onClick={()=>setSticky(null)}><X size={13}/></button></header><p>{selectedSticky.text}</p><button onClick={()=>showEditor(selectedSticky)}>编辑便签</button></div>}
   {editor&&<div className="annotation-editor" role="dialog" aria-label={editor.kind==='sticky'?'编辑便签':'编辑文字'}><strong>{editor.kind==='sticky'?'便签内容':'文字内容'}</strong><textarea autoFocus aria-label="标注文字内容" value={editor.text} maxLength={2000} onChange={e=>setEditor({...editor,text:e.target.value})}/><div><button onClick={()=>setEditor(null)}>取消</button><button disabled={!editor.text.trim()} onClick={()=>{if(!page)return;const el:NoteElement={id:editor.id||uid(),kind:editor.kind,x:editor.x,y:editor.y,text:editor.text,color,stroke};replace(editor.id?page.elements.map(e=>e.id===editor.id?el:e):[...page.elements,el]);setSelected(el.id);setSticky(el.kind==='sticky'?el.id:null);setEditor(null)}}>保存标注</button></div></div>}
  </div>
  <div className="note-page-strip" aria-label="图片笔记页"><button className={!page?'active':''} onClick={()=>{if(editor||gesture.current)return;update({...book,active:null});setTool('hand')}}>原图</button>{book.pages.map(p=><button key={p.id} className={book.active===p.id?'active':''} aria-label={`切换 ${p.name}`} onClick={()=>{if(!editor&&!gesture.current)update({...book,active:p.id})}}><span className="note-miniature">{p.elements.length?<Pencil size={15}/>:<Square size={15}/>}<small>{p.elements.length}</small></span><span>{p.name}</span></button>)}<button className="add-note" disabled={asset.kind==='video'} title={asset.kind==='video'?'绘图笔记先支持静态预览':'创建独立笔记页'} onClick={addPage}><Plus size={18}/>添加笔记</button>{page&&<label className="note-page-name">名称<input aria-label="笔记名称" value={page.name} maxLength={40} onChange={e=>update({...book,pages:book.pages.map(p=>p.id===page.id?{...p,name:e.target.value}:p)})}/></label>}</div>
 </div>
})
