import React,{useEffect,useRef,useState}from'react'
import{X,ChevronLeft,ChevronRight}from'lucide-react'
import type{GalleryAsset}from'./types'
import{FocusCanvas,CanvasCommands}from'./FocusCanvas'
import type{Notebook}from'./focus-notes'
export interface NotebookAdapter{setTransient?:(pending:boolean)=>void;load:()=>Notebook;hold:(book:Notebook)=>void;save:(book:Notebook,assetId?:string,allowUpgrade?:boolean)=>void|Promise<void>;dirty:(assetId?:string)=>boolean;ensure?:(assetId:string)=>Promise<Notebook>;reconcile?:(assetId:string)=>Promise<Notebook>;requiresUpgrade?:(assetId:string)=>boolean;saveLabel:string;saveUnavailable?:string}
export function FocusView({asset,items,change,close,details,video,overlay,notebook,media}:{asset:GalleryAsset;items:GalleryAsset[];change:(id:string)=>void;close:()=>void;details:React.ReactNode;video:React.ReactNode;overlay?:React.ReactNode;notebook:NotebookAdapter;media?:(onLoad:(image:HTMLImageElement)=>void)=>React.ReactNode}){
 const dialog=useRef<HTMLDialogElement>(null),canvas=useRef<CanvasCommands>(null)
 const [loading,setLoading]=useState(Boolean(notebook.ensure)),[loadError,setLoadError]=useState(''),[retry,setRetry]=useState(0),[saving,setSaving]=useState(false),[confirmUpgrade,setConfirmUpgrade]=useState(false),[conflict,setConflict]=useState(false)
 const mounted=useRef(true),booksRef=useRef<Notebook>(notebook.load())
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
 const [books,setBooks]=useState<Notebook>(notebook.load),[dirty,setDirty]=useState(()=>notebook.dirty(asset.id)),[status,setStatus]=useState(notebook.saveUnavailable?'会话笔记 · 关库或退出后清除':'')
 useEffect(()=>{const previous=document.activeElement as HTMLElement;dialog.current?.showModal();return()=>previous?.focus({preventScroll:true})},[])
 useEffect(()=>{dialog.current?.querySelector(`[data-focus-id="${asset.id}"]`)?.scrollIntoView({block:'nearest',inline:'center'})},[asset.id])

 useEffect(()=>{let cancelled=false;setConfirmUpgrade(false);setConflict(false);setLoadError('');setDirty(notebook.dirty(asset.id));if(!notebook.ensure){setLoading(false);return}setLoading(true);notebook.ensure(asset.id).then(next=>{if(!cancelled){booksRef.current=next;setBooks(next);setDirty(notebook.dirty(asset.id));setLoading(false)}}).catch(()=>{if(!cancelled){setLoading(false);setLoadError('笔记读取失败，未覆盖任何已有内容。')}});return()=>{cancelled=true}},[asset.id,notebook,retry])
 const navigate=(id:string)=>{if(confirmUpgrade)return;if(saving){setStatus('正在保存，请稍候。');return}if(canvas.current&&!canvas.current.canLeave()){setStatus('请先保存或取消当前标注，并结束绘制。');return}setStatus('');change(id)}
 const requestClose=()=>{if(confirmUpgrade){setConfirmUpgrade(false);return}if(saving){setStatus('正在保存，请稍候。');return}if(canvas.current&&!canvas.current.canLeave()){setStatus('请先保存或取消当前标注，并结束绘制。');return}close()}
 const index=items.findIndex(a=>a.id===asset.id),step=(n:number)=>{const target=items[index+n];if(target)navigate(target.id)}
 const update=(book:Notebook[string])=>{if(loading||loadError)return;const next={...booksRef.current,[asset.id]:book};booksRef.current=next;setBooks(next);notebook.hold(next);setDirty(true);setStatus('')}
 const save=async(allowUpgrade=false)=>{if(saving||loading||loadError)return;if(canvas.current&&!canvas.current.canLeave()){setStatus('请先保存或取消当前标注，并结束绘制。');return}if(notebook.requiresUpgrade?.(asset.id)&&!allowUpgrade){setConfirmUpgrade(true);return}setConfirmUpgrade(false);setConflict(false);setSaving(true);try{await notebook.save(booksRef.current,asset.id,allowUpgrade);if(mounted.current){const remains=notebook.dirty(asset.id);setDirty(remains);setStatus(remains?'此次保存已完成；新改动尚未保存。':notebook.saveLabel)}}catch(error){if(mounted.current){setConflict((error as {code?:string})?.code==='notebook-conflict');setDirty(true);setStatus(error instanceof Error?error.message+' 当前草稿保留，可重试。':'保存失败，当前草稿保留，可重试。')}}finally{if(mounted.current)setSaving(false)}}

 const reconcile=async()=>{try{const next=await notebook.reconcile?.(asset.id);if(next&&mounted.current){booksRef.current=next;setBooks(next);setDirty(true);setConflict(false);setStatus('已载入最新版本，改动保留为冲突草稿页。请核对后保存。')}}catch{setStatus('暂不能合并，当前草稿保留。')}}
 return <dialog className="focus-mode focus-notebook-mode" ref={dialog} aria-label="专注模式" aria-modal="true" onCancel={e=>{e.preventDefault();if(confirmUpgrade){setConfirmUpgrade(false);return}if(!canvas.current?.dismissOverlay())requestClose()}} onKeyUp={e=>{if(e.code==='Space')canvas.current?.holdHand(false)}} onKeyDown={e=>{
  if(confirmUpgrade)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();e.stopPropagation();void save();return}const t=e.target as HTMLElement;if(t.closest('input,textarea,select,video,[contenteditable=true]'))return
  if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)canvas.current?.redo();else canvas.current?.undo();return}
  if(['+','=','-','0','1'].includes(e.key)){e.preventDefault();if(e.key==='0')canvas.current?.fit();else if(e.key==='1')canvas.current?.actual();else canvas.current?.zoomBy(e.key==='-'?1/1.2:1.2);return}
  if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();canvas.current?.remove();return}
  if(e.code==='Space'&&t.closest('.canvas-viewport')){e.preventDefault();canvas.current?.holdHand(true);return}
  if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();step(e.key==='ArrowLeft'?-1:1)}
 }}>
  <header className="focus-header"><span>专注模式 <small>{index+1} / {items.length}</small></span><span className="focus-title">{asset.title}</span>{(status||notebook.saveUnavailable)&&<span className="note-save-status" title={status||notebook.saveUnavailable} role="status">{status||"会话笔记 · 关库或退出后清除"}</span>}{conflict&&notebook.reconcile&&<button onClick={()=>void reconcile()}>保留草稿并载入最新笔记</button>}<div className="focus-header-actions"><button className="icon" aria-label="上一张" disabled={index<=0} onClick={()=>step(-1)}><ChevronLeft/></button><button className="icon" aria-label="下一张" disabled={index>=items.length-1} onClick={()=>step(1)}><ChevronRight/></button><button className="icon" aria-label="关闭专注模式" onClick={requestClose}><X/></button></div></header>
  <div className="focus-main"><div className="focus-stage focus-editing-stage" aria-label="专注素材预览">{loading||loadError?<div className="notebook-read-state" role={loadError?"alert":"status"}>{loadError||"正在读取笔记…"}{loadError&&<button onClick={()=>setRetry(v=>v+1)}>重新读取笔记</button>}</div>:<FocusCanvas key={asset.id} ref={canvas} asset={asset} video={video} book={books[asset.id]||{pages:[],active:null}} update={update} save={()=>{void save()}} dirty={dirty} media={media} onTransientChange={notebook.setTransient} saveUnavailable={saving?'正在保存…':notebook.saveUnavailable}/> }</div><aside className="focus-details" aria-label="专注素材信息">{details}</aside></div>
  {confirmUpgrade&&<div className="notebook-upgrade-backdrop"><div className="notebook-upgrade" role="alertdialog" aria-label="启用笔记保存" onKeyDown={e=>{if(e.key==='Tab'){e.preventDefault();const buttons=Array.from(e.currentTarget.querySelectorAll('button'));const i=buttons.indexOf(document.activeElement as HTMLButtonElement);buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length]?.focus()}}}><h3>启用笔记保存</h3><p>首次保存会将当前素材库升级为 v5，旧版应用将无法打开此库。笔记独立保存，原图不变；取消不会修改库结构。</p><div><button autoFocus onClick={()=>setConfirmUpgrade(false)}>取消</button><button onClick={()=>void save(true)}>升级并保存笔记</button></div></div></div>}
  <nav className="focus-filmstrip" aria-label="专注图片画廊">{items.map(a=><button key={a.id} data-focus-id={a.id} aria-label={`切换到 ${a.title}`} aria-current={a.id===asset.id?'true':undefined} className={a.id===asset.id?'active':''} onClick={()=>navigate(a.id)}><img src={a.src} alt=""/><span>{a.title.split(' · ')[0]}</span></button>)}</nav>{overlay}
 </dialog>
}
