import React from 'react'
import {Grip,Pin,X,Folder,Palette,Save,Plus,ArrowLeft,ArrowRight,Maximize2,Minus,Check,Loader2} from 'lucide-react'
export interface WorkReferenceItem{id:string;title:string;src?:string;unavailable?:boolean}
export function WorkReferencePanel(p:{name:string;items:WorkReferenceItem[];note:string;colors:string[];pinned:boolean;nativeControls?:boolean;dirty:boolean;saving?:boolean;columns?:number;fitColumns?:boolean;error?:string;status?:string;style?:React.CSSProperties;onHeaderPointerDown?:React.PointerEventHandler;grip?:React.ReactNode;resizeGrip?:React.ReactNode;extra?:React.ReactNode;footerExtra?:React.ReactNode;onInspect:(id:string)=>void;onPreview:(id:string)=>void;onRemove:(id:string)=>void;onMove?:(id:string,delta:number)=>void;onAdd?:()=>void;onNote:(note:string)=>void;onColors:(colors:string[])=>void;onColumns?:(n:number)=>void;onPin:()=>void;onHide:()=>void;onSave:()=>void;onCopyColor:(color:string)=>void;colorMenu?:(e:React.MouseEvent<HTMLElement>|React.KeyboardEvent<HTMLElement>,color:string)=>void;onTransfer?:(id:string)=>void;onDragStart?:(e:React.DragEvent,id:string)=>void;transferLabel?:string;onRecover?:()=>void;onRefresh?:()=>void}){
 return <section className={`reference-window glass ${p.pinned?'pinned':''}`} style={p.style} aria-label={p.name}>
 <header className="window-title" onPointerDown={p.onHeaderPointerDown}>{p.grip||<span className="grip"><Grip size={16}/></span>}<div><strong>{p.name}</strong><small role="status" aria-live="polite" data-save-state={p.saving?'saving':p.dirty?'dirty':'saved'}>{p.items.length} 份参考 · {p.saving?'保存中…':p.dirty?'有未保存更改':'已保存'}</small></div>{p.onRecover&&<button className="icon" aria-label="找回窗口" title="移回当前屏幕的可见区域" onClick={p.onRecover}><Maximize2 size={15}/></button>}{p.nativeControls!==false&&<><button className={`icon ${p.pinned?'active':''}`} aria-pressed={p.pinned} title={p.pinned?'已置顶，点击取消置顶':'置顶显示在其他应用上方'} aria-label={`${p.pinned?'取消':'开启'}置顶 ${p.name}`} onClick={p.onPin}><Pin size={15}/></button><button className="icon" aria-label={`隐藏 ${p.name}`} title="隐藏窗口并保留草稿，可从工作模式恢复" disabled={p.saving} onClick={p.onHide}><Minus size={16}/></button></>}</header>
 <div className="window-body">{p.onAdd&&<div className="reference-actions"><button onClick={p.onAdd}><Plus size={14}/>添加参考</button>{p.onColumns&&<label>排列<select title="最多显示的列数；参考较少时自动填满" aria-label="参考列数" value={p.columns||2} onChange={e=>p.onColumns?.(Number(e.target.value))}>{[1,2,3,4].map(n=><option key={n} value={n}>{n}列</option>)}</select></label>}</div>}
 <div className="reference-grid" style={p.columns?{gridTemplateColumns:`repeat(${p.fitColumns?Math.max(1,Math.min(p.columns,p.items.length||1)):p.columns},minmax(0,1fr))`}:undefined}>{p.items.map((a,i)=><div className="reference-item" key={a.id}><button className="reference-picture" aria-label={`查看参考 ${a.title}`} disabled={a.unavailable} title="单击查看 · 空格快速预览" onClick={()=>p.onInspect(a.id)} onKeyDown={e=>{if(e.code==='Space'){e.preventDefault();e.stopPropagation();if(!e.repeat)p.onPreview(a.id)}}} onKeyUp={e=>{if(e.code==='Space')e.preventDefault()}} draggable={Boolean(p.onDragStart)&&!a.unavailable} onDragStart={e=>p.onDragStart?.(e,a.id)}>{a.unavailable?<span className="missing">素材暂不可用<br/><small>引用仍保留</small></span>:<img src={a.src} alt={a.title} loading="lazy" decoding="async"/>}</button><div className="reference-caption"><span>{a.title.split(' · ')[0]}</span><button className="icon" title="仅移除此参考，不删除素材" aria-label={`从 ${p.name} 移除 ${a.title}`} onClick={()=>p.onRemove(a.id)}><X size={13}/></button></div><div className="reference-item-actions">{p.onMove&&<div className="reference-order"><button className="icon" aria-label={`前移 ${a.title}`} disabled={i===0} onClick={()=>p.onMove?.(a.id,-1)}><ArrowLeft size={12}/></button><button className="icon" aria-label={`后移 ${a.title}`} disabled={i===p.items.length-1} onClick={()=>p.onMove?.(a.id,1)}><ArrowRight size={12}/></button></div>}{p.onTransfer&&<button className="tiny transfer" disabled={a.unavailable} onClick={()=>p.onTransfer?.(a.id)}>{p.transferLabel||'在资料库中复用'}</button>}</div></div>)}</div>
 {!p.items.length&&<div className="empty compact"><Folder/><p>这个工作集还没有参考</p><small>从资料库选择素材并加入</small></div>}{p.extra}
 <section className="window-swatches" aria-label={`${p.name} 色板`}><h3><Palette size={14}/>色板 <small>{p.colors.length} 色</small></h3>{p.colors.length?<div className="saved-swatches">{p.colors.map(c=><div key={c}><button className="swatch" style={{background:c}} title={`复制 ${c}`} aria-label={`复制工作颜色 ${c}`} onClick={()=>p.onCopyColor(c)} onContextMenu={e=>p.colorMenu?.(e,c)} onKeyDown={e=>{if(e.key==='ContextMenu'||e.shiftKey&&e.key==='F10')p.colorMenu?.(e,c)}}/><span>{c}</span><button className="icon" aria-label={`移除工作颜色 ${c}`} onClick={()=>p.onColors(p.colors.filter(v=>v!==c))}><X size={12}/></button></div>)}</div>:<p>从图片配色或色板添加这次设计用色。</p>}</section>
 <label className="note-label">工作备注<textarea aria-label="工作备注" value={p.note} maxLength={16000} onChange={e=>p.onNote(e.target.value)} placeholder="记录这次设计关注的细节…" spellCheck={false} rows={3}/></label>{p.error&&<div role="alert" className="work-window-error">{p.error}{p.onRefresh&&<button onClick={p.onRefresh}>重新读取工作集</button>}</div>}</div>
 <footer><span className="work-footer-hint" title="工作集只保存引用，移除成员不会删除库中素材">移除参考不会删除素材</span>{p.status&&<span className="work-window-status" role="status" aria-live="polite">{p.status}</span>}{p.footerExtra}<button className="work-save" disabled={p.saving} title="保存工作集及布局（⌘ / Ctrl + S）" aria-label={`保存 ${p.name}`} onClick={p.onSave}>{p.saving?<Loader2 size={14}/>:p.dirty?<Save size={14}/>:<Check size={14}/>}<span>{p.saving?'保存中':'保存'}</span></button></footer>{p.resizeGrip}
 </section>
}
