import { createLibraryStartTracer } from './library-start.tracer'
import {
  readExactPlainDataRecord,
  snapshotPlainDataRecord
} from './plain-data-record.internal'

/** Main-only read Adapter. Tests supply generated bytes; no filesystem is opened. */
export interface LibraryManifestReadAdapter {
  read(): unknown | Promise<unknown>
}

/** Compose Manifest declaration inspection behind the existing Library Start Interface. */
export function createLibraryManifestTracer(adapter: LibraryManifestReadAdapter) {
  return createLibraryStartTracer({ observe: async () =>
    inspectManifestSource(await adapter.read()) })
}

const MAX_MANIFEST_BYTES = 16 * 1024
const OPAQUE_ID = /^[A-Za-z0-9][A-Za-z0-9._~-]{0,127}$/u

/** Validated Main-internal declarations; never a public Library authority. */
export interface LibraryManifestDeclaration {
  readonly lineageIdentity: string
  readonly libraryIdentity: string
  readonly controlStoreIdentity: string
  readonly managedOriginalsRelativePath: string
}

export function readLibraryManifestDeclaration(value: unknown):
  | Readonly<{ kind: 'compatible'; declaration: LibraryManifestDeclaration }>
  | Readonly<{ kind: 'unsupported' | 'invalid' }> {
  const manifest = decodeCanonicalJson(value)
  if (!manifest) return { kind: 'invalid' }
  const kind = validateManifest(manifest)
  if (kind !== 'compatible') return { kind }
  const identity = manifest.libraryIdentity as { lineage: string; instance: string }
  const store = manifest.controlStore as { identity: string }
  const originals = manifest.managedOriginals as { relativePath: string }
  return Object.freeze({
    kind,
    declaration: Object.freeze({
      lineageIdentity: identity.lineage,
      libraryIdentity: identity.instance,
      controlStoreIdentity: store.identity,
      managedOriginalsRelativePath: originals.relativePath
    })
  })
}

/** Encode proposed v1 metadata in memory, using the same declaration policy. */
export function encodeLibraryManifestDeclaration(
  declaration: LibraryManifestDeclaration
): Uint8Array | undefined {
  const fields = readExactPlainDataRecord(declaration, [
    'lineageIdentity', 'libraryIdentity', 'controlStoreIdentity', 'managedOriginalsRelativePath'
  ])
  if (!fields || Object.values(fields).some((value) => typeof value !== 'string')) return undefined
  const bytes = new TextEncoder().encode(JSON.stringify({
    format: 'design-asset-library', manifestSchemaVersion: 1,
    libraryIdentity: { lineage: fields.lineageIdentity, instance: fields.libraryIdentity },
    controlStore: { identity: fields.controlStoreIdentity, schemaVersion: 1 },
    applicationCompatibility: { minimumReaderLevel: 1, writerLevel: 1 },
    managedOriginals: { relativePath: fields.managedOriginalsRelativePath }
  }))
  return readLibraryManifestDeclaration(bytes).kind === 'compatible' ? bytes : undefined
}

function inspectManifestSource(value: unknown): Readonly<{ kind: string }> {
  const source = readExactPlainDataRecord(value, [
    'manifestBytes', 'targetState', 'legacyEvidence'
  ])
  if (!source || !isStringChoice(source.targetState, ['empty', 'non-empty', 'unknown']) ||
    !isStringChoice(source.legacyEvidence, ['present', 'absent', 'not-assessed'])) {
    return { kind: 'manifest-invalid' }
  }
  if (source.manifestBytes === null) {
    if (source.targetState === 'empty' && source.legacyEvidence === 'absent') {
      return { kind: 'missing' }
    }
    if (source.targetState === 'non-empty' && source.legacyEvidence === 'present') {
      return { kind: 'legacy' }
    }
    return { kind: 'not-assessed' }
  }
  if (source.legacyEvidence === 'present') return { kind: 'manifest-invalid' }

  const result = readLibraryManifestDeclaration(source.manifestBytes).kind
  return { kind: result === 'compatible' ? 'manifest-compatible'
    : result === 'unsupported' ? 'manifest-unsupported' : 'manifest-invalid' }
}

function isStringChoice(value: unknown, choices: readonly string[]): value is string {
  return typeof value === 'string' && choices.includes(value)
}

function decodeCanonicalJson(value: unknown): Record<string, unknown> | undefined {
  try {
    const bytes = snapshotBytes(value)
    if (!bytes || (bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf)) {
      return undefined
    }
    const text = new TextDecoder('utf-8', { fatal: true }).decode(bytes)
    const parsed: unknown = JSON.parse(text)
    if (JSON.stringify(parsed) !== text) return undefined
    return snapshotPlainDataRecord(parsed, 12)
  } catch {
    return undefined
  }
}

function snapshotBytes(value: unknown): Uint8Array | undefined {
  try {
    if (!ArrayBuffer.isView(value) || Object.getPrototypeOf(value) !== Uint8Array.prototype) {
      return undefined
    }
    const keys = Reflect.ownKeys(value)
    if (keys.length === 0 || keys.length > MAX_MANIFEST_BYTES ||
      keys.some((key, index) => key !== String(index))) return undefined
    if (typeof SharedArrayBuffer !== 'undefined' &&
      (value as Uint8Array).buffer instanceof SharedArrayBuffer) return undefined
    const copy = new Uint8Array(keys.length)
    for (let index = 0; index < copy.length; index++) {
      copy[index] = (value as Uint8Array)[index]
    }
    return copy
  } catch {
    return undefined
  }
}

function validateManifest(manifest: Record<string, unknown>): 'compatible' | 'unsupported' | 'invalid' {
  if (Number.isSafeInteger(manifest.manifestSchemaVersion) &&
    Number(manifest.manifestSchemaVersion) > 1) return 'unsupported'
  const root = readExactPlainDataRecord(manifest, [
    'format', 'manifestSchemaVersion', 'libraryIdentity', 'controlStore',
    'applicationCompatibility', 'managedOriginals'
  ])
  if (!root || root.format !== 'design-asset-library' || root.manifestSchemaVersion !== 1) {
    return 'invalid'
  }
  const identity = readExactPlainDataRecord(manifest.libraryIdentity, ['lineage', 'instance'])
  const storeVersion = snapshotPlainDataRecord(manifest.controlStore, 8)
  if (storeVersion && Number.isSafeInteger(storeVersion.schemaVersion) &&
    Number(storeVersion.schemaVersion) > 1) return 'unsupported'
  const store = readExactPlainDataRecord(manifest.controlStore, ['identity', 'schemaVersion'])
  const compatibility = readExactPlainDataRecord(manifest.applicationCompatibility, [
    'minimumReaderLevel', 'writerLevel'
  ])
  const originals = readExactPlainDataRecord(manifest.managedOriginals, ['relativePath'])
  if (!identity || !store || !compatibility || !originals) return 'invalid'
  const ids = [identity.lineage, identity.instance, store.identity]
  if (store.schemaVersion !== 1 ||
    !ids.every((id) => typeof id === 'string' && OPAQUE_ID.test(id)) ||
    new Set(ids).size !== ids.length || !isSafeManagedOriginalsBinding(originals.relativePath) ||
    !Number.isSafeInteger(compatibility.minimumReaderLevel) ||
    !Number.isSafeInteger(compatibility.writerLevel) ||
    Number(compatibility.minimumReaderLevel) < 1 ||
    Number(compatibility.writerLevel) < Number(compatibility.minimumReaderLevel)) return 'invalid'
  return Number(compatibility.minimumReaderLevel) > 1 ? 'unsupported' : 'compatible'
}

const RESERVED_ROLE_SEGMENTS = new Set([
  'cache', 'caches', 'runtime', 'runtimes', 'model', 'models', 'plugin', 'plugins'
])
const WINDOWS_DEVICE_NAME = /^(?:con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/iu

function isSafeManagedOriginalsBinding(value: unknown): value is string {
  if (typeof value !== 'string' || value.length === 0 || value.length > 240 ||
    value !== value.normalize('NFC') || /[\u0000-\u001F\u007F\\:*?"<>|]/u.test(value) ||
    value.startsWith('/') || value.startsWith('~') || value.endsWith('/')) return false
  const encoded = new TextEncoder().encode(value)
  if (new TextDecoder('utf-8', { fatal: true }).decode(encoded) !== value) return false
  const segments = value.split('/')
  if (segments.length > 8 || encoded.byteLength > 240) return false
  return segments.every((segment) => {
    const folded = segment.toLowerCase()
    return segment.length > 0 && Array.from(segment).length <= 120 &&
      segment !== '.' && segment !== '..' && !segment.startsWith('.') &&
      !segment.endsWith('.') && !segment.endsWith(' ') &&
      !RESERVED_ROLE_SEGMENTS.has(folded) && !WINDOWS_DEVICE_NAME.test(folded)
  })
}
