/** Generated by seal-pi-runtime; app-bundled release identity, not user-editable runtime metadata. */
export const PI_RUNTIME_RELEASE_SHA256="a93f68a80369ad3cd6ce1f583d8a7cf0110b14545f6c2244c42a4dba4b27287f"
