import { CHANNEL_CONNECTED_CLEANUP_CANDIDATES, CHANNEL_CONNECTED_CONFIRM, CHANNEL_CONNECTED_CONFIRM_CLEANUP, CHANNEL_CONNECTED_CONFLICTS, CHANNEL_CONNECTED_DISCONNECT, CHANNEL_CONNECTED_INDEX_NEXT, CHANNEL_CONNECTED_INSPECT, CHANNEL_CONNECTED_LIST, CHANNEL_CONNECTED_MEDIA_PREVIEW, CHANNEL_CONNECTED_OPERATIONS, CHANNEL_CONNECTED_PREPARE, CHANNEL_CONNECTED_PREPARE_FILE, CHANNEL_CONNECTED_PREPARE_NEW, CHANNEL_CONNECTED_QUEUE_LIFECYCLE, CHANNEL_CONNECTED_QUEUE_METADATA, CHANNEL_CONNECTED_RESOLVE_CONFLICT, CHANNEL_CONNECTED_SEARCH, CHANNEL_CONNECTED_SYNC, CHANNEL_LEGACY_CLOSE, CHANNEL_LEGACY_CONFIRM, CHANNEL_LEGACY_INSPECT, CHANNEL_LEGACY_LIST, CHANNEL_LEGACY_MEDIA_PREVIEW, CHANNEL_LEGACY_PREPARE, CHANNEL_LEGACY_SEARCH, type ConnectedLibraryScope, type ConnectedMetadataPatch } from '../shared/contracts/external-connected-library.contract';
export interface ConnectedLibraryPreloadInvoker {
    invoke(channel: string, request?: unknown): Promise<any>;
}
export function createExternalConnectedLibraryPreloadApi(invoker: ConnectedLibraryPreloadInvoker) {
    const invoke = async (channel: string, request?: unknown) => { const result = request === undefined ? await invoker.invoke(channel) : await invoker.invoke(channel, request); return result?.success ? result.value : result; };
    return Object.freeze({
        connectedLibrary: { inspect: () => invoke(CHANNEL_CONNECTED_INSPECT), prepare: (scope: ConnectedLibraryScope, requestedGrant: 'read-only' | 'read-write') => invoke(CHANNEL_CONNECTED_PREPARE, { scope, requestedGrant }), confirm: (receipt: string) => invoke(CHANNEL_CONNECTED_CONFIRM, { receipt }), indexNext: (limit?: number) => invoke(CHANNEL_CONNECTED_INDEX_NEXT, limit === undefined ? undefined : { limit }), list: () => invoke(CHANNEL_CONNECTED_LIST), search: (query: string) => invoke(CHANNEL_CONNECTED_SEARCH, { query }), queueMetadata: (itemKey: string, clientReceipt: string, patch: ConnectedMetadataPatch) => invoke(CHANNEL_CONNECTED_QUEUE_METADATA, { itemKey, clientReceipt, patch }), prepareNew: (metadata?: ConnectedMetadataPatch) => invoke(CHANNEL_CONNECTED_PREPARE_NEW, metadata ? { metadata } : undefined), prepareFile: (itemKey: string) => invoke(CHANNEL_CONNECTED_PREPARE_FILE, { itemKey }), queueLifecycle: (itemKey: string, clientReceipt: string, action: 'trash' | 'restore') => invoke(CHANNEL_CONNECTED_QUEUE_LIFECYCLE, { itemKey, clientReceipt, action }), sync: (limit?: number) => invoke(CHANNEL_CONNECTED_SYNC, limit === undefined ? undefined : { limit }), operations: () => invoke(CHANNEL_CONNECTED_OPERATIONS), conflicts: () => invoke(CHANNEL_CONNECTED_CONFLICTS), resolveConflict: (conflictId: string, decision: 'use-local' | 'use-eagle' | 'hold') => invoke(CHANNEL_CONNECTED_RESOLVE_CONFLICT, { conflictId, decision }), cleanupCandidates: () => invoke(CHANNEL_CONNECTED_CLEANUP_CANDIDATES), confirmCleanup: (itemKey: string, clientReceipt: string) => invoke(CHANNEL_CONNECTED_CONFIRM_CLEANUP, { itemKey, clientReceipt }), readPreview: (itemKey: string, libraryIdentity: string, generation: string) => invoke(CHANNEL_CONNECTED_MEDIA_PREVIEW, { itemKey, libraryIdentity, generation }), disconnect: () => invoke(CHANNEL_CONNECTED_DISCONNECT) },
        legacyReadonly: { inspect: () => invoke(CHANNEL_LEGACY_INSPECT), prepare: () => invoke(CHANNEL_LEGACY_PREPARE), confirm: (receipt: string) => invoke(CHANNEL_LEGACY_CONFIRM, { receipt }), list: () => invoke(CHANNEL_LEGACY_LIST), search: (query: string) => invoke(CHANNEL_LEGACY_SEARCH, { query }), readPreview: (assetId: string, identity: string, generation: string) => invoke(CHANNEL_LEGACY_MEDIA_PREVIEW, { assetId, identity, generation }), close: () => invoke(CHANNEL_LEGACY_CLOSE) }
    });
}
