// Generated by the offline builder; runtime does not compile or download codecs.
export const VIDEO_RUNTIME_FILE = "bundle-a0lSwS/video.exe"
export const VIDEO_RUNTIME_SHA256 = "a5a680d03b7c69b1fc7e08a24eceaeaf39d4c4b8693064a3a6b38bd9d932e67e"
export const VIDEO_RUNTIME_SOURCE_DIGEST = "5c8725b170367a960e4629853b4bb2d51527e61e58b6b4853582e63ded327722"
