import {randomUUID} from 'node:crypto'
import type {ActiveLibraryHost} from '../../shared/contracts/active-library.contract'
import {validateWorkScope,validateWorkWrite,validateWorkValue,workRecord,workId,workRevision,type WorkScope,type WorkSetWrite,type WorkSetCatalog,type WorkWindowSnapshot,type WorkWindowAction,type WorkResult,type WorkWindowLayout} from '../../shared/contracts/work-set.contract'
import {validateNotebook,type NotebookSaveRequest} from '../../shared/contracts/asset-notebook.contract'
import {visibleWorkBounds,type WorkArea} from './work-window-bounds'
export interface WorkWindowPort{publish(value:WorkWindowSnapshot|null):void;show():void;hide():void;destroy():void;setPinned(value:boolean):void;bounds():WorkWindowLayout;setBounds(value:WorkWindowLayout):void;isTrusted(event:unknown):boolean}
interface Entry{notesDirty?:boolean;port:WorkWindowPort;state:WorkWindowSnapshot;sessionToken:string;queue:Promise<unknown>;timer?:ReturnType<typeof setTimeout>}
/** Windows are owned separately; private paths and broad application APIs never enter their preload. */
export function createWorkWindowController(deps:{host:ActiveLibraryHost;deviceId:string;areas:()=>WorkArea[];theme:()=> 'light'|'dark';createWindow:(input:{layout:WorkWindowLayout;changed:()=>void;closed:()=>void;readPreview:(url:string)=>Promise<Uint8Array>})=>WorkWindowPort;changed:()=>void;locate:(scope:WorkScope,setId:string,assetId?:string)=>void;hideMain:()=>void}){
 const entries=new Map<string,Entry>();let epoch=0;let retiredSession:string|null=null
 const result=async<T>(fn:()=>Promise<T>|T):Promise<WorkResult<T>>=>{try{return{success:true,value:await fn()}}catch(e){return{success:false,error:e instanceof Error&&'code'in e?e.message:e instanceof Error&&e.message==='TOO_MANY_WINDOWS'?'最多同时打开8个工作窗口，请先关闭其他工作窗口。':'操作未完成，请重试。',...(e&&typeof e==='object'&&'code'in e?{code:String(e.code)}:{})}}}
 const matches=(s:WorkScope)=>{const a=deps.host.inspect();return a.state==='ready'&&a.identity===s.libraryIdentity&&a.generation===s.generation}
 const assertCurrent=(entry:Entry)=>{if(entries.get(entry.state.set.id)!==entry||!matches(entry.state.scope))throw Error('STALE_WORK_WINDOW')}
 const invalidate=()=>{epoch++;for(const e of entries.values()){clearTimeout(e.timer);e.port.publish(null);e.port.destroy()}entries.clear()}
 const locateEntry=(event:unknown,token?:string)=>{for(const e of entries.values())if(e.port.isTrusted(event)&&(!token||token===e.state.token)){assertCurrent(e);return e}throw Error('UNTRUSTED_WORK_WINDOW')}
 const persist=(e:Entry)=>{const save=async()=>{assertCurrent(e);const layout={...e.port.bounds(),open:true};try{await deps.host.writeWorkLayout({...e.state.scope,sessionToken:e.sessionToken,id:e.state.set.id,layout},deps.deviceId);assertCurrent(e);e.state={...e.state,geometry:layout,pinned:layout.pinned,layoutError:undefined};e.port.publish(e.state)}catch(error){if(entries.get(e.state.set.id)===e){e.state={...e.state,layoutError:'窗口位置未保存，请重试。'};e.port.publish(e.state)}throw error}};const task=e.queue.then(save);e.queue=task.catch(()=>{});return task}
 const geometryChanged=(e:Entry)=>{clearTimeout(e.timer);e.timer=setTimeout(()=>{void persist(e).catch(()=>{})},250)}
 const refreshEntry=async(e:Entry)=>{const before=epoch;const catalog=await deps.host.readWorkSets(e.state.scope,deps.deviceId);if(before!==epoch)return;assertCurrent(e);const set=catalog.sets.find(s=>s.id===e.state.set.id);if(!set){clearTimeout(e.timer);entries.delete(e.state.set.id);e.port.destroy();return}const assets=(await deps.host.readAssetContext(set.assetIds)).assets;if(before!==epoch)return;assertCurrent(e);e.state={...e.state,set,assets:[...assets]};e.sessionToken=catalog.sessionToken;e.port.publish(e.state)}
 const refresh=async()=>{for(const e of [...entries.values()]){try{await refreshEntry(e)}catch{if(entries.get(e.state.set.id)===e){entries.delete(e.state.set.id);clearTimeout(e.timer);e.port.destroy()}}}}
 const read=(input:unknown)=>result(async()=>{const catalog=await deps.host.readWorkSets(validateWorkScope(input),deps.deviceId);if(catalog.sessionToken===retiredSession)throw Error('LIBRARY_TRANSITION');return catalog})
 const write=(input:unknown)=>result(async()=>{const r=validateWorkWrite(input);if(r.sessionToken===retiredSession)throw Error('LIBRARY_TRANSITION');const value=await deps.host.writeWorkSet(r,deps.deviceId);deps.changed();await refresh();return value})
 const open=async(input:unknown):Promise<WorkResult<WorkWindowSnapshot>>=>result(async()=>{const r=workRecord(input,['libraryIdentity','generation','id','theme']),scope=validateWorkScope({libraryIdentity:r.libraryIdentity,generation:r.generation}),id=workId(r.id);if(r.theme!==undefined&&!['light','dark'].includes(String(r.theme)))throw Error('INVALID_THEME');if(!matches(scope))throw Error('STALE_LIBRARY');const existing=entries.get(id);if(existing){assertCurrent(existing);if(r.theme==='light'||r.theme==='dark'){existing.state={...existing.state,theme:r.theme};existing.port.publish(existing.state)}existing.port.show();return existing.state}if(entries.size>=8)throw Error('TOO_MANY_WINDOWS');const before=epoch,catalog=await deps.host.readWorkSets(scope,deps.deviceId),set=catalog.sets.find(s=>s.id===id);if(catalog.sessionToken===retiredSession)throw Error('LIBRARY_TRANSITION');if(!set)throw Error('SET_MISSING');const assets=(await deps.host.readAssetContext(set.assetIds)).assets;if(before!==epoch||!matches(scope))throw Error('STALE_LIBRARY');if(entries.has(id)){const existing=entries.get(id)!;existing.port.show();return existing.state}
  const layout={...visibleWorkBounds(set.layout,deps.areas(),entries.size),open:true};await deps.host.writeWorkLayout({...scope,id,sessionToken:catalog.sessionToken,layout},deps.deviceId);if(before!==epoch||!matches(scope))throw Error('STALE_LIBRARY')
  if(entries.has(id)){const existing=entries.get(id)!;existing.port.show();return existing.state}if(entries.size>=8)throw Error('TOO_MANY_WINDOWS');
  const state:WorkWindowSnapshot={token:randomUUID(),scope,set,assets:[...assets],pinned:layout.pinned,geometry:layout,theme:r.theme==='dark'?'dark':r.theme==='light'?'light':deps.theme()};let entry:Entry
  const port=deps.createWindow({layout,readPreview:async(url)=>{assertCurrent(entry);const u=new URL(url);if(u.host!=='preview'||u.search||u.username||u.password||u.port)throw Error('INVALID_PREVIEW');const parts=u.pathname.split('/').filter(Boolean).map(decodeURIComponent);if(parts.length!==3||parts[0]!==scope.libraryIdentity||parts[1]!==scope.generation||!entry.state.set.assetIds.includes(parts[2])||entry.state.set.unavailableIds.includes(parts[2]))throw Error('MEMBERSHIP_NOT_GRANTED');const bytes=await deps.host.readPreview(parts[2]);assertCurrent(entry);if(!entry.state.set.assetIds.includes(parts[2])||entry.state.set.unavailableIds.includes(parts[2]))throw Error('MEMBERSHIP_NOT_GRANTED');return bytes},changed:()=>{if(entry&&entries.get(id)===entry)geometryChanged(entry)},closed:()=>{if(entry&&entries.get(id)===entry){clearTimeout(entry.timer);entries.delete(id)}}});entry={port,state,sessionToken:catalog.sessionToken,queue:Promise.resolve()};entries.set(id,entry);port.publish(state);port.show();deps.changed();return state
 })
 const restore=(input:unknown)=>result(async()=>{const r=workRecord(input,['libraryIdentity','generation','theme']);if(r.theme!==undefined&&!['light','dark'].includes(String(r.theme)))throw Error('INVALID_THEME');const scope=validateWorkScope({libraryIdentity:r.libraryIdentity,generation:r.generation}),catalog=await deps.host.readWorkSets(scope,deps.deviceId);let count=0;for(const set of catalog.sets.filter(s=>s.layout?.open)){const opened=await open({...scope,id:set.id,theme:r.theme});if(!opened.success)throw Error('WINDOW_RESTORE_FAILED');count++}return{count}})
 const recover=()=>result(async()=>{for(const e of entries.values()){e.port.setBounds(visibleWorkBounds(e.port.bounds(),deps.areas()));e.port.show();await persist(e)}return{count:entries.size}})
 const inspect=(event:unknown)=>result(()=>locateEntry(event).state)
 const act=(event:unknown,input:unknown)=>result(async()=>{const a=workRecord(input,['token','kind','expectedRevision','value','pinned','assetId','dirty','discard']),e=locateEntry(event,workId(a.token));const run=async()=>{assertCurrent(e)
  if(a.kind==='close'){workRecord(a,['token','kind','discard']);if(typeof a.discard!=='boolean')throw Error('INVALID_ACTION');if(!a.discard&&(e.notesDirty||e.state.draft))throw Error('UNSAVED_WORK_SET');clearTimeout(e.timer);await deps.host.writeWorkLayout({...e.state.scope,sessionToken:e.sessionToken,id:e.state.set.id,layout:{...e.port.bounds(),open:false}},deps.deviceId);assertCurrent(e);entries.delete(e.state.set.id);e.port.destroy();deps.changed()}
  else if(a.kind==='notes-dirty'){workRecord(a,['token','kind','dirty']);if(typeof a.dirty!=='boolean')throw Error('INVALID_ACTION');e.notesDirty=a.dirty}
  else if(a.kind==='draft'){workRecord(a,['token','kind','expectedRevision','value']);const value=validateWorkValue(a.value);if(value.assetIds.some(id=>!e.state.set.assetIds.includes(id)))throw Error('MEMBERSHIP_NOT_GRANTED');e.state={...e.state,draft:value,draftRevision:workRevision(a.expectedRevision)}}
  else if(a.kind==='discard-draft'){workRecord(a,['token','kind']);e.state={...e.state,draft:undefined,draftRevision:undefined};e.port.publish(e.state)}
  else if(a.kind==='save'){workRecord(a,['token','kind','expectedRevision','value']);const value=validateWorkValue(a.value);if(value.assetIds.some(id=>!e.state.set.assetIds.includes(id)))throw Error('MEMBERSHIP_NOT_GRANTED');const saved=await deps.host.writeWorkSet({...e.state.scope,sessionToken:e.sessionToken,allowUpgrade:false,command:{kind:'save',id:e.state.set.id,expectedRevision:workRevision(a.expectedRevision),value}},deps.deviceId,{...e.port.bounds(),open:true});assertCurrent(e);const set=saved.sets.find(s=>s.id===e.state.set.id)!;e.state={...e.state,set,...(JSON.stringify(e.state.draft)===JSON.stringify(value)?{draft:undefined,draftRevision:undefined}:{})};e.port.publish(e.state);deps.changed()}
  else if(a.kind==='pin'){workRecord(a,['token','kind','pinned']);if(typeof a.pinned!=='boolean')throw Error('INVALID_ACTION');e.port.setPinned(a.pinned);e.state={...e.state,pinned:a.pinned};e.port.publish(e.state)}
  else if(a.kind==='hide'){workRecord(a,['token','kind']);e.port.hide()}
  else if(a.kind==='recover'){workRecord(a,['token','kind']);e.port.setBounds(visibleWorkBounds(e.port.bounds(),deps.areas()))}
  else if(a.kind==='add-from-library'){workRecord(a,['token','kind']);deps.locate(e.state.scope,e.state.set.id)}
  else if(a.kind==='locate'){workRecord(a,['token','kind','assetId']);const id=workId(a.assetId);if(!e.state.set.assetIds.includes(id))throw Error('MEMBERSHIP_NOT_GRANTED');deps.locate(e.state.scope,e.state.set.id,id)}
  else throw Error('INVALID_ACTION')
  return e.state
 };const task=e.queue.then(run);e.queue=task.catch(()=>{});await task;if(['pin','hide','recover'].includes(String(a.kind)))await persist(e);return e.state})
 const notebookRead=(event:unknown,input:unknown)=>result(async()=>{const r=workRecord(input,['token','assetId']),e=locateEntry(event,workId(r.token)),assetId=workId(r.assetId);if(!e.state.set.assetIds.includes(assetId))throw Error('MEMBERSHIP_NOT_GRANTED');const value=await deps.host.readNotebook({...e.state.scope,assetId});assertCurrent(e);return value})
 const notebookSave=(event:unknown,input:unknown)=>result(async()=>{const r=workRecord(input,['token','request']),e=locateEntry(event,workId(r.token)),q=workRecord(r.request,['assetId','libraryIdentity','generation','sessionToken','sourceRef','expectedRevision','allowUpgrade','book']);const assetId=workId(q.assetId);if(!e.state.set.assetIds.includes(assetId)||q.libraryIdentity!==e.state.scope.libraryIdentity||q.generation!==e.state.scope.generation||q.allowUpgrade!==false||!Number.isSafeInteger(q.expectedRevision)||Number(q.expectedRevision)<0)throw Error('MEMBERSHIP_NOT_GRANTED');const request:NotebookSaveRequest={...e.state.scope,assetId,sessionToken:workId(q.sessionToken),sourceRef:workId(q.sourceRef),expectedRevision:Number(q.expectedRevision),allowUpgrade:false,book:validateNotebook(q.book)};const saved=await deps.host.saveNotebook(request);assertCurrent(e);return saved})
 const drain=async()=>{const a=deps.host.inspect();if(a.state==='ready'&&a.identity&&a.generation){try{retiredSession=(await deps.host.readWorkSets({libraryIdentity:a.identity,generation:a.generation},deps.deviceId)).sessionToken}catch{}}await Promise.allSettled([...entries.values()].map(e=>persist(e)));invalidate()}
 const hasUnsaved=()=>[...entries.values()].some(e=>e.notesDirty||e.state.draft&&JSON.stringify(e.state.draft)!==JSON.stringify(validateWorkValue({name:e.state.set.name,assetIds:e.state.set.assetIds,note:e.state.set.note,colors:e.state.set.colors,columns:e.state.set.columns})))
 return{hasUnsaved,read,write,open,restore,recover,inspect,act,notebookRead,notebookSave,invalidate,refresh,drain,hideMain:()=>result(()=>{if(!entries.size)throw Error('NO_WORK_WINDOWS');entries.values().next().value?.port.show();deps.hideMain();return{count:entries.size}}),count:()=>entries.size}
}
