import { requireWorkspaceClient } from '../../workspace-client'
import React,{useEffect,useRef,useState} from 'react'
import type {AiBackendConfig} from '../../../shared/types/ai-backend.types'
import {backendInferenceAdmission} from '../../../shared/constants/pi-provider-admission'
export default function AiServiceAcceptancePanel(){
 const api=requireWorkspaceClient(),epoch=useRef(0),reviewRef=useRef<string|null>(null),jobRef=useRef<string|null>(null),[backends,setBackends]=useState<AiBackendConfig[]>([]),[connection,setConnection]=useState(''),[model,setModel]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState<any>(null),[job,setJob]=useState<any>(null),[error,setError]=useState(''),[calls,setCalls]=useState(2),[cost,setCost]=useState(0),[quote,setQuote]=useState(0)
 useEffect(()=>{const version=++epoch.current;void api?.aiBackendList?.().then((list:AiBackendConfig[])=>{if(epoch.current===version)setBackends(list.filter(b=>b.enabled&&b.capabilities.vision&&backendInferenceAdmission(b).allowed))});return()=>{epoch.current++;if(reviewRef.current)void api?.aiAcceptance?.discard(reviewRef.current).catch(()=>{});if(jobRef.current)void api?.aiAcceptance?.cancel(jobRef.current).catch(()=>{})}},[api])
 useEffect(()=>{if(!job||job.state!=='running')return;let done=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const next=await api.aiAcceptance.status(job.id);if(!done)setJob(next)}catch{if(!done)setError('验收状态暂不可读；不要重发。')}if(!done)timer=setTimeout(poll,300)};timer=setTimeout(poll,100);return()=>{done=true;clearTimeout(timer)}},[api,job?.id,job?.state])
 const act=async(fn:(valid:()=>boolean)=>Promise<void>)=>{if(busy)return;const version=epoch.current;setBusy(true);setError('');try{await fn(()=>version===epoch.current)}catch{if(epoch.current===version)setError('操作未完成，请检查连接、模型及预算。账号或费用未知时不会自动执行。')}finally{if(epoch.current===version)setBusy(false)}}
 if(!api?.aiAcceptance)return null
 return <section className="visual-ai-panel" aria-label="生成图片服务验收"><header><strong>生成图片服务验收</strong></header><p>只使用本应用生成的一张图片和临时资料库；计划不联网。账号配置后，单独审阅目的地与有限预算再执行。额度消耗和费用可能与估计不同。</p>
 <label>验收连接<select aria-label="验收连接" disabled={busy||!!review||job?.state==='running'} value={connection} onChange={e=>{setConnection(e.target.value);setModel(backends.find(b=>b.id===e.target.value)?.defaultModel??'')}}><option value="">选择已配置连接</option>{backends.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
 <label>验收模型<input aria-label="验收模型" disabled={busy||!!review||job?.state==='running'} value={model} onChange={e=>setModel(e.target.value)}/></label>
 <div className="pi-connection-grid"><label>最多物理请求<input aria-label="验收最多请求" type="number" min={1} max={8} disabled={busy||!!review} value={calls} onChange={e=>setCalls(Number(e.target.value))}/></label><label>费用估计上限（USD）<input aria-label="验收费用上限" type="number" min={0} step="0.01" disabled={busy||!!review} value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label>单次请求保守费用估计（USD）<input aria-label="验收单次估价" type="number" min={0} step="0.01" disabled={busy||!!review} value={quote} onChange={e=>setQuote(Number(e.target.value))}/></label></div>
 <button disabled={busy||!connection||!model.trim()||!!review||job?.state==='running'} onClick={()=>void act(async valid=>{const r=await api.aiAcceptance.prepare({connectionRef:connection,model,maxPhysicalRequests:calls,maxOutputTokens:3072,maxWallClockMs:60000,maxEstimatedCostUsd:cost,estimatedCostPerRequestUsd:quote});if(valid()){reviewRef.current=r.receipt;setReview(r)}else void api.aiAcceptance.discard(r.receipt)})}>生成验收计划（不联网）</button>
 {review&&<div className="visual-ai-review" role="region" aria-label="确认生成图片服务验收"><p>{review.notice}</p><p>服务：{review.plan.origin}；模型：{review.plan.model}；最多 {review.plan.maxPhysicalRequests} 次请求；60 秒；费用估计上限 ${review.plan.maxEstimatedCostUsd}。所有重试扣预算，未知发送不自动退款或重发。</p><button disabled={busy} onClick={()=>void act(async valid=>{await api.aiAcceptance.discard(review.receipt);if(valid()){reviewRef.current=null;setReview(null)}})}>取消计划</button><button disabled={busy} onClick={()=>void act(async valid=>{const next=await api.aiAcceptance.confirm(review.receipt);if(valid()){reviewRef.current=null;setReview(null);jobRef.current=next.id;setJob(next)}else void api.aiAcceptance.cancel(next.id)})}>批准本次范围并执行</button></div>}
 {job&&<div role="status"><p>验收：{job.state}；已扣请求：{job.spent??'等待收敛'}</p>{job.output&&<p>{job.output.caption}</p>}{job.state==='running'&&<button onClick={()=>void api.aiAcceptance.cancel(job.id)}>取消验收</button>}{job.error&&<p>{job.error}{job.errorCode&&<>（诊断：{job.errorCode}）</>}</p>}</div>}{error&&<p role="alert">{error}</p>}
 </section>
}
