import { requireWorkspaceClient } from '../../workspace-client'
import type { OcrStatus } from '../../../shared/contracts/asset-ocr.contract'
import { workspaceMutationErrorMessage } from '../../../shared/client/workspace-connection-error'
import React,{useEffect,useRef,useState} from 'react'
export default function OcrEnvironmentSettings(){
 const [status,setStatus]=useState<OcrStatus|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const mounted=useRef(false),requestGeneration=useRef(0),selectionGeneration=useRef(0),errorOrigin=useRef<'read'|'selection'|null>(null)
 const isCurrent=(request:number)=>mounted.current&&request===requestGeneration.current
 const read=async()=>{const request=++requestGeneration.current;try{const r=await requireWorkspaceClient().assetOcr.status();if(!isCurrent(request))return;if(r.ok){setStatus(r.value);if(errorOrigin.current==='read'){errorOrigin.current=null;setError('')}}else if(errorOrigin.current!=='selection'){errorOrigin.current='read';setError(r.error)}}catch{if(isCurrent(request)&&errorOrigin.current!=='selection'){errorOrigin.current='read';setError('OCR 环境状态暂不可读。')}}}
 useEffect(()=>{mounted.current=true;void read();const timer=setInterval(()=>{void read()},3000);const stop=requireWorkspaceClient().assetOcr.onRuntimeChanged?.(()=>{void read()});return()=>{mounted.current=false;clearInterval(timer);requestGeneration.current++;selectionGeneration.current++;stop?.()}},[])
 const configure=()=>{const request=++requestGeneration.current,selection=++selectionGeneration.current,isSelectionCurrent=()=>mounted.current&&selection===selectionGeneration.current;setBusy(true);errorOrigin.current=null;setError('');void requireWorkspaceClient().assetOcr.configure().then(r=>{if(!isSelectionCurrent())return;if(r.ok){if(isCurrent(request))setStatus(r.value)}else{errorOrigin.current='selection';setError(r.error)}}).catch(error=>{if(isSelectionCurrent()){errorOrigin.current='selection';setError(workspaceMutationErrorMessage(error,'未能选择环境。'))}}).finally(()=>{if(isSelectionCurrent())setBusy(false)})}
 return <section className="ui-card" aria-label="本地 OCR 环境"><h2>OCR 环境</h2><p>选择已有可信本地环境并验证识字、空图和最大输入；识别时才运行，结束后确认进程退出并释放资源。</p><p>{status?(status.configured?'已验证':'尚未就绪'):'正在复核当前环境'}{status&&` · ${status.label}`}</p><button className="ui-button ui-button-secondary" disabled={busy} onClick={configure}>选择并验证本地 OCR 环境</button>{status?.configured&&<button className="ui-button ui-button-secondary" disabled={busy} onClick={()=>{setBusy(true);void requireWorkspaceClient().assetOcr.deactivate().then(r=>{if(r.ok)setStatus(r.value);else setError(r.error)}).finally(()=>setBusy(false))}}>停用 OCR 并释放</button>}{busy&&<button className="ui-button ui-button-secondary" onClick={()=>void requireWorkspaceClient().assetOcr.cancel()}>取消验证</button>}{error&&<p role="alert">{error}</p>}</section>
}
