import {appPath} from '../../../shared/workflows/app-navigation.workflow'
import {AUTH_STAGE_LABELS} from '../../../shared/contracts/ai-auth-state'
import {piProviderAdmission,backendInferenceAdmission} from '../../../shared/constants/pi-provider-admission'
import {PI_PROVIDER_ENDPOINTS,PI_PROVIDER_AUTH_MODES,supportsPiProductAuthentication} from '../../../shared/constants/pi-provider-presets'
import React,{useEffect,useRef,useState} from 'react'
import type {AiBackendConfig} from '../../../shared/types/ai-backend.types'
import type {AiCredentialStatus,AiLoginStatus} from '../../../shared/contracts/ai-connection.contract'
import './pi-connections.css'
const providerDefaults:Record<string,string>=PI_PROVIDER_ENDPOINTS
const editableFingerprint=(config:AiBackendConfig)=>{const{credentialRevision,credentialRef,modelValidation,...editable}=config;return JSON.stringify(editable)}
const newConnection=():AiBackendConfig=>({id:'pi-'+crypto.randomUUID(),name:'新模型连接',type:'openai-compatible',transport:'pi',providerKind:'openai-compatible',authMode:'none',baseUrl:providerDefaults['openai-compatible'],defaultModel:'',enabled:true,timeoutMs:120000,priority:10,processingLocation:'local-service',capabilities:{chat:true,vision:true,embeddings:false,jsonOutput:true,modelList:true,modelManagement:false}})
export default function PiConnectionsPanel({loginEligibility=piProviderAdmission,initialConnectionRef}:{loginEligibility?:typeof piProviderAdmission;initialConnectionRef?:string}={}){
 const api=(window as any).electronAPI,life=useRef(0),pending=useRef(false),loginRef=useRef<string|null>(null),validationRef=useRef<string|null>(null),[advanced,setAdvanced]=useState(false),[backends,setBackends]=useState<AiBackendConfig[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState<Record<string,AiCredentialStatus>>({}),[selected,setSelected]=useState<AiBackendConfig|null>(null),[key,setKey]=useState(''),[models,setModels]=useState<string[]>([]),[validation,setValidation]=useState<{receipt:string;notice:string}|null>(null),[validationResult,setValidationResult]=useState(''),[login,setLogin]=useState<AiLoginStatus|null>(null),[answer,setAnswer]=useState('')
 const load=async()=>{const version=life.current;try{const b=await api.aiBackendList();if(version!==life.current)return;setBackends(b);window.dispatchEvent(new Event('dam:ai-connections-updated'));const statuses=await Promise.allSettled(b.map(async(c:AiBackendConfig)=>[c.id,await api.aiConnections.credentialStatus(c.id)]));if(version===life.current)setStatus(Object.fromEntries(statuses.filter(r=>r.status==='fulfilled').map((r:any)=>r.value)))}catch{if(version===life.current)setError('连接配置暂不可用。')}}
 useEffect(()=>{life.current++;void load();return()=>{life.current++;if(validationRef.current)void api.aiConnections.discardValidation(validationRef.current).catch(()=>{})}},[api])
 useEffect(()=>{setAnswer('')},[login?.id,login?.prompt?.id])
 useEffect(()=>{if(!login||!['starting','interaction','cancelling','unknown'].includes(login.state))return;let done=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const s=await api.aiConnections.loginStatus(login.id);if(!done){setLogin(s);if(s.state==='completed'){const version=life.current;void load();void api.aiBackendList().then((list:AiBackendConfig[])=>{if(version===life.current)setSelected(previous=>previous?.id===s.backendId?list.find(b=>b.id===s.backendId)??previous:previous)})}}}catch{if(!done)setError('登录状态读取失败。')}if(!done)timer=setTimeout(poll,500)};timer=setTimeout(poll,250);return()=>{done=true;clearTimeout(timer)}},[login?.id,login?.state,api])
 const act=async(fn:(valid:()=>boolean)=>Promise<void>)=>{if(pending.current)return;pending.current=true;const version=life.current;setBusy(true);setError('');try{await fn(()=>version===life.current)}catch{if(version===life.current)setError('操作未完成，请刷新核对配置与凭据状态。')}finally{if(version===life.current){pending.current=false;setBusy(false)}}}
 const edit=(b:AiBackendConfig)=>{if(validationRef.current)void api.aiConnections.discardValidation(validationRef.current).catch(()=>{});validationRef.current=null;setValidation(null);setValidationResult('');loginRef.current=null;life.current++;const version=life.current;pending.current=false;setBusy(false);setSelected(structuredClone(b));setModels([]);setKey('');setError('');setLogin(null);setAnswer('');void api.aiConnections.currentLogin?.(b.id).then((operation:AiLoginStatus|null)=>{if(life.current===version){setLogin(operation);loginRef.current=operation?.id??null}}).catch(()=>{})}
 useEffect(()=>{if(initialConnectionRef){const current=backends.find(b=>b.id===initialConnectionRef);if(current&&selected?.id!==current.id)edit(current)}},[initialConnectionRef,backends])
 const saved=selected?backends.find(b=>b.id===selected.id):undefined,dirty=Boolean(selected&&saved&&editableFingerprint(selected)!==editableFingerprint(saved))
 const guided=(kind:'local'|'api'|'chatgpt')=>{const b=newConnection();edit(kind==='local'?{...b,name:'本机模型服务'}:{...b,name:kind==='chatgpt'?'ChatGPT 账号':'模型 API',providerKind:'openai',baseUrl:providerDefaults.openai,authMode:kind==='chatgpt'?'oauth':'api-key',processingLocation:'external-service'});setAdvanced(false)}
 const inference=selected?backendInferenceAdmission(selected):null,loginAdmission=selected?loginEligibility(selected.providerKind??'openai-compatible',selected.authMode??'none','login'):null
 if(!api?.aiConnections)return null
 return <section className="visual-ai-panel pi-connections" aria-label="连接与账号"><header><strong>模型连接与任务配置</strong><button disabled={busy} onClick={()=>void load()}>刷新连接</button></header><p>本地兼容服务与云端模型共用分析入口。配置、目录探测和账号登录不授权发送素材。</p>
 <div className="visual-ai-actions"><button disabled={busy} onClick={()=>guided('local')}>连接本机服务</button><button disabled={busy} onClick={()=>guided('api')}>使用模型 API</button><button disabled={busy} onClick={()=>guided('chatgpt')}>使用 ChatGPT 账号</button>{backends.map(b=><button key={b.id} disabled={busy} onClick={()=>edit(b)}>{b.name} · {status[b.id]?.configured?'已保存凭据':status[b.id]?.legacyPresent?'待迁移凭据':'未保存凭据'}</button>)}</div>
 {selected&&!inference?.allowed&&<p role="status">{inference?.message}</p>}
 {selected&&<div className="pi-connection-form" role="region" aria-label="编辑模型连接"><div className="pi-connection-grid">
 <label>连接名称<input aria-label="连接名称" value={selected.name} disabled={busy} onChange={e=>setSelected({...selected,name:e.target.value})}/></label>
 {(advanced||selected.authMode!=='oauth'&&selected.providerKind!=='openai-compatible')&&<label>提供方<select aria-label="提供方" value={selected.providerKind??'openai-compatible'} disabled={busy} onChange={e=>setSelected({...selected,transport:'pi',providerKind:e.target.value as any,baseUrl:providerDefaults[e.target.value],authMode:PI_PROVIDER_AUTH_MODES[e.target.value as keyof typeof PI_PROVIDER_AUTH_MODES][0],processingLocation:e.target.value==='openai-compatible'?'local-service':'external-service'})}>{Object.keys(providerDefaults).filter(p=>advanced||['openai','anthropic'].includes(p)).map(p=><option key={p} value={p}>{p==='openai-compatible'?'兼容接口':p==='openai-codex'?'Codex（暂不可用）':p==='github-copilot'?'Copilot（暂不可用）':p==='google'?'Google（暂不可用）':p}</option>)}</select></label>}
 {(advanced||selected.providerKind==='openai-compatible')&&<label>服务地址<input aria-label="服务地址" disabled={busy} value={selected.baseUrl} onChange={e=>setSelected({...selected,baseUrl:e.target.value})}/></label>}
 <label>模型名称<input aria-label="模型名称" disabled={busy} value={selected.defaultModel??''} list="pi-model-list" onChange={e=>setSelected({...selected,defaultModel:e.target.value})}/><datalist id="pi-model-list">{models.map(m=><option key={m} value={m}/>)}</datalist></label>
 <label>认证方式<select aria-label="认证方式" disabled={busy} value={selected.authMode??'none'} onChange={e=>setSelected({...selected,authMode:e.target.value as any})}><option value="none" disabled={!supportsPiProductAuthentication(selected.providerKind??'openai-compatible','none')}>无需认证</option><option value="api-key" disabled={!supportsPiProductAuthentication(selected.providerKind??'openai-compatible','api-key')}>API Key</option><option value="oauth" disabled={!supportsPiProductAuthentication(selected.providerKind??'openai-compatible','oauth')}>订阅账号登录</option></select></label>
<label>处理位置<select aria-label="Pi 处理位置" disabled={busy} value={selected.processingLocation??'external-service'} onChange={e=>setSelected({...selected,processingLocation:e.target.value as any})}><option value="local-service">本机服务</option><option value="external-service">外部服务或转发代理</option></select></label>
 {advanced&&<label>执行接口<select disabled={busy} value={selected.transport??'legacy'} onChange={e=>setSelected({...selected,transport:e.target.value as any})}><option value="pi">Pi 统一接口</option><option value="legacy">已有兼容接口</option></select></label>}
 </div><button onClick={()=>setAdvanced(v=>!v)} aria-expanded={advanced}>{advanced?'收起技术选项':'高级连接选项'}</button><label><input type="checkbox" disabled={busy} checked={selected.enabled} onChange={e=>setSelected({...selected,enabled:e.target.checked})}/> 启用此连接</label><p>图片能力目前为配置声明；目录存在和连接成功不能替代实际图片推理验证。手动模型 ID 始终可填写。</p>
 <div className="visual-ai-actions"><button disabled={busy} onClick={()=>void act(async valid=>{const list=await api.aiBackendSave(selected);if(!valid())return;setBackends(list);setSelected(list.find((b:AiBackendConfig)=>b.id===selected.id));await load()})}>保存连接</button><button disabled={busy||!backends.some(b=>b.id===selected.id)||dirty} onClick={()=>void act(async valid=>{const r=await api.aiBackendListModels({backendId:selected.id});if(!valid())return;if(r.success)setModels(r.models.map((m:any)=>m.id));else setError('目录暂不可用，请手动填写模型 ID；推理能力尚未验证。')})}>读取模型目录</button><button disabled={busy} onClick={()=>void act(async valid=>{await api.aiBackendDelete({id:selected.id});if(valid()){setSelected(null);await load()}})}>删除连接</button></div>
 <div className="visual-ai-actions"><button disabled={busy||!inference?.allowed||selected.transport!=='pi'||!backends.some(b=>b.id===selected.id)||dirty} onClick={()=>void act(async valid=>{const review=await api.aiConnections.prepareValidation(selected.id);if(!valid()){void api.aiConnections.discardValidation(review.receipt);return}validationRef.current=review.receipt;setValidation(review)})}>核对生成图片能力验证</button></div>
 {validation&&<div className="visual-ai-review" role="region" aria-label="确认模型能力验证"><p>{validation.notice}</p><button disabled={busy} onClick={()=>{void api.aiConnections.discardValidation(validation.receipt);validationRef.current=null;setValidation(null)}}>取消能力验证</button><button disabled={busy} onClick={()=>void act(async valid=>{const proof=await api.aiConnections.confirmValidation(validation.receipt);if(valid()){validationRef.current=null;setValidation(null);setValidationResult(proof.colourChallengePassed?'生成图片与完整 JSON 验证通过':'请求与 JSON 完整，颜色识别未通过；图像理解能力仍待核验');await load()}})}>同意发送生成测试图</button></div>}
 {validationResult&&<p role="status">{validationResult}</p>}
 {dirty&&<p role="status">连接有未保存修改，请先保存或取消后再登录、探测或分配任务。</p>}{saved&&<button disabled={busy||!dirty} onClick={()=>edit(saved)}>取消修改</button>}
 {selected.modelValidation&&<p>上次模型验证：{selected.modelValidation.model} · {selected.modelValidation.vision?'图像挑战通过':'图像挑战未通过'} · {selected.modelValidation.testedAt}</p>}
 {selected.authMode==='api-key'&&<><label>新的 API Key<input aria-label="API Key" type="password" autoComplete="new-password" value={key} disabled={busy} onChange={e=>setKey(e.target.value)}/></label><button disabled={busy||!key.trim()||!backends.some(b=>b.id===selected.id)||dirty} onClick={()=>void act(async valid=>{const value=key;setKey('');const s=await api.aiConnections.setApiKey({backendId:selected.id,key:value});if(valid()){setStatus(p=>({...p,[selected.id]:s}));await load()}})}>安全保存 API Key</button></>}
 {status[selected.id]?.storageAvailable===false&&<p role="alert">系统安全存储不可用，不能保存账号或密钥。</p>}
 {status[selected.id]?.legacyPresent&&<p>此连接有旧格式凭据。<button disabled={busy} onClick={()=>void act(async valid=>{const s=await api.aiConnections.migrateCredential({backendId:selected.id,expectedRevision:status[selected.id].revision});if(valid()){setStatus(p=>({...p,[selected.id]:s}));await load()}})}>确认迁移此连接凭据</button></p>}
 {status[selected.id]?.identityVerified&&<p>{status[selected.id]?.planUsageAuthorized?'身份与计划权限已验证':'身份已验证，计划推理尚未授权'}{status[selected.id]?.requiresRelogin?' · 需要重新登录':''}</p>}
 {selected.authMode==='oauth'&&<p>无需 API Key；请在运行 DAM 的同一台机器完成浏览器授权。 {loginAdmission?.message} 登录失败不会自动改走 API 计费。</p>}
 {selected.authMode==='oauth'&&<div className="visual-ai-actions"><button disabled={busy||!loginAdmission?.allowed||!backends.some(b=>b.id===selected.id)||dirty} onClick={()=>void act(async valid=>{const s=await api.aiConnections.login(selected.id);if(valid()){loginRef.current=s.id;setLogin(s)}})}>{selected.providerKind==='openai'?'Continue with ChatGPT':'开始订阅登录'}</button><button disabled={!login||busy} onClick={()=>void api.aiConnections.cancelLogin(login!.id)}>取消订阅登录</button></div>}
 {login&&<div role="status"><p>{login.state==='completed'?(login.planUsageAuthorized===false?'账号身份已验证，但未授予 ChatGPT 计划推理权限。':'账号已连接；素材执行仍需重新确认'):['failed','cancelled','denied','expired','unknown'].includes(login.state)?login.error??'登录已取消':login.stage?AUTH_STAGE_LABELS[login.stage]:'等待账号授权'}</p><button onClick={()=>void api.aiConnections.authDiagnostic(login.id).then((summary:unknown)=>navigator.clipboard.writeText(JSON.stringify(summary,null,2))).catch(()=>setError('诊断摘要未能复制，请重试。'))}>复制脱敏登录诊断</button>{login.errorCode&&<small>失败阶段：{login.stage?AUTH_STAGE_LABELS[login.stage]:'尚未开始'} · {login.errorCode}</small>}{login.event?.userCode&&<p>设备码：{login.event.userCode}</p>}{login.event?.url&&<button onClick={()=>void act(async()=>{await api.aiConnections.openAuthUrl({id:login.id,url:login.event!.url})})}>在系统浏览器完成登录</button>}{login.prompt&&<><label>{login.prompt.message}{login.prompt.type==='select'?<select aria-label="订阅登录方式" value={answer} onChange={e=>setAnswer(e.target.value)}><option value="">请选择登录方式</option>{login.prompt.options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select>:<input type={login.prompt.type==='text'?'text':'password'} autoComplete="off" value={answer} onChange={e=>setAnswer(e.target.value)}/>}</label><button disabled={!answer} onClick={()=>void act(async()=>{const value=answer;setAnswer('');await api.aiConnections.answerLogin({id:login.id,promptId:login.prompt!.id,answer:value})})}>提交授权信息</button></>}</div>}
 <button disabled={busy||!status[selected.id]?.configured} onClick={()=>void act(async valid=>{const s=await api.aiConnections.clearCredential(selected.id);if(valid()){setStatus(p=>({...p,[selected.id]:s}));await load()}})}>退出账号并移除凭据</button>
 <a className="ui-button ui-button-secondary" href={'#'+appPath('ai-task-models')}>设置任务默认模型</a>

 </div>}{error&&<p role="alert">{error}</p>}
 </section>
}
