import React,{useEffect,useState} from 'react'
import type {AiBackendConfig} from '../../../shared/types/ai-backend.types'
import {backendInferenceAdmission} from '../../../shared/constants/pi-provider-admission'
const tasks=[['analyze','视觉分析与标签'],['reverse','提示词反推'],['tags','独立标签']] as const
export default function TaskModelSettings(){
 const [backends,setBackends]=useState<AiBackendConfig[]>([]),[choices,setChoices]=useState<Record<string,{backendId:string;model:string}>>({}),[templates,setTemplates]=useState<Array<{id:string;name:string;content:string}>>([]),[feedback,setFeedback]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{let alive=true;void Promise.all([(window as any).electronAPI.aiBackendList(),(window as any).electronAPI.settingsLoad()]).then(([list,settings])=>{if(alive){setBackends(list);setChoices(settings.aiTaskModels??{});setTemplates(settings.promptReverseTemplates??[])}}).catch(()=>{if(alive)setFeedback('配置暂不可读，请重新进入后重试。')});return()=>{alive=false}},[])
 const save=async()=>{setBusy(true);setFeedback('');try{const api=(window as any).electronAPI;const current=await api.settingsLoad();await api.settingsSave({aiTaskModels:{...current.aiTaskModels,...choices}});setFeedback('任务默认模型已保存；不会自动发送素材。')}catch{setFeedback('未能保存，请核对已保存的连接与模型。')}finally{setBusy(false)}}
 return <section className="ui-card" aria-label="任务默认模型"><h2>任务用哪个模型</h2><p>这里只设置默认选择，素材执行仍需独立确认。OCR 使用本地 OCR 环境，不走这些模型连接。</p>{tasks.map(([id,label])=><div key={id} className="pi-connection-grid"><label>{label}<select aria-label={label+'连接'} value={choices[id]?.backendId??''} onChange={event=>{const b=backends.find(v=>v.id===event.target.value);if(b)setChoices(v=>({...v,[id]:{backendId:b.id,model:b.defaultModel??''}}))}}><option value="">未分配</option>{backends.filter(b=>b.enabled&&backendInferenceAdmission(b).allowed).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>模型名称<input aria-label={label+'模型'} value={choices[id]?.model??''} onChange={event=>setChoices(v=>({...v,[id]:{backendId:v[id]?.backendId??'',model:event.target.value}}))}/></label></div>)}<button className="ui-button ui-button-primary" disabled={busy||Object.values(choices).some(v=>!v.backendId||!v.model.trim())} onClick={()=>void save()}>保存任务默认模型</button>{feedback&&<p role="status">{feedback}</p>}<details><summary>保留的旧提示模板</summary><p>这些旧记录完整保留，不代表当前统一分析配方使用它们。</p>{templates.length?templates.map(t=><details key={t.id}><summary>{t.name}</summary><pre>{t.content}</pre></details>):<p>没有旧模板。</p>}</details></section>
}
