/** Generated by seal-pi-runtime; app-bundled release identity, not user-editable runtime metadata. */
export const PI_RUNTIME_RELEASE_SHA256="edc947653913e104245e60e3d7f35095887b2788163296c4933f0ded23f4e9bd"
