/** Reads may reconcile an interrupted connection. Unknown commands stay blocked. */
const reads = new Set([
  'app:build-identity', 'app:capabilities',
  'workspace:transition-pending', 'drafts:list', 'files:pending',
  'library:inspect', 'library:add:inspect', 'library:media:read-preview',
  'library-trash:inspect', 'library-trash:list',
  'library-organization:read', 'library-organization:preview-colors', 'library-notebook:read',
  'work-sets:read', 'work-windows:list', 'work-media:status','work-media:read','work-files:list', 'library-recovery:list',
  'connected-library:inspect', 'connected-library:list', 'connected-library:search',
  'connected-library:pairing-inspect',
  'connected-library:companion-artifact',
  'connected-library:operations', 'connected-library:conflicts',
  'connected-library:cleanup-candidates', 'connected-library:media-preview',
  'legacy-readonly:inspect', 'legacy-readonly:list', 'legacy-readonly:search', 'legacy-readonly:media-preview',
  'download:list', 'download:jobs', 'settings:load', 'ai-backend:list',
  'ai-connection:active-logins', 'ai-connection:credential-status',
  'ai-connection:login-status', 'ai-connection:current-login', 'ai-connection:auth-diagnostic',
  'ai-acceptance:status', 'background-ocr:read', 'asset-ocr:status', 'asset-ocr:read',
  'background-analysis:read', 'basic-analysis:inspect', 'basic-analysis:captions', 'basic-analysis:attempts', 'independent-tags:read', 'tag-recovery:list', 'managed-vision:status', 'managed-models:read', 'ai-resources:read', 'ai-resources:diagnostics',
  'tag-batch:inspect', 'tag-execution:inspect', 'tag-execution:read',
  'visual-ai:backends', 'visual-ai:inspect', 'visual-ai:results',
  'assets:list', 'assets:get-custom-category',
  'asset-search:query', 'asset-search:status', 'asset-search:read-assets',
  'retrieval-models:read',
  'asset-retrieval:coverage','asset-retrieval:query',
  'tag:get', 'tag:list', 'tag:search', 'asset-tag:list-by-asset',
  'tag-search:assets', 'tag-search:untagged', 'tag-search:ai-pending',
  'model-library-workspace:summarize',
  'llama-runtime:get-status', 'llama-runtime:list-local-models',
  'ocr:get-install-log', 'ai-worker:get-gpu-status',
  'doctor:getLastReport', 'doctor:listChecks',
  'aiRuntime:listRuntimes', 'aiRuntime:getRuntimeState', 'aiRuntime:getActiveRuntime',
  'aiRuntime:getMacOSCapabilities', 'aiRuntime:getWindowsCapabilities',
  'ai-runtime:get-macos-ai-branch-status', 'ai-runtime:get-windows-ai-branch-status',
  'aiRuntime:getPythonMpsStatus', 'aiRuntime:getPythonCudaStatus', 'aiRuntime:getClipSiglipOnnxStatus',
  'runtime-package:get-execution-status', 'settingsMigration:listBackups',
  'ai-model:list', 'cooperative-model:list',
  'assets:path-governance-report', 'assets:path-migration-report'
])
export const isWorkspaceReadCommand = (command: string) => reads.has(command)
