import {test} from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import http from 'node:http'
import {pathToFileURL} from 'node:url'
import {createHash} from 'node:crypto'
import {_electron as electron} from 'playwright'
import sharp from 'sharp'
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),until=async(check)=>{for(let i=0;i<600;i++){if(await check())return;await sleep(25)}throw Error('formal condition timed out')}
await test('formal Main/preload/Renderer acceptance review makes no request and executes only signed generated temporary Host scope',async()=>{
 const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'dam-pi-e2e-'))),profile=path.join(root,'profile'),library=path.join(root,'library'),evidence=path.join(root,'evidence'),entry=path.join(root,'entry');let app,calls=0,catalog=0
 const server=http.createServer(async(req,res)=>{if(req.method==='GET'){catalog++;res.setHeader('Content-Type','application/json');res.end('{"data":[{"id":"fixture"}]}');return}const chunks=[];for await(const c of req)chunks.push(c);const body=JSON.parse(Buffer.concat(chunks).toString());calls++;assert.equal(body.model,'fixture');assert.equal(req.headers.authorization,'Bearer fixture-api-key-not-real');const validation=body.messages[1].content[0].text.includes('双色验证');let colours=[];if(validation){const pixels=await sharp(Buffer.from(body.messages[1].content[1].image_url.url.split(',')[1],'base64')).raw().toBuffer();for(const x of [0,48]){const rgb=[...pixels.subarray(x*3,x*3+3)];colours.push(['红色','绿色','蓝色'][rgb.indexOf(Math.max(...rgb))])}}const tags=body.messages[0].content.includes('标签助手');const out=validation?{caption:'双色验证',ocrText:'',prompt:'Two colour blocks',tags:colours}:tags?{tags:['Pi标签']}:{caption:'Pi隔离分析',ocrText:'',prompt:'A synthetic geometric design',tags:['Pi标签']};res.writeHead(200,{'Content-Type':'text/event-stream'});res.write('data: '+JSON.stringify({id:'s',choices:[{index:0,delta:{role:'assistant',content:JSON.stringify(out)},finish_reason:null}]})+'\n\n');res.end('data: '+JSON.stringify({id:'s',choices:[{index:0,delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n')});await new Promise(r=>server.listen(0,'127.0.0.1',r))
 try{
  for(const d of [profile,evidence,entry])await fs.mkdir(d);const source=path.join(root,'generated.png');await sharp({create:{width:100,height:80,channels:3,background:'#7799bb'}}).png().toFile(source);const original=createHash('sha256').update(await fs.readFile(source)).digest('hex')
  await fs.writeFile(path.join(entry,'package.json'),JSON.stringify({name:'dam-pi-test',type:'module',main:'main.mjs'}));await fs.writeFile(path.join(entry,'main.mjs'),`import ${JSON.stringify(pathToFileURL(path.resolve('out/main/index.js')).href)};`)
  const config={rootDirectory:root,profileDirectory:profile,libraryDirectory:library,evidenceDirectory:evidence,sourceSelections:[[source]]},env=Object.fromEntries(Object.entries(process.env).filter(([k])=>!k.startsWith('DAM_')&&!['NODE_OPTIONS','ELECTRON_RUN_AS_NODE','ELECTRON_RENDERER_URL'].includes(k)))
  app=await electron.launch({args:[entry,'--dam-active-library-synthetic-e2e',`--user-data-dir=${profile}`],env:{...env,NODE_ENV:'test',DAM_ACTIVE_LIBRARY_SYNTHETIC_E2E:JSON.stringify(config)}});assert.ok((await app.evaluate(({app})=>['userData','sessionData','logs','crashDumps'].map(p=>app.getPath(p)))).every(p=>p.startsWith(root+path.sep)))
  const page=await app.firstWindow();page.setDefaultTimeout(18000);await page.setViewportSize({width:1450,height:1080});await page.getByTestId('formal-library-canvas').waitFor();await page.getByTestId('library-create').click();await page.getByTestId('library-create-confirm').click();await page.getByRole('button',{name:'添加图片',exact:true}).click();await page.getByTestId('library-copy-confirm').click();await page.locator('.lc-card').first().waitFor()
  const selected=await page.evaluate(async()=>{const s=await window.damClient.library.inspect(),a=(await window.damClient.listAssets())[0];return{libraryIdentity:s.identity,generation:s.generation,assetId:a.id}});await page.evaluate(()=>location.hash='/ai-console');const panel=page.getByRole('region',{name:'连接与账号',exact:true});await panel.getByRole('button',{name:'连接本机服务'}).click();await panel.getByLabel('连接名称').fill('Pi自有测试服务');await panel.getByLabel('服务地址').fill(`http://127.0.0.1:${server.address().port}/v1`);await panel.getByLabel('模型名称').fill('fixture');await panel.getByLabel('认证方式').selectOption('api-key');await panel.getByRole('button',{name:'保存连接'}).click();await panel.getByRole('button',{name:'读取模型目录'}).waitFor({state:'visible'});await panel.getByLabel('API Key').fill('fixture-api-key-not-real');await panel.getByRole('button',{name:'安全保存 API Key'}).click();await until(async()=>await panel.getByRole('button',{name:/Pi自有测试服务.*已保存凭据/}).count()===1)
  assert.equal(calls,0);assert.equal(await panel.getByLabel('API Key').inputValue(),'');const settings=await page.evaluate(()=>window.damClient.settingsLoad());assert.ok(!JSON.stringify(settings).includes('fixture-api-key-not-real'));assert.ok(!(await fs.readFile(path.join(profile,'ai-credentials.v1.json'),'utf8')).includes('fixture-api-key-not-real'))
  await page.evaluate(()=>location.hash='/library');await page.evaluate(()=>location.hash='/ai-console');await page.getByRole('link',{name:'高级诊断',exact:true}).click();await page.getByText('工程服务验收（生成图片）',{exact:true}).click();const acceptance=page.getByRole('region',{name:'生成图片服务验收',exact:true});await acceptance.waitFor();const backend=(await page.evaluate(()=>window.damClient.aiBackendList())).find(b=>b.name==='Pi自有测试服务');await acceptance.getByLabel('验收连接').selectOption(backend.id);await acceptance.getByLabel('验收模型').fill('fixture');assert.equal(calls,0);await acceptance.getByRole('button',{name:'生成验收计划（不联网）'}).click();await acceptance.getByRole('region',{name:'确认生成图片服务验收'}).waitFor();assert.equal(calls,0);assert.equal(catalog,0);assert.equal((await page.evaluate(()=>window.damClient.listAssets())).length,1)
  await acceptance.getByRole('button',{name:'批准本次范围并执行'}).click();await until(async()=>/验收：(succeeded|failed|unknown|cancelled)/.test(await acceptance.innerText()));assert.match(await acceptance.innerText(),/验收：succeeded/,JSON.stringify({calls,catalog,status:await acceptance.innerText()}));assert.equal(calls,1);await acceptance.getByText('Pi隔离分析',{exact:true}).waitFor();assert.equal((await page.evaluate(()=>window.damClient.listAssets())).length,1);assert.equal((await page.evaluate(s=>window.damClient.visualAi.results(s),selected)).value.length,0);assert.equal(createHash('sha256').update(await fs.readFile(source)).digest('hex'),original)
  if(process.env.PI_EVIDENCE_DIR){await fs.mkdir(process.env.PI_EVIDENCE_DIR,{recursive:true});await acceptance.screenshot({path:path.join(process.env.PI_EVIDENCE_DIR,'acceptance-formal.png')})}
  await app.close();app=null;assert.equal(await fs.readFile(path.join(evidence,'shutdown-complete'),'utf8'),'complete\n')
 }finally{if(app)await app.close();server.closeAllConnections();await new Promise(r=>server.close(r));await fs.rm(root,{recursive:true,force:true})}
})
