import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

const source = await fs.readFile('src/renderer/routes/AiConsolePage.tsx', 'utf8')
const matrixSource = await fs.readFile('src/renderer/components/settings/MacOSAiCapabilityMatrix.tsx', 'utf8')

assert.match(source, /MacOSAiCapabilityMatrix/)
assert.match(source, /getMacOSCapabilities/)
assert.match(source, /getPythonMpsStatus/)
assert.match(source, /getClipSiglipOnnxStatus/)
assert.match(source, /macOS 路线概览/)
assert.match(source, /Qwen3-VL GGUF/)
assert.match(source, /Qwen3-VL MLX/)
assert.match(source, /Qwen2\.5-VL Ollama fallback/)
assert.match(source, /external HTTP fallback/)
assert.match(source, /summarizeOllamaFallback/)
assert.match(source, /summarizeExternalHttpFallback/)
assert.match(source, /Ollama fallback/)
assert.match(source, /Custom HTTP/)
assert.match(source, /CLIP\/SigLIP ONNX/)
assert.match(source, /PaddleOCR ONNX/)
assert.match(source, /MacOSAiWorkerProbeResult/)
assert.match(source, /llamaRuntimeGetStatus/)
assert.match(source, /llamaRuntimeListLocalModels/)
assert.match(source, /aiModelList/)
assert.match(source, /aiModelStatus/)
assert.match(matrixSource, /macOS 细项能力矩阵/)
assert.match(matrixSource, /probe\.lanes\.map/)
assert.match(matrixSource, /capability\.modelFamily \?\? capability\.backend \?\? capability\.role/)
assert.match(matrixSource, /capability\.label/)

const overviewSliceStart = source.indexOf('function OverviewWorkspace')
const overviewSliceEnd = source.indexOf('function RuntimeTile', overviewSliceStart)
const overviewSlice = source.slice(overviewSliceStart, overviewSliceEnd)

assert.match(overviewSlice, /macOSWorkerProbe/)
assert.match(overviewSlice, /macOS 路线概览/)
assert.match(overviewSlice, /MPS/)
assert.match(overviewSlice, /Python MPS 兼容性/)
assert.match(overviewSlice, /ONNX Runtime/)
assert.match(overviewSlice, /CLIP\/SigLIP ONNX/)
assert.match(overviewSlice, /CLIP\/SigLIP 兼容性/)
assert.match(overviewSlice, /MLX/)
assert.match(overviewSlice, /Llama 路线/)
assert.match(overviewSlice, /Qwen2\.5-VL Ollama fallback/)
assert.match(overviewSlice, /external HTTP fallback/)
assert.match(overviewSlice, /Smoke GGUF/)
assert.match(overviewSlice, /Vision mmproj/)
assert.match(overviewSlice, /下载中/)
