import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

const source = await fs.readFile('src/renderer/routes/AiConsolePage.tsx', 'utf8')
const statusModuleSource = await fs.readFile('src/renderer/modules/ai-console-status/ai-console-status.module.ts', 'utf8')
const statusAdapterSource = await fs.readFile('src/renderer/modules/ai-console-status/electron-ai-console-status.adapter.ts', 'utf8')
const matrixSource = await fs.readFile('src/renderer/components/settings/PlatformAiCapabilityMatrix.tsx', 'utf8')
const branchWorkflowSource = await fs.readFile('src/shared/workflows/platform-ai-branch-status.workflow.ts', 'utf8')
const platformAdapterSource = await fs.readFile('src/renderer/platform-ai-runtime.adapter.ts', 'utf8')

assert.doesNotMatch(source, /MacOSAiCapabilityMatrix/)
assert.match(statusModuleSource, /selectCurrentPlatformAiRuntimeRequests/)
assert.doesNotMatch(statusAdapterSource, /probePythonMpsRuntime|probePythonCudaRuntime/)
assert.match(platformAdapterSource, /getMacOSCapabilities/)
assert.match(platformAdapterSource, /getWindowsCapabilities/)
assert.match(platformAdapterSource, /getMacOSAiBranchStatus/)
assert.match(platformAdapterSource, /getWindowsAiBranchStatus/)
assert.doesNotMatch(source, /getMacOSCapabilities|getWindowsCapabilities/)
assert.doesNotMatch(source, /getMacOSAiBranchStatus|getWindowsAiBranchStatus/)
assert.match(platformAdapterSource, /getPythonMpsStatus/)
assert.match(platformAdapterSource, /getPythonCudaStatus/)
assert.match(statusAdapterSource, /getClipSiglipOnnxStatus/)
assert.doesNotMatch(branchWorkflowSource, /Qwen3-VL MLX/)
assert.match(branchWorkflowSource, /Qwen2\.5-VL Ollama fallback/)
assert.match(branchWorkflowSource, /Windows 路线概览/)
assert.match(branchWorkflowSource, /CLIP\/SigLIP ONNX/)
assert.doesNotMatch(source, /type MacOSAiWorkerProbeDisplay|: MacOSAiWorkerProbeDisplay|<MacOSAiWorkerProbeDisplay/)
assert.doesNotMatch(source, /MacOSAiWorkerProbeResult/)
assert.doesNotMatch(source, /selectPlatformAiBranchStatus/)
assert.match(statusAdapterSource, /llamaRuntimeGetStatus/)
assert.match(statusAdapterSource, /llamaRuntimeListLocalModels/)
assert.match(statusAdapterSource, /aiModelList/)
assert.match(statusAdapterSource, /aiModelStatus/)
assert.match(statusModuleSource, /projectPlatformAiWorkerProbeDiagnosticsSelection/)
assert.match(statusModuleSource, /projectPlatformPythonRuntimeCompatibilityDisplay/)
assert.match(statusModuleSource, /platformBranch: currentPlatformSelection\?\.platformBranch \?\? projectedBranchStatus\?\.platformBranch/)
assert.match(statusModuleSource, /probe: platformProbeResponse\?\.success \? platformProbeResponse\.data\?\.capabilities : null/)
assert.doesNotMatch(source, /projectMacOSAiWorkerProbeDisplay/)
assert.doesNotMatch(source, /projectWindowsAiWorkerProbeDisplay/)
assert.doesNotMatch(source, /projectPythonMpsCompatibilityDisplay/)
assert.doesNotMatch(source, /pythonMpsStatus/)
assert.doesNotMatch(statusModuleSource, /setInterval|showToast|pushLog|Date\.now/)
assert.match(matrixSource, /projectAiRuntimeCapabilityMatrixDisplay/)
assert.match(matrixSource, /export function PlatformAiCapabilityMatrix/)
assert.match(matrixSource, /AiWorkerLaneProbe/)
assert.doesNotMatch(matrixSource, /MacOSAiCapabilityMatrix/)
assert.doesNotMatch(matrixSource, /MacOSAiWorkerProbeResult\['lanes'\]/)
assert.doesNotMatch(matrixSource, /Windows 细项能力矩阵/)
assert.doesNotMatch(matrixSource, /macOS 细项能力矩阵/)
assert.match(matrixSource, /probe\.lanes\.map/)
assert.match(matrixSource, /capability\.modelFamily \?\? capability\.backend \?\? capability\.role/)
assert.match(matrixSource, /capability\.label/)
assert.match(matrixSource, /projectAiCapabilityStatusDisplay/)
assert.doesNotMatch(matrixSource, /const STATUS_LABELS/)
assert.doesNotMatch(matrixSource, /const STATUS_STYLES/)

const overviewSliceStart = source.indexOf('function OverviewWorkspace')
const overviewSliceEnd = source.indexOf('function RuntimeTile', overviewSliceStart)
const overviewSlice = source.slice(overviewSliceStart, overviewSliceEnd)

assert.doesNotMatch(overviewSlice, /onInstallMacOSDeps/)
assert.doesNotMatch(overviewSlice, /installingMacOSDeps/)
assert.doesNotMatch(overviewSlice, />安装 macOS AI 依赖</)
assert.doesNotMatch(overviewSlice, /label="MPS"/)
assert.doesNotMatch(overviewSlice, /label="Python MPS 兼容性"/)
assert.doesNotMatch(overviewSlice, /label="ONNX Runtime"/)
assert.doesNotMatch(overviewSlice, /label="CLIP\/SigLIP ONNX"/)
assert.doesNotMatch(overviewSlice, /label="CLIP\/SigLIP 兼容性"/)
assert.doesNotMatch(overviewSlice, /主要运行路线/)
assert.doesNotMatch(overviewSlice, /候选运行路线/)
assert.doesNotMatch(overviewSlice, /MLX/)
assert.doesNotMatch(overviewSlice, /platformProbeDisplay\.mps/)
assert.doesNotMatch(overviewSlice, /projectMacOSAiWorkerProbeDisplay/)
assert.doesNotMatch(overviewSlice, />macOS 路线概览</)
assert.doesNotMatch(overviewSlice, />Windows 路线概览</)
assert.doesNotMatch(overviewSlice, /platformWorkerProbe\?\.isMacOS\s*\?/)
assert.doesNotMatch(overviewSlice, /platformWorkerProbe\?\.torch\.mpsAvailable\s*\?/)
assert.doesNotMatch(overviewSlice, /platformWorkerProbe\?\.onnxruntime\.available\s*\?/)
assert.doesNotMatch(overviewSlice, /platformWorkerProbe\?\.clipSiglipOnnx\.available\s*\?/)
assert.doesNotMatch(overviewSlice, /platformWorkerProbe\?\.mlx\.available\s*\?/)
assert.doesNotMatch(source, /createPlatformAiBranchStatus/)
assert.doesNotMatch(source, /CHANNEL_AI_RUNTIME_GET_MACOS_AI_BRANCH_STATUS/)
assert.doesNotMatch(source, /function branchStatusTone/)
assert.doesNotMatch(source, /function branchStatusLabel/)
assert.doesNotMatch(source, /function branchWorkflowTitle/)
assert.doesNotMatch(source, /function cooperativeReadinessTone/)
assert.doesNotMatch(source, /function cooperativeReadinessDetail/)
assert.doesNotMatch(source, /queueStats\.failed \? 'warn' : 'good'/)
assert.doesNotMatch(source, /branch\?\.workflows\.some/)
assert.doesNotMatch(source, />Platform AI Branch Status</)
assert.doesNotMatch(source, /按共享 AI workflow/)

const active=await fs.readFile('src/renderer/routes/AiWorkspace.tsx','utf8')
assert.match(source,/AiWorkspace/)
assert.doesNotMatch(active,/createAiConsoleStatusModule|setInterval|installAiRuntimeDeps|clearGpuMemory|aiModelList|llamaRuntimeGetStatus/)
assert.match(active,/PiConnectionsPanel|TaskModelSettings|BackgroundOcrPanel|OcrEnvironmentSettings/)
console.log('Retired console no longer mounts unavailable platform/runtime polling; preserved adapter/workflow checks remain independent.')
