import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

const source = await fs.readFile('src/renderer/routes/AiConsolePage.tsx', 'utf8')
const matrixSource = await fs.readFile('src/renderer/components/settings/PlatformAiCapabilityMatrix.tsx', 'utf8')
const branchWorkflowSource = await fs.readFile('src/shared/workflows/platform-ai-branch-status.workflow.ts', 'utf8')

assert.match(source, /PlatformAiCapabilityMatrix/)
assert.doesNotMatch(source, /MacOSAiCapabilityMatrix/)
assert.match(source, /getMacOSCapabilities/)
assert.match(source, /getMacOSAiBranchStatus/)
assert.match(source, /getWindowsAiBranchStatus/)
assert.match(source, /getPythonMpsStatus/)
assert.match(source, /getClipSiglipOnnxStatus/)
assert.match(source, /projectPlatformAiRouteOverviewDisplay/)
assert.match(source, /Qwen3-VL GGUF/)
assert.doesNotMatch(branchWorkflowSource, /Qwen3-VL MLX/)
assert.match(branchWorkflowSource, /Qwen2\.5-VL Ollama fallback/)
assert.match(branchWorkflowSource, /Windows 路线概览/)
assert.match(source, /external HTTP fallback/)
assert.match(source, /summarizeOllamaFallback/)
assert.match(source, /summarizeExternalHttpFallback/)
assert.match(source, /Ollama fallback/)
assert.match(source, /Custom HTTP/)
assert.match(branchWorkflowSource, /CLIP\/SigLIP ONNX/)
assert.match(source, /PaddleOCR ONNX/)
assert.match(source, /MacOSAiWorkerProbeResult/)
assert.match(source, /PlatformAiBranchStatusResponse/)
assert.match(source, /PlatformAiBranchStatusPanel/)
assert.match(source, /display\.panelTitle/)
assert.match(source, /PlatformAiBranchStatusPanel/)
assert.match(source, /projectPlatformAiBranchStatusDisplay/)
assert.match(source, /selectPlatformAiBranchStatus/)
assert.match(source, /llamaRuntimeGetStatus/)
assert.match(source, /llamaRuntimeListLocalModels/)
assert.match(source, /GGUF 文本与 mmproj 图像推理通过/)
assert.match(source, /图像推理已验证/)
assert.match(source, /aiModelList/)
assert.match(source, /aiModelStatus/)
assert.match(source, /cooperativeRuntimeModels/)
assert.match(source, /projectAiConsoleModelReadinessDisplay/)
assert.match(source, /projectAiQueueStatusDisplay/)
assert.match(source, /projectGgufArtifactTileDisplay/)
assert.match(source, /projectMacOSAiWorkerProbeDisplay/)
assert.match(matrixSource, /projectAiRuntimeCapabilityMatrixDisplay/)
assert.match(matrixSource, /export function PlatformAiCapabilityMatrix/)
assert.doesNotMatch(matrixSource, /MacOSAiCapabilityMatrix/)
assert.doesNotMatch(matrixSource, /Windows 细项能力矩阵/)
assert.doesNotMatch(matrixSource, /macOS 细项能力矩阵/)
assert.match(matrixSource, /probe\.lanes\.map/)
assert.match(matrixSource, /capability\.modelFamily \?\? capability\.backend \?\? capability\.role/)
assert.match(matrixSource, /capability\.label/)
assert.match(matrixSource, /projectAiCapabilityStatusDisplay/)
assert.doesNotMatch(matrixSource, /const STATUS_LABELS/)
assert.doesNotMatch(matrixSource, /const STATUS_STYLES/)

const overviewSliceStart = source.indexOf('function OverviewWorkspace')
const overviewSliceEnd = source.indexOf('function RuntimeTile', overviewSliceStart)
const overviewSlice = source.slice(overviewSliceStart, overviewSliceEnd)

assert.match(overviewSlice, /platformWorkerProbe/)
assert.match(overviewSlice, /platformBranchStatus/)
assert.match(overviewSlice, /routeOverviewDisplay\.title/)
assert.match(overviewSlice, /routeOverviewDisplay\.description/)
assert.match(overviewSlice, /routeOverviewDisplay\.showMacOSDiagnostics/)
assert.match(overviewSlice, /routeOverviewDisplay\.runtimeLanes\.map/)
assert.match(overviewSlice, /routeOverviewDisplay\.installDependenciesLabel/)
assert.match(overviewSlice, /routeOverviewDisplay\.installingDependenciesLabel/)
assert.match(overviewSlice, /routeOverviewDisplay\.diagnosticTiles\.mpsLabel/)
assert.match(overviewSlice, /routeOverviewDisplay\.diagnosticTiles\.pythonCompatibilityLabel/)
assert.match(overviewSlice, /routeOverviewDisplay\.diagnosticTiles\.onnxRuntimeLabel/)
assert.match(overviewSlice, /routeOverviewDisplay\.diagnosticTiles\.clipSiglipOnnxLabel/)
assert.match(overviewSlice, /routeOverviewDisplay\.diagnosticTiles\.clipSiglipCompatibilityLabel/)
assert.match(overviewSlice, /routeOverviewDisplay\.primaryRuntimeLaneCaption/)
assert.match(overviewSlice, /routeOverviewDisplay\.candidateRuntimeLaneCaption/)
assert.doesNotMatch(overviewSlice, />安装 macOS AI 依赖</)
assert.doesNotMatch(overviewSlice, /label="MPS"/)
assert.doesNotMatch(overviewSlice, /label="Python MPS 兼容性"/)
assert.doesNotMatch(overviewSlice, /label="ONNX Runtime"/)
assert.doesNotMatch(overviewSlice, /label="CLIP\/SigLIP ONNX"/)
assert.doesNotMatch(overviewSlice, /label="CLIP\/SigLIP 兼容性"/)
assert.doesNotMatch(overviewSlice, /主要运行路线/)
assert.doesNotMatch(overviewSlice, /候选运行路线/)
assert.doesNotMatch(overviewSlice, /MLX/)
assert.match(overviewSlice, /Llama 路线/)
assert.match(overviewSlice, /Qwen2\.5-VL Ollama fallback/)
assert.match(overviewSlice, /external HTTP fallback/)
assert.match(overviewSlice, /Smoke GGUF/)
assert.match(overviewSlice, /Vision mmproj/)
assert.match(overviewSlice, /ggufArtifactDisplay/)
assert.match(overviewSlice, /platformProbeDisplay/)
assert.doesNotMatch(overviewSlice, />macOS 路线概览</)
assert.doesNotMatch(overviewSlice, />Windows 路线概览</)
assert.doesNotMatch(overviewSlice, /platformWorkerProbe\?\.isMacOS\s*\?/)
assert.doesNotMatch(overviewSlice, /platformWorkerProbe\?\.torch\.mpsAvailable\s*\?/)
assert.doesNotMatch(overviewSlice, /platformWorkerProbe\?\.onnxruntime\.available\s*\?/)
assert.doesNotMatch(overviewSlice, /platformWorkerProbe\?\.clipSiglipOnnx\.available\s*\?/)
assert.doesNotMatch(overviewSlice, /platformWorkerProbe\?\.mlx\.available\s*\?/)
assert.doesNotMatch(source, /createPlatformAiBranchStatus/)
assert.doesNotMatch(source, /CHANNEL_AI_RUNTIME_GET_MACOS_AI_BRANCH_STATUS/)
assert.doesNotMatch(source, /function branchStatusTone/)
assert.doesNotMatch(source, /function branchStatusLabel/)
assert.doesNotMatch(source, /function branchWorkflowTitle/)
assert.doesNotMatch(source, /function cooperativeReadinessTone/)
assert.doesNotMatch(source, /function cooperativeReadinessDetail/)
assert.doesNotMatch(source, /queueStats\.failed \? 'warn' : 'good'/)
assert.doesNotMatch(source, /branch\?\.workflows\.some/)
assert.doesNotMatch(source, />Platform AI Branch Status</)
assert.doesNotMatch(source, /按共享 AI workflow/)
