import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

const panelPath = 'src/renderer/components/settings/AiRuntimePanel.tsx'
const matrixPath = 'src/renderer/components/settings/PlatformAiCapabilityMatrix.tsx'
const settingsPath = 'src/renderer/routes/Settings.tsx'
const aiConsolePath = 'src/renderer/routes/AiConsolePage.tsx'
const doctorPanelPath = 'src/renderer/components/settings/DoctorPanel.tsx'
const platformAdapterPath = 'src/renderer/platform-ai-runtime.adapter.ts'

const panelSource = await fs.readFile(panelPath, 'utf8')
const matrixSource = await fs.readFile(matrixPath, 'utf8')
const settingsSource = await fs.readFile(settingsPath, 'utf8')
const aiConsoleSource = await fs.readFile(aiConsolePath, 'utf8')
const doctorPanelSource = await fs.readFile(doctorPanelPath, 'utf8')
const platformAdapterSource = await fs.readFile(platformAdapterPath, 'utf8')

assert.ok(panelSource.length > 0)
assert.doesNotMatch(settingsSource, /AiRuntimePanel/)
assert.match(aiConsoleSource, /AiRuntimePanel/)
assert.match(aiConsoleSource, /<AiRuntimePanel onEvidenceChanged=/)
assert.match(aiConsoleSource, /'runtime', 'AI 运行时管理'/)
assert.match(settingsSource, /<DoctorPanel \/>/)

assert.match(panelSource, /electronAPI\?\.aiRuntime/)
assert.match(panelSource, /listRuntimes/)
assert.match(panelSource, /getActiveRuntime/)
assert.match(panelSource, /selectPlatformAiRuntimeRequests/)
assert.match(platformAdapterSource, /getMacOSCapabilities/)
assert.match(platformAdapterSource, /getPythonMpsStatus/)
assert.match(platformAdapterSource, /probePythonMpsRuntime/)
assert.match(panelSource, /getClipSiglipOnnxStatus/)
assert.match(panelSource, /probeOnnxModelLoad/)
assert.match(panelSource, /probeOcrRealEvidence/)
assert.match(panelSource, /projectOcrRealEvidenceProbeDisplay/)
assert.match(panelSource, /验证 OCR 真实推理/)
assert.match(panelSource, /不会读取素材库、安装依赖或下载模型/)
assert.match(panelSource, /await onEvidenceChanged\?\.\(\)/)
assert.match(panelSource, /selectActiveRuntime/)
assert.match(panelSource, /startRuntime/)
assert.match(panelSource, /stopRuntime/)
assert.match(panelSource, /restartRuntime/)
assert.match(panelSource, /healthCheck/)
assert.match(panelSource, /healthCheckAll/)

assert.doesNotMatch(panelSource, /ipcRenderer/)
assert.doesNotMatch(panelSource, /process\.platform/)
assert.doesNotMatch(panelSource, /from ['"]fs['"]|from ['"]path['"]|require\(['"]fs['"]\)|require\(['"]path['"]\)/)
assert.doesNotMatch(panelSource, /\bfetch\s*\(|axios|XMLHttpRequest/)
assert.doesNotMatch(panelSource, /child_process|execFile|runProcess|pythonPath\s*=|ai-service\/app\.py/)
assert.doesNotMatch(panelSource, /\.(download|install)\s*\(|downloadModel|installRuntime|startInstall|runtimePackage[A-Z]/)
assert.doesNotMatch(panelSource, /settingsSave|updateSettings|saveSettings/)

const firstEffectStart = panelSource.indexOf('  useEffect(()')
const firstEffectEnd = panelSource.indexOf('}, [])', firstEffectStart)
const firstEffectBlock = panelSource.slice(firstEffectStart, firstEffectEnd)
assert.match(firstEffectBlock, /loadRuntimes/)
assert.doesNotMatch(firstEffectBlock, /startRuntime|restartRuntime|healthCheck/)

assert.match(panelSource, /AiRuntimeState/)
assert.match(panelSource, /AiRuntimeConfig/)
assert.match(panelSource, /PlatformAiBranchRuntimeMetadata/)
assert.doesNotMatch(panelSource, /MacOSAiBranchRuntimeMetadata \| WindowsAiBranchRuntimeMetadata/)
assert.match(panelSource, /getCurrentPlatformAiBranchRuntime/)
assert.match(panelSource, /resolvePlatformAiBranch/)
assert.doesNotMatch(panelSource, /getMacOSAiBranchRuntime/)
assert.doesNotMatch(panelSource, /getWindowsAiBranchRuntime/)
assert.match(panelSource, /<PlatformAiBranchPanel branch=\{currentPlatformAiBranch\} \/>/)
assert.doesNotMatch(panelSource, /\bmacosAiBranch\b/)
assert.doesNotMatch(panelSource, /\bwindowsAiBranch\b/)
assert.match(panelSource, /PlatformAiWorkerProbeWithRuntimeVersions/)
assert.match(panelSource, /platformBranch: PlatformAiBranch/)
assert.doesNotMatch(panelSource, /isWindows: boolean/)
assert.doesNotMatch(panelSource, /<PlatformAiWorkerProbePanel[^>]*isWindows=/)
assert.doesNotMatch(panelSource, /MacOSAiWorkerProbeResult \| WindowsAiWorkerProbeResult/)
assert.match(panelSource, /platformWorkerProbe/)
assert.match(panelSource, /platformWorkerProbeError/)
assert.match(panelSource, /CLIP\/SigLIP ONNX/)
assert.match(panelSource, /CLIP\/SigLIP ONNX 兼容性检查/)
assert.match(panelSource, /WD Tagger ONNX 真实加载验证/)
assert.match(panelSource, /projectOnnxModelLoadProbeDisplay/)
assert.match(panelSource, /projectAiRuntimePlatformPanelCopy/)
assert.match(panelSource, /projectPlatformPythonRuntimeCompatibilityDisplay/)
assert.match(panelSource, /projectPlatformPythonRuntimeExecutionProbeDisplay/)
assert.match(panelSource, /AiRuntimeCompatibilityDisplay/)
assert.match(panelSource, /AiRuntimeModelLoadProbeDisplay/)
assert.match(platformAdapterSource, /getPythonMpsStatus\?: \(\) => Promise<AiRuntimeIpcResponse<AiRuntimePythonMpsStatusResponse>>/)
assert.match(platformAdapterSource, /getPythonCudaStatus\?: \(\) => Promise<AiRuntimeIpcResponse<AiRuntimePythonCudaStatusResponse>>/)
assert.match(platformAdapterSource, /probePythonMpsRuntime\?: \(\) => Promise<AiRuntimeIpcResponse<AiRuntimePythonMpsExecutionProbeResponse>>/)
assert.match(platformAdapterSource, /probePythonCudaRuntime\?: \(\) => Promise<AiRuntimeIpcResponse<AiRuntimePythonCudaExecutionProbeResponse>>/)
assert.doesNotMatch(panelSource, /useState<AiRuntimePythonMpsStatusResponse \| AiRuntimePythonCudaStatusResponse/)
assert.doesNotMatch(panelSource, /useState<AiRuntimePythonMpsExecutionProbeResponse \| AiRuntimePythonCudaExecutionProbeResponse/)
assert.doesNotMatch(panelSource, /\bpythonMpsStatus\b/)
assert.doesNotMatch(panelSource, /\bpythonMpsExecutionProbe\b/)
assert.match(panelSource, /projectAiRuntimeBranchPanelDisplay/)
assert.match(panelSource, /projectAiRuntimeWorkerProbePanelDisplay/)
assert.match(panelSource, /PlatformAiCapabilityMatrix/)
assert.match(panelSource, /PlatformAiLaneDisplayInput/)
assert.doesNotMatch(panelSource, /type PlatformAiLaneLike/)
assert.match(panelSource, /function PlatformAiLaneCard/)
assert.doesNotMatch(panelSource, /MacOSAiCapabilityMatrix/)
assert.doesNotMatch(panelSource, /MacOSAiLaneLike/)
assert.match(panelSource, /projectAiRuntimeStatusDisplay/)
assert.match(panelSource, /projectAiRuntimeSummaryDisplay/)
assert.match(panelSource, /projectAiRuntimeHealthResultDisplay/)
assert.match(panelSource, /AiRuntimeStatusIcon/)
assert.doesNotMatch(panelSource, /ReturnType<typeof projectAiRuntimeStatusDisplay>\['icon'\]/)
assert.match(panelSource, /projectAiCapabilityStatusDisplay/)
assert.match(panelSource, /projectAiRuntimeInfoLabel/)
assert.match(panelSource, /projectAiRuntimeDisplayValue/)
assert.match(panelSource, /projectAiRuntimeActionLabel/)
assert.doesNotMatch(panelSource, /const STATUS_STYLE/)
assert.doesNotMatch(panelSource, /const STATUS_LABELS/)
assert.doesNotMatch(panelSource, /const INFO_LABELS/)
assert.doesNotMatch(panelSource, /function displayValue/)
assert.doesNotMatch(panelSource, /function actionLabel/)
assert.doesNotMatch(panelSource, /function isMacOSAiBranchMetadata/)
assert.doesNotMatch(panelSource, /function getMacOSAiBranchRuntime/)
assert.doesNotMatch(panelSource, /metadata\?\.macosAiBranch/)
assert.doesNotMatch(panelSource, /function statusText/)
assert.doesNotMatch(panelSource, /function branchStatusStyle/)
assert.doesNotMatch(panelSource, /runtime\.status === ['"]running['"]/)
assert.doesNotMatch(panelSource, /runtime\.status === ['"]failed['"]/)
assert.doesNotMatch(panelSource, /probe\?\.isMacOS\s*\?/)
assert.doesNotMatch(panelSource, /probe\.isMacOS\s*\?/)
assert.doesNotMatch(panelSource, /probe\.isAppleSilicon\s*\?/)
assert.doesNotMatch(panelSource, /macOSWorkerProbe/)
assert.doesNotMatch(panelSource, /setMacOSWorkerProbe/)
assert.doesNotMatch(panelSource, /Python CUDA 兼容性检查/)
assert.doesNotMatch(panelSource, /Python MPS 兼容性检查/)
assert.doesNotMatch(panelSource, /Python CUDA 真实执行验证/)
assert.doesNotMatch(panelSource, /Python MPS 真实执行验证/)
assert.doesNotMatch(panelSource, /Windows Worker 实时探测/)
assert.doesNotMatch(panelSource, /macOS Worker 实时探测/)
assert.doesNotMatch(panelSource, /Windows AI 分支/)
assert.doesNotMatch(panelSource, /macOS AI 分支/)
assert.match(matrixSource, /projectAiRuntimeCapabilityMatrixDisplay/)
assert.match(matrixSource, /export function PlatformAiCapabilityMatrix/)
assert.match(matrixSource, /AiWorkerLaneProbe/)
assert.match(matrixSource, /PlatformAiWorkerProbeWithRuntimeVersions/)
assert.match(matrixSource, /platformBranch: PlatformAiBranch/)
assert.doesNotMatch(matrixSource, /isWindows\??: boolean/)
assert.doesNotMatch(matrixSource, /type PlatformAiCapabilityMatrixProbe/)
assert.doesNotMatch(matrixSource, /MacOSAiCapabilityMatrix/)
assert.doesNotMatch(matrixSource, /MacOSAiLaneCard/)
assert.doesNotMatch(matrixSource, /MacOSAiWorkerProbeResult\['lanes'\]/)
assert.doesNotMatch(matrixSource, /MacOSAiWorkerProbeResult/)
assert.doesNotMatch(matrixSource, /WindowsAiWorkerProbeResult/)
assert.match(matrixSource, /probe\.lanes\.map/)
assert.match(matrixSource, /capability\.modelFamily \?\? capability\.backend \?\? capability\.role/)
assert.match(matrixSource, /capability\.label/)
assert.match(matrixSource, /projectAiCapabilityStatusDisplay/)
assert.doesNotMatch(matrixSource, /Windows 细项能力矩阵/)
assert.doesNotMatch(matrixSource, /macOS 细项能力矩阵/)
assert.doesNotMatch(matrixSource, /STATUS_LABELS\[/)
assert.doesNotMatch(matrixSource, /STATUS_STYLES\[/)

assert.match(doctorPanelSource, /export default function DoctorPanel/)
assert.match(doctorPanelSource, /doctor/)

const handleSaveStart = settingsSource.indexOf('const handleSave')
const handleSaveEnd = settingsSource.indexOf('const handleClearCache', handleSaveStart)
const handleSaveBlock = settingsSource.slice(handleSaveStart, handleSaveEnd)
assert.match(handleSaveBlock, /updateSettings/)
assert.doesNotMatch(handleSaveBlock, /aiRuntime|aiRuntimeSettings|startRuntime|healthCheck/)
