import assert from 'node:assert/strict'
import {test} from 'node:test'
import {evaluateBackgroundReadiness,type BackgroundTelemetry,type QualifiedBackgroundEnvelope} from '../src/main/background-analysis/background-resource-policy'
const now=20000,known=<T>(value:T)=>({kind:'known' as const,value,sampledAt:now}),base=():BackgroundTelemetry=>({memory:known({free:4*1024**3,total:8*1024**3}),battery:known(false),lowPower:known(false),thermal:known('nominal'),idle:known('idle'),visible:known(true),gpuFree:{kind:'unknown'}}),cpu:QualifiedBackgroundEnvelope={ownership:'host-owned',verified:true,peakRamBytes:256*1024**2,accelerator:'cpu',lightOnBattery:false}
await test('qualified CPU policy fixture can pass without invented GPU memory; production null binding never passes',()=>{assert.equal(evaluateBackgroundReadiness(base(),cpu,now).policyAllows,true);assert.deepEqual(evaluateBackgroundReadiness(base(),null,now).reasons,['automatic-executor-not-integrated'])})
await test('stale, future and missing memory samples are unknown rather than spare capacity',()=>{for(const value of [{kind:'unknown' as const},{kind:'known' as const,value:{free:4*1024**3,total:8*1024**3},sampledAt:0},{kind:'known' as const,value:{free:4*1024**3,total:8*1024**3},sampledAt:now+1}])assert.ok(evaluateBackgroundReadiness({...base(),memory:value},cpu,now).reasons.includes('memory-unknown'))})
await test('reserve, power, heat, interaction and visibility each deny new background admission',()=>{
 const cases:Array<[Partial<BackgroundTelemetry>,string]>=[[{memory:known({free:500*1024**2,total:8*1024**3})},'memory-insufficient'],[{battery:known(true)},'waiting-external-power'],[{lowPower:{kind:'unknown'}},'low-power-mode-unknown'],[{lowPower:known(true)},'low-power-mode'],[{thermal:known('serious')},'thermal-pressure'],[{idle:known('active')},'foreground-active'],[{idle:known('locked')},'session-locked'],[{visible:known(false)},'no-visible-window']]
 for(const [change,reason]of cases){const r=evaluateBackgroundReadiness({...base(),...change},cpu,now);assert.equal(r.policyAllows,false);assert.ok(r.reasons.includes(reason))}
})
await test('unowned runtime, absent envelope and GPU unknown cannot inherit CPU-only eligibility',()=>{assert.ok(evaluateBackgroundReadiness(base(),{...cpu,ownership:'unowned'},now).reasons.includes('runtime-not-owned'));assert.ok(evaluateBackgroundReadiness(base(),{...cpu,verified:false},now).reasons.includes('execution-envelope-unknown'));assert.ok(evaluateBackgroundReadiness(base(),{...cpu,accelerator:'gpu',peakGpuBytes:1},now).reasons.includes('gpu-memory-unknown'))})
