import {test} from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import {build} from 'esbuild'
import {_electron as electron} from 'playwright'
import {createChatGptContractFixture} from './chatgpt-contract-fixture.mjs'
const root=await fs.mkdtemp(path.join(os.tmpdir(),'dam-pi-codex-contract-'));let app
try{
 const fixture=await createChatGptContractFixture(root,{});await fs.symlink(path.resolve('node_modules'),path.join(root,'node_modules'),'dir')
 const renderer=await build({stdin:{contents:`import React from'react';import{createRoot}from'react-dom/client';import Panel from'./src/renderer/components/asset/PiConnectionsPanel';createRoot(document.getElementById('root')).render(<Panel loginEligibility={()=>({allowed:true,code:'ISOLATED_CONTRACT_ONLY',message:'仅合成网络，不代表账号验收'})}/>);`,loader:'tsx',resolveDir:process.cwd()},bundle:true,platform:'browser',format:'iife',outfile:path.join(root,'bundle.js'),write:false,logLevel:'silent'});for(const f of renderer.outputFiles)await fs.writeFile(f.path,f.contents)
 await fs.writeFile(path.join(root,'index.html'),'<link rel="stylesheet" href="bundle.css"><div id="root"></div><script src="bundle.js"></script>')
 const preload=`const{contextBridge,ipcRenderer}=require('electron');const invoke=(n,v)=>ipcRenderer.invoke(n,v);contextBridge.exposeInMainWorld('electronAPI',{contractCurrentOperation:()=>invoke('contract:operation'),contractCallback:()=>invoke('contract:callback'),aiBackendList:()=>invoke('contract:list'),settingsLoad:()=>invoke('contract:settings'),aiConnections:{credentialStatus:id=>invoke('ai-connection:credential-status',id),login:id=>invoke('ai-connection:login',id),loginStatus:id=>invoke('ai-connection:login-status',id),answerLogin:v=>invoke('ai-connection:answer-login',v),cancelLogin:id=>invoke('ai-connection:cancel-login',id)}})`;await fs.writeFile(path.join(root,'preload.cjs'),preload)
 const main=`import{app,BrowserWindow,ipcMain}from'electron';import fs from'node:fs';import{spawn}from'node:child_process';import{createAiConnectionService}from'./src/main/ai-gateway/ai-connection-service';import{createPiRuntimeHost}from'./src/main/ai-gateway/pi-runtime-host';import{createCredentialVault}from'./src/main/ai-credentials/credential-vault';import{createSyntheticSecretProtection}from'./src/main/ai-credentials/synthetic-secret-protection';import{registerAiConnectionIpc}from'./src/main/ipc/ai-connection.ipc';import{createNewInstallAppSettingsDefaults}from'./src/main/services/settings/settings-defaults.builder';import{publicBackend,publicSettings}from'./src/main/ai-credentials/public-settings';
 const root=${JSON.stringify(root)};for(const n of ['userData','sessionData','logs','crashDumps'])app.setPath(n,root+'/'+n);
 let settings=createNewInstallAppSettingsDefaults();const base={...settings.aiBackends[0],id:'codex-a',name:'ChatGPT A',transport:'pi',providerKind:'openai',authMode:'oauth',enabled:true,baseUrl:'https://api.openai.com/v1'};settings.aiBackends=[base,{...base,id:'codex-b',name:'ChatGPT B'}];let window,lastOperation;
 const owned=createPiRuntimeHost({root:${JSON.stringify(path.resolve('pi-runtime'))},spawn:(node,args,options)=>spawn(node,[${JSON.stringify(fixture.bootstrap)}],options)}),stats=[];
 const runtime={inspect:owned.inspect,execute:(request,signal,callbacks={})=>owned.execute(request,signal,{...callbacks,interaction:event=>{if(event.type==='contract-network'){stats.push({method:event.method,path:event.path});fs.writeFileSync(root+'/network.json',JSON.stringify(stats))}else callbacks.interaction?.(event)}})};
 const service=createAiConnectionService({hostIdentity:{getDeviceId:()=> '00000000-0000-4000-8000-000000000001'},admission:()=>({allowed:true,code:'ISOLATED_CONTRACT_ONLY',message:''}),settings:{getSettings:()=>settings,saveSettings:patch=>{settings={...settings,...patch};return settings}},vault:createCredentialVault({file:root+'/vault.json',protection:createSyntheticSecretProtection(root)}),runtime,changed:()=>{}});
 registerAiConnectionIpc({service,handle:(n,h)=>ipcMain.handle(n,async(e,...args)=>{const result=await h(e,...args);if(n==='ai-connection:login')lastOperation=result.id;return result}),isMain:e=>e.sender===window?.webContents});ipcMain.handle('contract:operation',()=>lastOperation);ipcMain.handle('contract:callback',()=>{const url=new URL(service.authUrlForOperation(lastOperation));return{url:url.searchParams.get('redirect_uri')+'?code=synthetic&state='+url.searchParams.get('state')+'&client_id=oaiapp_synthetic',client:url.searchParams.get('client_id'),hint:url.searchParams.has('id_token_hint'),name:url.searchParams.get('agent_name_hint')}});ipcMain.handle('contract:list',()=>settings.aiBackends.map(publicBackend));ipcMain.handle('contract:settings',()=>publicSettings(settings));
 app.whenReady().then(()=>{window=new BrowserWindow({width:1100,height:1000,webPreferences:{preload:root+'/preload.cjs',contextIsolation:true,nodeIntegration:false}});window.loadFile(root+'/index.html')});let drained=false;app.on('before-quit',e=>{if(!drained){e.preventDefault();void service.drain().finally(()=>{drained=true;app.quit()})}});app.on('window-all-closed',()=>app.quit());`
 await build({stdin:{contents:main,loader:'ts',resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',packages:'external',outfile:path.join(root,'main.cjs'),logLevel:'silent'})
 const env=Object.fromEntries(Object.entries(process.env).filter(([k])=>!['ELECTRON_RUN_AS_NODE','ELECTRON_RENDERER_URL','NODE_OPTIONS'].includes(k)&&!k.startsWith('DAM_')));app=await electron.launch({args:[path.join(root,'main.cjs')],env});const page=await app.firstWindow();page.setDefaultTimeout(20000)
 const status=async()=>page.evaluate(async()=>window.electronAPI.aiConnections.loginStatus(await window.electronAPI.contractCurrentOperation()))
 const begin=async(name='ChatGPT A')=>{await page.getByRole('button',{name:new RegExp(name+' ·')}).click();await page.getByRole('button',{name:'Continue with ChatGPT'}).click();await page.locator('input[type=password]').waitFor();return await page.evaluate(()=>window.electronAPI.contractCurrentOperation())}
 const until=async(check)=>{for(let i=0;i<300;i++){if(await check())return;await new Promise(r=>setTimeout(r,25))}throw Error('contract wait timeout')}
 await test('actual SDK/Main/React guarded ChatGPT sign-in commits only verified registration; public status has no auth query or token',async()=>{
  await begin();const current=await status();assert.equal(current.prompt.type,'manual_code');assert.equal(new URL(current.event.url).search,'');const callback=await page.evaluate(()=>window.electronAPI.contractCallback());assert.equal(callback.client,'dynamic_agent_client');assert.equal(callback.name,'DAM');await page.locator('input[type=password]').fill(callback.url);await page.getByRole('button',{name:'提交授权信息'}).click();await until(async()=>(await status()).state==='completed');const completed=await status();assert.equal(completed.planUsageAuthorized,true);assert.ok(!JSON.stringify(completed).includes('synthetic-access'));assert.equal((await page.evaluate(()=>window.electronAPI.aiBackendList()))[0].credentialRevision,1)
 })
 await test('new Worker reuses same issued client and protected hint; reauthentication does not register another client',async()=>{
  await begin();const callback=await page.evaluate(()=>window.electronAPI.contractCallback());assert.equal(callback.client,'oaiapp_synthetic');assert.equal(callback.hint,true);assert.equal(callback.name,null);assert.ok(!JSON.stringify(await status()).includes('id_token_hint'));await page.locator('input[type=password]').fill(callback.url);await page.getByRole('button',{name:'提交授权信息'}).click();await until(async()=>(await status()).state==='completed');assert.equal((await page.evaluate(()=>window.electronAPI.aiBackendList()))[0].credentialRevision,2)
 })
 await test('invalid callback and cancellation do not replace verified account or perform token requests',async()=>{
  const before=JSON.parse(await fs.readFile(path.join(root,'network.json'),'utf8')).length;await begin();const callback=await page.evaluate(()=>window.electronAPI.contractCallback());await page.locator('input[type=password]').fill(callback.url.replace(/state=[^&]+/,'state=invalid'));await page.getByRole('button',{name:'提交授权信息'}).click();await until(async()=>(await status()).state==='failed');assert.equal((await page.evaluate(()=>window.electronAPI.aiBackendList()))[0].credentialRevision,2);assert.equal(JSON.parse(await fs.readFile(path.join(root,'network.json'),'utf8')).length,before);await begin();await page.getByRole('button',{name:'取消订阅登录'}).click();await until(async()=>(await status()).state==='cancelled')
 })
}finally{if(app)await app.close();await fs.rm(root,{recursive:true,force:true})}
