#!/usr/bin/env python3
import os
import sys
import sqlite3
import argparse

def main():
    parser = argparse.ArgumentParser(
        description="Securely clean up pending tag suggestions and asset tags generated by 'ai_florence_ocr'."
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--dry-run",
        action="store_true",
        default=True,
        help="Perform a dry run to inspect the status without modifying the database (default)."
    )
    group.add_argument(
        "--confirm",
        action="store_true",
        help="Permanently delete or clean up all pending tags from 'ai_florence_ocr' source."
    )
    
    args = parser.parse_args()
    if args.confirm:
        args.dry_run = False

    db_path = os.path.expanduser("~/DesignAssetManager/design_asset_manager.db")
    if not os.path.exists(db_path):
        print(f"Error: Database file does not exist at {db_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Connecting to SQLite database: {db_path}")
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    try:
        # 1. Gather statistics
        # Pending suggestions
        cursor.execute(
            "SELECT COUNT(*) FROM tag_suggestions WHERE source = 'ai_florence_ocr' AND status = 'pending'"
        )
        pending_sugs_count = cursor.fetchone()[0]

        # Confirmed suggestions (should not be touched)
        cursor.execute(
            "SELECT COUNT(*) FROM tag_suggestions WHERE source = 'ai_florence_ocr' AND status = 'confirmed'"
        )
        confirmed_sugs_count = cursor.fetchone()[0]

        # Pending asset_tags relations
        cursor.execute(
            "SELECT COUNT(*) FROM asset_tags WHERE source = 'ai_florence_ocr' AND status = 'pending'"
        )
        pending_asset_tags_count = cursor.fetchone()[0]

        # Confirmed asset_tags relations (should not be touched)
        cursor.execute(
            "SELECT COUNT(*) FROM asset_tags WHERE source = 'ai_florence_ocr' AND status = 'confirmed'"
        )
        confirmed_asset_tags_count = cursor.fetchone()[0]

        print("\n==============================================")
        print("           FLORENCE OCR TAG STATISTICS        ")
        print("==============================================")
        print(f"Pending Tag Suggestions (tag_suggestions):    {pending_sugs_count}")
        print(f"Confirmed Tag Suggestions (tag_suggestions):  {confirmed_sugs_count} (Safe - will NOT touch)")
        print(f"Pending Asset-Tag Relations (asset_tags):     {pending_asset_tags_count}")
        print(f"Confirmed Asset-Tag Relations (asset_tags):   {confirmed_asset_tags_count} (Safe - will NOT touch)")
        print("==============================================")

        if args.dry_run:
            print("\n[DRY RUN] No modifications have been made to the database.")
            print("To delete pending Florence OCR suggestions and relations, run with --confirm.")
        else:
            if pending_sugs_count == 0 and pending_asset_tags_count == 0:
                print("\nNo pending Florence OCR tags found. Nothing to clean up.")
                return

            print(f"\n[CONFIRMATION] Proceeding to clean up:")
            print(f" - Deleting {pending_sugs_count} pending tag suggestions...")
            print(f" - Deleting {pending_asset_tags_count} pending asset-tag relations...")

            # Perform deletions in a transaction
            cursor.execute(
                "DELETE FROM tag_suggestions WHERE source = 'ai_florence_ocr' AND status = 'pending'"
            )
            sugs_deleted = cursor.rowcount

            cursor.execute(
                "DELETE FROM asset_tags WHERE source = 'ai_florence_ocr' AND status = 'pending'"
            )
            relations_deleted = cursor.rowcount

            conn.commit()
            print("\nCleanup completed successfully!")
            print(f" - Deleted {sugs_deleted} pending tag suggestions.")
            print(f" - Deleted {relations_deleted} pending asset-tag relations.")

    except Exception as e:
        conn.rollback()
        print(f"Error executing cleanup: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        conn.close()

if __name__ == "__main__":
    main()
