import {exerciseRealLocalAi,verifyRealLocalAiRestored} from './real-local-ai-electron-flow.mjs'
if(process.env.DAM_E2E_REAL_LOCAL_AI==='1')process.env.DAM_E2E_OCR='1'
import {exerciseDedicatedOcr,verifyDedicatedOcrRestored} from './dedicated-ocr-electron-flow.mjs'
import {exerciseAiDiscovery,verifyAiDiscoveryRestored} from './ai-discovery-electron-flow.mjs'
import {exerciseWorkSets,verifyWorkSetsRestored} from './work-sets-electron-flow.mjs'
import {exerciseOrganization,verifyOrganizationRestored} from './organization-electron-flow.mjs'
// Runs the formal composition in a scratch profile/library. Optional input folder must contain authorized test copies.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import {createHash} from 'node:crypto'
import {execFileSync} from 'node:child_process'
import {_electron as electron} from 'playwright'
import sharp from 'sharp'
import {transform} from 'esbuild'
if(!process.env.DAM_SKIP_BUILD)execFileSync(process.execPath,['node_modules/electron-vite/bin/electron-vite.js','build'],{stdio:'inherit'})
const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'dam-library-canvas-e2e-'))),profile=path.join(root,'profile'),library=path.join(root,'library'),evidence=path.join(root,'evidence'),sources=path.join(root,'sources')
await Promise.all([profile,evidence,sources].map(d=>fs.mkdir(d,{recursive:true})))
const supplied=process.env.DAM_AUTHORIZED_TEST_COPIES;const privateRun=Boolean(supplied);if(privateRun&&(process.env.DAM_E2E_OCR==='1'||process.env.DAM_E2E_AI_DISCOVERY==='1'||process.env.DAM_E2E_WORKSETS==='1'||process.env.DAM_E2E_ORGANIZATION==='1'))throw Error('WORKFLOW_VISUAL_TESTS_REQUIRE_GENERATED_FIXTURES');let originals=[]
if(supplied){const dir=await fs.realpath(supplied);assert.ok(dir.startsWith(await fs.realpath(os.tmpdir())));for(const [i,name]of(await fs.readdir(dir)).entries()){const file=path.join(dir,name),stat=await fs.lstat(file);if(!stat.isFile()||stat.isSymbolicLink())continue;const to=path.join(sources,`sample-${i}${path.extname(name)}`);await fs.copyFile(file,to);originals.push(to)}}else{
 const source=await fs.readFile('src/renderer/routes/work-mode-prototype/fixtures.ts','utf8');const transformed=await transform(source,{loader:'ts',format:'esm'});const fixtureModule=path.join(root,'generated-fixtures.mjs');await fs.writeFile(fixtureModule,transformed.code);const generated=await import(fixtureModule);
 for(const [i,ext]of ['png','jpg','webp'].entries()){const file=path.join(sources,`sample-${i}.${ext}`);let image=sharp(Buffer.from(decodeURIComponent(generated.assets[i].src.split(',').slice(1).join(','))));if(ext==='jpg')image=image.jpeg();else if(ext==='webp')image=image.webp();else image=image.png();await image.toFile(file);originals.push(file)}
}
if(process.env.DAM_E2E_OCR==='1'){
 for(const [name,body] of [['ocr-chinese','<text x="60" y="220" font-family="PingFang SC,sans-serif" font-size="48">设计素材 2026</text>'],['ocr-blank','']]){const file=path.join(sources,name+'.png');await sharp(Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="960" height="640"><rect width="960" height="640" fill="#fff"/>${body}</svg>`)).png().toFile(file);originals.push(file)}
}
const unsupported=path.join(sources,'sample-unsupported.txt');await fs.writeFile(unsupported,'unsupported fixture');const selections=[...originals,unsupported];const sha=async file=>createHash('sha256').update(await fs.readFile(file)).digest('hex');const hashes=await Promise.all(selections.map(sha));const milestones=[],errors=[]
const config={rootDirectory:root,profileDirectory:profile,libraryDirectory:library,evidenceDirectory:evidence,sourceSelections:[selections,selections]}
const options={colorScheme:null,args:['.','--dam-active-library-synthetic-e2e',`--user-data-dir=${profile}`],env:{...process.env,NODE_ENV:'test',DAM_ACTIVE_LIBRARY_SYNTHETIC_E2E:JSON.stringify(config)}}
let app=await electron.launch(options)
const assertImages=async(page,selector)=>{await page.waitForFunction(selector=>{const imgs=[...document.querySelectorAll(selector)];return imgs.length>0&&imgs.every(img=>img.complete&&img.naturalWidth>0)},selector)}
let liveCount=0,failed=false
try{
 let page=await app.firstWindow();page.on('pageerror',()=>errors.push('renderer-error'));await page.setViewportSize({width:1379,height:1042});await page.getByTestId('formal-library-canvas').waitFor()
 assert.equal(await page.locator('.work-prototype').count(),0);if(process.platform==='darwin'){const geometry=await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];return{outer:w.getBounds(),content:w.getContentBounds()}});assert.equal(geometry.outer.y,geometry.content.y)}const paths=await app.evaluate(({app})=>[app.getPath('userData'),app.getPath('sessionData'),app.getPath('logs'),app.getPath('crashDumps')]);assert.ok(paths.every(p=>p.startsWith(root+path.sep)));assert.equal(await page.evaluate(async()=>{try{await fetch('https://must-be-blocked.invalid/');return false}catch{return true}}),true);milestones.push('formal-renderer-and-private-scratch-profile-no-network')
 await page.getByTestId('library-create').click();await page.getByTestId('library-create-confirm').click();await page.getByRole('button',{name:'添加图片',exact:true}).click();const expectedCount=originals.filter(f=>/\.(png|jpe?g|webp)$/i.test(f)).length;await page.getByTestId('library-copy-review').getByText(new RegExp(`可收录 ${expectedCount} 个；排除 ${selections.length-expectedCount} 个`)).waitFor();await page.getByTestId('library-copy-confirm').click();await page.locator('.lc-card').first().waitFor();const badge=page.locator('.library-manager .ui-status').first();assert.equal(await badge.getAttribute('data-tone'),'neutral');assert.equal(await page.locator('.library-manager [data-testid=library-add-assets]').evaluate(e=>getComputedStyle(e).backgroundImage),'none');if(!privateRun)await page.screenshot({path:path.join(evidence,'neutral-library-manager.png')});if(await page.getByRole('button',{name:'关闭资料库管理'}).count())await page.getByRole('button',{name:'关闭资料库管理'}).click();await assertImages(page,'.lc-card-open img');liveCount=await page.locator('.lc-card').count();assert.equal(liveCount,expectedCount);const assets=await page.evaluate(()=>window.damClient.listAssets());assert.equal(assets.length,liveCount);const first=assets[0],id=first.id;const title=first.title;const filetype=first.file_type||first.fileType;assert.ok(['png','jpg','jpeg','webp'].includes(filetype.toLowerCase()));milestones.push('copy-import-real-authority-controlled-preview-and-format-rejection')
 assert.equal(await page.locator('.context-heading').count(),0);assert.equal((await page.locator('.library-content').boundingBox()).y,0);
 const rail=await page.locator('.icon-rail').boundingBox();assert.equal(rail.x,0);assert.equal(rail.width,70);assert.equal((await page.locator('.main-view').boundingBox()).x,70);
 const inspectorScope=await page.getByTestId('formal-library-canvas').getAttribute('data-library-scope');const imgSrc=await page.locator('.lc-card-open img').first().getAttribute('src');assert.match(imgSrc,/^dam-preview:\/\/preview\//)
 await page.getByRole('textbox',{name:'搜索素材'}).fill(title);await page.waitForFunction(()=>document.querySelectorAll('.lc-card').length===1);assert.match(await page.locator('.lc-match').innerText(),/名称|标题|文件/);await page.getByRole('textbox',{name:'搜索素材'}).fill('no-such-library-item');await page.getByRole('button',{name:'清除搜索与筛选'}).click();await page.waitForFunction(n=>document.querySelectorAll('.lc-card').length===n,liveCount);milestones.push('live-name-search-explanation-and-clear-empty-query')
 const tag=await page.evaluate(()=>window.damClient.tagCreate({name:'e2e-canvas-tag'}));const tagId=tag.tag?.id||tag.id;assert.ok(tagId);await page.evaluate(async({id,tagId})=>{const r=await window.damClient.assetTagAdd(id,tagId,{source:'manual',status:'confirmed'});if(r?.success===false)throw new Error('TAG_SETUP_FAILED')},{id,tagId})
 await page.getByRole('button',{name:'更多功能菜单'}).click();await page.getByRole('menuitem',{name:'刷新素材'}).click();await page.getByRole('button',{name:'按标签筛选 e2e-canvas-tag'}).click();await page.waitForFunction(()=>document.querySelectorAll('.lc-card').length===1);await page.getByRole('button',{name:'取消筛选 tag:e2e-canvas-tag'}).click();await page.waitForFunction(n=>document.querySelectorAll('.lc-card').length===n,liveCount);milestones.push('saved-tag-filter-and-clear-via-formal-store')
 await app.evaluate(({ipcMain})=>{globalThis.__savedCanvasList=ipcMain._invokeHandlers.get('assets:list');ipcMain.removeHandler('assets:list');ipcMain.handle('assets:list',()=>{throw new Error('SYNTHETIC_LIST_FAILURE')})})
 await page.getByRole('button',{name:'更多功能菜单'}).click();await page.getByRole('menuitem',{name:'刷新素材'}).click();await page.getByRole('alert').getByText('刷新失败，保留已载入素材。',{exact:false}).waitFor();assert.equal(await page.locator('.lc-card').count(),liveCount)
 await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('assets:list');ipcMain.handle('assets:list',globalThis.__savedCanvasList);delete globalThis.__savedCanvasList})
 await page.getByRole('alert').getByRole('button',{name:'重试',exact:true}).click();await page.getByRole('alert').waitFor({state:'detached'});milestones.push('failed-refresh-preserves-content-and-retries')
 const trigger=page.locator(`[id="asset-card-open-${id}"]`);await trigger.click();await page.getByRole('region',{name:'素材详细分析'}).waitFor();const grid=await page.locator('.lc-center').boundingBox(),side=await page.locator('.lc-side-details').boundingBox();assert.ok(grid.x+grid.width<=side.x+1);assert.equal(await page.locator('.image-tools-panel').count(),1);assert.equal(await page.getByText('编辑标签、描述与素材工具',{exact:true}).count(),0);assert.equal(await page.locator('.palette-labels').count(),0);if(!privateRun)await page.screenshot({path:path.join(evidence,'formal-library-side.png')});milestones.push('side-detail-layout-and-retained-tool-callers')
 const info=page.getByRole('region',{name:'素材信息',exact:true});await info.getByText('来源',{exact:true}).waitFor();assert.ok(await info.getByText('素材标签管理',{exact:true}).isVisible());assert.ok(await info.getByText('画面描述',{exact:true}).isVisible());assert.equal(await info.locator('details').count(),0)
 assert.ok(await page.locator('.immediate-palette').evaluate(e=>e.nextElementSibling?.getAttribute('aria-label')==='素材信息'))
 const tagInput=info.getByRole('textbox',{name:''}).first();await tagInput.fill('inspector-layout-tag');const suggestions=page.getByRole('listbox',{name:'标签建议'});await suggestions.waitFor();assert.equal(await suggestions.evaluate(e=>!!e.closest('.host-editor')),false)
 assert.ok(await suggestions.evaluate(e=>{const r=e.getBoundingClientRect();return r.width>100&&r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight}))
 assert.ok(await info.locator('.host-editor').evaluate(e=>getComputedStyle(e).overflowY==='visible'&&getComputedStyle(e).maxHeight==='none'))
 if(!privateRun)await page.screenshot({path:path.join(evidence,'inspector-tags-unclipped.png')})
 await page.getByRole('button',{name:'切换明暗外观',exact:true}).click();await tagInput.fill('inspector-layout-tag');await suggestions.waitFor();await page.waitForFunction(()=>{const e=document.querySelector('.tag-suggestions [aria-selected=true]');if(!e)return false;const s=getComputedStyle(e),sample=document.createElement('div');sample.style.backgroundColor=s.getPropertyValue('--accent-soft');return s.backgroundColor===sample.style.backgroundColor});if(!privateRun)await page.screenshot({path:path.join(evidence,'inspector-tags-dark.png')});await suggestions.getByRole('option').first().click()
 await page.waitForFunction(async id=>(await window.damClient.listAssets()).find(a=>a.id===id)?.tags.includes('inspector-layout-tag'),id)
 await page.getByRole('button',{name:'切换明暗外观',exact:true}).click();milestones.push('expanded-metadata-and-unclipped-tag-popup-pointer-write')
 await trigger.focus();await page.keyboard.press('Space');const focus=page.getByRole('dialog',{name:'专注模式',exact:true});await focus.waitFor();await assertImages(page,'.canvas-image-frame img');assert.equal(await focus.locator('.focus-filmstrip button').count(),liveCount);await focus.getByRole('button',{name:'放大图片'}).click();assert.ok(Number(await focus.locator('.canvas-viewport').getAttribute('data-zoom'))>1);await focus.getByRole('button',{name:'适应窗口'}).click();if(liveCount>1){const previous=await focus.locator('.canvas-image-frame img').getAttribute('src');const next=focus.getByRole('button',{name:'下一张',exact:true});if(await next.isEnabled())await next.click();else await focus.getByRole('button',{name:'上一张',exact:true}).click();await assertImages(page,'.canvas-image-frame img');assert.notEqual(await focus.locator('.canvas-image-frame img').getAttribute('src'),previous)}if(!privateRun)await page.screenshot({path:path.join(evidence,'formal-library-focus.png')});await focus.getByRole('button',{name:'添加笔记',exact:true}).click();await focus.getByRole('button',{name:'矩形',exact:true}).click();const frame=await focus.locator('.canvas-image-frame').boundingBox();await page.mouse.move(frame.x+frame.width*.2,frame.y+frame.height*.2);await page.mouse.down();await page.mouse.move(frame.x+frame.width*.5,frame.y+frame.height*.5,{steps:5});await page.mouse.up();assert.equal(await focus.locator('[data-note-element=rect]').count(),1);const noteAssetId=await focus.locator('.focus-filmstrip button[aria-current=true]').getAttribute('data-focus-id');
 await focus.getByRole('button',{name:'保存笔记',exact:true}).click();await focus.getByRole('alertdialog',{name:'启用笔记保存'}).waitFor();await focus.getByRole('button',{name:'取消',exact:true}).click();
 const noteScope=await page.evaluate(async assetId=>{const a=await window.damClient.library.inspect();return{libraryIdentity:a.identity,generation:a.generation,assetId}},noteAssetId);
 assert.equal((await page.evaluate(s=>window.damClient.library.notebookRead(s),noteScope)).value.requiresUpgrade,true);
 await focus.getByRole('button',{name:'保存笔记',exact:true}).click();await focus.getByRole('button',{name:'升级并保存笔记',exact:true}).click();await focus.getByText('笔记已保存到当前素材库；原图未改变。',{exact:true}).waitFor();
 const committed=await page.evaluate(s=>window.damClient.library.notebookRead(s),noteScope);assert.equal(committed.value.book.pages[0].elements[0].kind,'rect');assert.equal(committed.value.requiresUpgrade,false);
 // Failure leaves a draft available for a retry.
 await focus.getByRole('textbox',{name:'笔记名称',exact:true}).fill('Saved reference');
 page.on('dialog',dialog=>{if(dialog.type()!=='beforeunload')void dialog.dismiss().catch(()=>{})});
 await app.evaluate(({dialog})=>{globalThis.__noteOriginalDialog=dialog.showMessageBoxSync;globalThis.__noteExitPrompts=0;dialog.showMessageBoxSync=()=>{globalThis.__noteExitPrompts++;return 0}});
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());
 assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),1);
 assert.equal(await app.evaluate(()=>globalThis.__noteExitPrompts),1);
 await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=globalThis.__noteOriginalDialog;delete globalThis.__noteOriginalDialog});
 await page.keyboard.press('Escape');await focus.waitFor({state:'detached'});
 await page.evaluate(()=>{window.__savedConfirm=window.confirm;window.confirm=()=>false});
 await page.getByRole('link',{name:'资料库管理'}).click();await page.getByTestId('library-close').click();
 assert.equal((await page.evaluate(()=>window.damClient.library.inspect())).state,'ready');
 await page.evaluate(()=>{window.confirm=window.__savedConfirm;delete window.__savedConfirm});
 await page.getByRole('button',{name:'关闭资料库管理'}).click();
 await page.evaluate(()=>{location.hash='#/settings'});await page.waitForURL('**/settings');
 await page.evaluate(()=>{location.hash='#/library'});await page.locator('.lc-card').first().waitFor();
 const draftTrigger=page.locator(`[id="asset-card-open-${noteAssetId}"]`);await draftTrigger.focus();await page.keyboard.press('Space');
 await focus.getByRole('button',{name:'切换 Saved reference',exact:true}).waitFor();
 assert.equal(await focus.getByRole('textbox',{name:'笔记名称',exact:true}).inputValue(),'Saved reference');
 milestones.push('unsaved-notes-cancel-library-close-native-window-close-and-survive-route-change');

 await app.evaluate(({ipcMain})=>{globalThis.__notesSave=ipcMain._invokeHandlers.get('library-notebook:save');ipcMain.removeHandler('library-notebook:save');ipcMain.handle('library-notebook:save',()=>({success:false,error:'模拟保存失败'}))});
 await focus.getByRole('button',{name:'保存笔记',exact:true}).click();await focus.getByRole('status').filter({hasText:'当前草稿保留'}).waitFor();assert.equal(await focus.getByRole('textbox',{name:'笔记名称',exact:true}).inputValue(),'Saved reference');
 await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('library-notebook:save');ipcMain.handle('library-notebook:save',globalThis.__notesSave);delete globalThis.__notesSave});
 await focus.getByRole('button',{name:'保存笔记',exact:true}).click();await focus.getByText('笔记已保存到当前素材库；原图未改变。',{exact:true}).waitFor();milestones.push('notebook-upgrade-consent-save-failure-retains-draft-and-retry');
 if(!privateRun)await page.screenshot({path:path.join(evidence,'notebook-saved.png')});
 await page.keyboard.press('Escape');await focus.waitFor({state:'detached'});assert.equal(await page.locator(`[id="asset-card-open-${noteAssetId}"]`).evaluate(e=>e===document.activeElement),true);milestones.push('focus-hard-cut-controlled-media-zoom-gallery-and-focus-restore')
 const savedOcr=process.env.DAM_E2E_OCR==='1'?await exerciseDedicatedOcr(page,app,evidence):null;if(savedOcr)milestones.push('dedicated-ocr-real-cpu-empty-edit-draft-search-v8-and-session-safety');
 const savedRealAi=process.env.DAM_E2E_REAL_LOCAL_AI==='1'?await exerciseRealLocalAi(page,evidence):null;if(savedRealAi)milestones.push('real-qwen-and-rapidocr-coexist-with-user-edits-empty-precedence-and-cancellation');
 const savedAi=process.env.DAM_E2E_AI_DISCOVERY==='1'?await exerciseAiDiscovery(page,app,evidence):null;if(savedAi)milestones.push('ai-analysis-suggestions-search-explanation-dynamic-folders-no-copies');
 const savedWorkSets=process.env.DAM_E2E_WORKSETS==='1'?await exerciseWorkSets(page,app,evidence):null;if(savedWorkSets)milestones.push('multi-native-worksets-save-colors-notes-reorder-layout-revoke-and-reopen');
 const savedOrganization=process.env.DAM_E2E_ORGANIZATION==='1'?await exerciseOrganization(page,app,evidence):null;if(savedOrganization)milestones.push('organization-ui-folders-references-palettes-and-save-retry');
 await page.getByRole('link',{name:'资料库管理'}).click();await page.getByTestId('library-close').click();assert.equal(await page.locator('.lc-card,.lc-side-details,.lc-focus').count(),0);assert.notEqual(await page.evaluate(async src=>{try{return(await fetch(src)).status}catch{return 0}},imgSrc),200);await page.getByTestId('library-reopen').click();await page.locator('.lc-card').first().waitFor();assert.equal(await page.getByTestId('formal-library-canvas').getAttribute('data-library-scope'),inspectorScope);milestones.push('closed-library-denies-preview-and-reopen-rebinds-current-authority')
 await app.close();app=await electron.launch(options);page=await app.firstWindow();await page.getByTestId('formal-library-canvas').waitFor();if(await page.getByTestId('library-reopen').count())await page.getByTestId('library-reopen').click();else if(await page.getByTestId('library-open').count())await page.getByTestId('library-open').click();await page.locator('.lc-card').first().waitFor();assert.equal(await page.locator('.lc-card').count(),liveCount);await assertImages(page,'.lc-card-open img');milestones.push('process-restart-retains-library-and-previews');
 const restoredNotes=await page.evaluate(async assetId=>{const a=await window.damClient.library.inspect();return window.damClient.library.notebookRead({libraryIdentity:a.identity,generation:a.generation,assetId})},noteAssetId);assert.equal(restoredNotes.value.book.pages[0].name,'Saved reference');
 const noteTrigger=page.locator(`[id="asset-card-open-${noteAssetId}"]`);await noteTrigger.focus();await page.keyboard.press('Space');await page.getByRole('button',{name:'切换 Saved reference',exact:true}).waitFor();assert.equal(await page.locator('[data-note-element=rect]').count(),1);await page.keyboard.press('Escape');milestones.push('notebook-ui-restores-after-application-restart');
 if(savedRealAi){await verifyRealLocalAiRestored(page,savedRealAi);milestones.push('real-local-ai-ocr-and-user-description-survive-restart')}
 if(savedOcr){await verifyDedicatedOcrRestored(page,savedOcr);milestones.push('dedicated-ocr-and-user-correction-restored-after-process-restart')}
 if(savedAi){await verifyAiDiscoveryRestored(page,savedAi);milestones.push('ai-search-and-dynamic-folders-restored-after-restart')}
 if(savedWorkSets){await verifyWorkSetsRestored(page,app,savedWorkSets);milestones.push('native-worksets-and-device-layout-restored-after-restart')}
 if(savedOrganization){await verifyOrganizationRestored(page,savedOrganization);milestones.push('organization-ui-restored-after-application-restart')}
 assert.deepEqual(await Promise.all(selections.map(sha)),hashes);assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>Object.keys(localStorage).some(k=>k.startsWith('dam-')&&k.includes('prototype'))),false)
 const result={passed:milestones.length,milestones,assetCount:liveCount,privateCopies:privateRun,sourceHashesPreserved:true,privateScreenshotsTaken:false,rendererErrors:errors,sourcePathsDisclosed:false};await fs.writeFile(path.join(evidence,'report.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({...result,evidence:privateRun?'private-test-report-retained-locally':evidence},null,2))
 if(process.env.DAM_LIBRARY_CANVAS_REVIEW==='1'){if(process.env.DAM_E2E_WORKSETS==='1')await page.getByRole('button',{name:'工作模式',exact:true}).click();else if(process.env.DAM_E2E_ORGANIZATION==='1')await page.getByRole('button',{name:'文件夹',exact:true}).click();else if(process.env.DAM_E2E_OCR==='1'&&savedOcr){await page.locator(`[id="asset-card-open-${savedOcr.chinese}"]`).click();await page.getByRole('region',{name:'专用文字识别',exact:true}).scrollIntoViewIfNeeded()}console.log('Formal Library review ready. Isolated test Library; close the application or press Ctrl+C to finish.');await new Promise(resolve=>{process.once('SIGINT',resolve);process.once('SIGTERM',resolve);app.process().once('exit',resolve)})}
}catch(e){failed=true;if(!privateRun){console.error(e); try{const page=await app.firstWindow();await page.screenshot({path:path.join(evidence,'failure.png')});console.log('Failure evidence:',evidence)}catch{}}throw e}finally{if(failed)app.process().kill('SIGKILL');else await app.close().catch(()=>{})}
