import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

const ipcSource = await fs.readFile('src/main/ipc/ai-worker.ipc.ts', 'utf8')
const rendererSource = await fs.readFile('src/renderer/routes/AiConsolePage.tsx', 'utf8')
const overviewWorkflowSource = await fs.readFile('src/shared/workflows/ai-console-overview.workflow.ts', 'utf8')
const installerSource = await fs.readFile('ai-service/tools/install_macos_ai_deps.py', 'utf8')

assert.match(ipcSource, /ipcMain\.handle\('macos-ai:install-deps'/)
assert.match(ipcSource, /failedPackages/)
assert.match(ipcSource, /installedPackages/)
assert.match(ipcSource, /durationMs/)
assert.match(ipcSource, /outputTail/)
assert.match(ipcSource, /JSON\.parse\(line\)/)
assert.match(ipcSource, /PYTHONPYCACHEPREFIX/)
assert.match(ipcSource, /ensureManagedAiPythonRuntime/)
assert.match(ipcSource, /managed-venv-python/)
assert.match(ipcSource, /runtime:\s*{[\s\S]*managed:\s*true/)
assert.doesNotMatch(ipcSource, /console\.log\('\[macos-ai:install-deps\] Running:', pythonExe, installScript\)/)

assert.match(installerSource, /"type": "complete"/)
assert.match(installerSource, /"package": "all"/)
assert.match(installerSource, /"package": "pip \(all\)"/)
assert.match(installerSource, /sys\.exit\(1\)/)

assert.match(rendererSource, /projectAiConsoleDependencyInstallCopy/)
assert.match(rendererSource, /projectAiConsoleDependencyInstallCopy\('macos'\)/)
assert.match(rendererSource, /aiDependencyInstallCopy\.completedLog\(result\)/)
assert.match(rendererSource, /aiDependencyInstallCopy\.failedLog\(result\)/)
assert.doesNotMatch(rendererSource, /failedPackages/)
assert.doesNotMatch(rendererSource, /installedPackages/)
assert.doesNotMatch(rendererSource, /managed runtime created|managed runtime reused/)
assert.doesNotMatch(rendererSource, /macOS AI deps install failed/)
assert.match(overviewWorkflowSource, /failedPackages/)
assert.match(overviewWorkflowSource, /installedPackages/)
assert.match(overviewWorkflowSource, /managed runtime created|managed runtime reused/)
assert.match(overviewWorkflowSource, /macOS AI deps install failed/)

const ocrDependencySource = await fs.readFile('src/main/services/ocr-dependency.service.ts', 'utf8')
const aiRuntimeIpcSource = await fs.readFile('src/main/ipc/ai-runtime.ipc.ts', 'utf8')
const aiPythonRuntimeSource = await fs.readFile('src/main/services/ai-python-runtime.service.ts', 'utf8')
const aiPythonEnvironmentSource = await fs.readFile('src/main/services/ai-python-environment.ts', 'utf8')
const cooperativeModelIpcSource = await fs.readFile('src/main/ipc/cooperative-model.ipc.ts', 'utf8')
const modelDownloadSource = await fs.readFile('src/main/services/ai-models/ai-model-download.service.ts', 'utf8')

assert.match(ocrDependencySource, /resolveBasePythonExecutable/)
assert.match(ocrDependencySource, /resolveManagedAiPythonRuntime/)
assert.match(ocrDependencySource, /ensureManagedAiPythonRuntime/)
assert.match(ocrDependencySource, /app\.getPath\(name\)/)
assert.match(aiPythonEnvironmentSource, /const AI_PYTHON_ENVIRONMENT_PLATFORM_ADAPTERS: AiPythonEnvironmentPlatformAdapter\[\]/)
assert.match(aiPythonEnvironmentSource, /resolveAiPythonEnvironmentPlatformAdapter/)
assert.match(aiPythonEnvironmentSource, /platform: 'win32'[\s\S]*managedPythonPathParts: \['Scripts', 'python\.exe'\]/)
assert.match(aiPythonEnvironmentSource, /managedPythonPathParts: \['bin', 'python'\]/)
assert.doesNotMatch(aiPythonEnvironmentSource, /host\.platform === 'win32' \? path\.win32 : path\.posix/)
assert.match(aiPythonEnvironmentSource, /interface BasePythonResolverInput/)
assert.match(aiPythonEnvironmentSource, /platform: 'win32'[\s\S]*resolveBasePythonExecutable: resolveWindowsBasePythonExecutable/)
assert.match(aiPythonEnvironmentSource, /platform: 'darwin'[\s\S]*resolveBasePythonExecutable: resolveMacOSHomebrewPythonExecutable/)
assert.doesNotMatch(aiPythonEnvironmentSource, /const resolvers: BasePythonResolver\[\]/)
assert.doesNotMatch(aiPythonEnvironmentSource, /process\.platform|process\.env/)
assert.match(aiRuntimeIpcSource, /ai-python-runtime\.service/)
assert.match(aiRuntimeIpcSource, /resolvePythonExecutable/)
assert.doesNotMatch(aiRuntimeIpcSource, /ocr-dependency\.service/)
assert.match(aiPythonRuntimeSource, /resolveMacOSAiPythonRuntime/)
assert.match(cooperativeModelIpcSource, /ensureManagedAiPythonRuntime/)
assert.match(modelDownloadSource, /ensureManagedAiPythonRuntime/)
