import {test} from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import {build} from 'esbuild'
import {_electron as electron} from 'playwright'
import {createPiContractFixture} from './pi-contract-fixture.mjs'
const root=await fs.mkdtemp(path.join(os.tmpdir(),'dam-pi-codex-contract-'));let app
try{
 const fixture=await createPiContractFixture(root,{allowCodex:true,provider:'openai-codex'});await fs.symlink(path.resolve('node_modules'),path.join(root,'node_modules'),'dir')
 const renderer=await build({stdin:{contents:`import React from'react';import{createRoot}from'react-dom/client';import Panel from'./src/renderer/components/asset/PiConnectionsPanel';createRoot(document.getElementById('root')).render(<Panel loginEligibility={()=>({allowed:true,code:'ISOLATED_CONTRACT_ONLY',message:'仅合成网络，不代表账号验收'})}/>);`,loader:'tsx',resolveDir:process.cwd()},bundle:true,platform:'browser',format:'iife',outfile:path.join(root,'bundle.js'),write:false,logLevel:'silent'});for(const f of renderer.outputFiles)await fs.writeFile(f.path,f.contents)
 await fs.writeFile(path.join(root,'index.html'),'<link rel="stylesheet" href="bundle.css"><div id="root"></div><script src="bundle.js"></script>')
 const preload=`const{contextBridge,ipcRenderer}=require('electron');const invoke=(n,v)=>ipcRenderer.invoke(n,v);contextBridge.exposeInMainWorld('damClient',{contractCurrentOperation:()=>invoke('contract:operation'),contractAuthState:()=>invoke('contract:auth-state'),aiBackendList:()=>invoke('contract:list'),settingsLoad:()=>invoke('contract:settings'),aiConnections:{credentialStatus:id=>invoke('ai-connection:credential-status',id),login:id=>invoke('ai-connection:login',id),loginStatus:id=>invoke('ai-connection:login-status',id),answerLogin:v=>invoke('ai-connection:answer-login',v),cancelLogin:id=>invoke('ai-connection:cancel-login',id)}})`;await fs.writeFile(path.join(root,'preload.cjs'),preload)
 const main=`import{app,BrowserWindow,ipcMain}from'electron';import fs from'node:fs';import{spawn}from'node:child_process';import{createAiConnectionService}from'./src/main/ai-gateway/ai-connection-service';import{createPiRuntimeHost}from'./src/main/ai-gateway/pi-runtime-host';import{createCredentialVault}from'./src/main/ai-credentials/credential-vault';import{createSyntheticSecretProtection}from'./src/main/ai-credentials/synthetic-secret-protection';import{registerAiConnectionIpc}from'./src/main/ipc/ai-connection.ipc';import{createNewInstallAppSettingsDefaults}from'./src/main/services/settings/settings-defaults.builder';import{publicBackend,publicSettings}from'./src/main/ai-credentials/public-settings';
 const root=${JSON.stringify(root)};for(const n of ['userData','sessionData','logs','crashDumps'])app.setPath(n,root+'/'+n);
 let settings=createNewInstallAppSettingsDefaults();const base={...settings.aiBackends[0],id:'codex-a',name:'Codex A',transport:'pi',providerKind:'openai-codex',authMode:'oauth',enabled:true,baseUrl:'https://chatgpt.com/backend-api'};settings.aiBackends=[base,{...base,id:'codex-b',name:'Codex B'}];let window,lastOperation;
 const owned=createPiRuntimeHost({root:${JSON.stringify(path.resolve('pi-runtime'))},spawn:(node,args,options)=>spawn(node,[${JSON.stringify(fixture.bootstrap)}],options)}),stats=[];
 const runtime={inspect:owned.inspect,execute:(request,signal,callbacks={})=>owned.execute(request,signal,{...callbacks,interaction:event=>{if(event.type==='contract-network'){stats.push({method:event.method,path:event.path});fs.writeFileSync(root+'/network.json',JSON.stringify(stats))}else callbacks.interaction?.(event)}})};
 const service=createAiConnectionService({admission:()=>({allowed:true,code:'ISOLATED_CONTRACT_ONLY',message:''}),settings:{getSettings:()=>settings,saveSettings:patch=>{settings={...settings,...patch};return settings}},vault:createCredentialVault({file:root+'/vault.json',protection:createSyntheticSecretProtection(root)}),runtime,changed:()=>{}});
 registerAiConnectionIpc({service,handle:(n,h)=>ipcMain.handle(n,async(e,...args)=>{const result=await h(e,...args);if(n==='ai-connection:login')lastOperation=result.id;return result}),isMain:e=>e.sender===window?.webContents});ipcMain.handle('contract:operation',()=>lastOperation);ipcMain.handle('contract:auth-state',()=>new URL(service.authUrlForOperation(lastOperation)).searchParams.get('state'));ipcMain.handle('contract:list',()=>settings.aiBackends.map(publicBackend));ipcMain.handle('contract:settings',()=>publicSettings(settings));
 app.whenReady().then(()=>{window=new BrowserWindow({width:1100,height:1000,webPreferences:{preload:root+'/preload.cjs',contextIsolation:true,nodeIntegration:false}});window.loadFile(root+'/index.html')});let drained=false;app.on('before-quit',e=>{if(!drained){e.preventDefault();void service.drain().finally(()=>{drained=true;app.quit()})}});app.on('window-all-closed',()=>app.quit());`
 await build({stdin:{contents:main,loader:'ts',resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',packages:'external',outfile:path.join(root,'main.cjs'),logLevel:'silent'})
 const env=Object.fromEntries(Object.entries(process.env).filter(([k])=>!['ELECTRON_RUN_AS_NODE','ELECTRON_RENDERER_URL','NODE_OPTIONS'].includes(k)&&!k.startsWith('DAM_')));app=await electron.launch({args:[path.join(root,'main.cjs')],env});const page=await app.firstWindow();page.setDefaultTimeout(20000)
 const status=async()=>page.evaluate(async()=>window.damClient.aiConnections.loginStatus(await window.damClient.contractCurrentOperation()))
 const begin=async(name='Codex A')=>{await page.getByRole('button',{name:new RegExp(name+' ·')}).click();await page.getByRole('button',{name:'开始订阅登录'}).click();await page.getByLabel('订阅登录方式').waitFor();return await page.evaluate(()=>window.damClient.contractCurrentOperation())}
 const until=async(check)=>{for(let i=0;i<300;i++){if(await check())return;await new Promise(r=>setTimeout(r,25))}throw Error('contract wait timeout')}
 const answer=async(method)=>{await page.getByLabel('订阅登录方式').selectOption(method);await page.getByRole('button',{name:'提交授权信息'}).click()}
 await test('actual Codex select crosses fixed Worker/Main/React; invalid answer rejected and device branch completes using fake network',async()=>{
  const operation=await begin(),state=await status();assert.equal(state.prompt.type,'select');assert.deepEqual(state.prompt.options.map(o=>o.id),['browser','device_code']);assert.equal(await page.locator('input[type=password]').count(),0)
  await assert.rejects(page.evaluate(v=>window.damClient.aiConnections.answerLogin(v),{id:operation,promptId:state.prompt.id,answer:'illegal-method'}))
  await answer('device_code');await until(async()=>(await status()).state==='completed');const calls=JSON.parse(await fs.readFile(path.join(root,'network.json'),'utf8'));assert.deepEqual(calls.map(c=>c.path),['/api/accounts/deviceauth/usercode','/api/accounts/deviceauth/token','/oauth/token']);assert.equal((await page.evaluate(()=>window.damClient.aiBackendList()))[0].credentialRevision,1)
 })
 await test('actual Codex browser branch preserves state, manual code and one fake token exchange',async()=>{
  await begin('Codex B');await answer('browser');await until(async()=>(await status()).prompt?.type==='manual_code');const current=await status(),state=await page.evaluate(()=>window.damClient.contractAuthState());assert.ok(state)
  await page.locator('input[type=password]').fill('http://localhost:1455/auth/callback?code=synthetic-code&state='+state);await page.getByRole('button',{name:'提交授权信息'}).click();await until(async()=>(await status()).state==='completed');assert.equal((await page.evaluate(()=>window.damClient.aiBackendList()))[1].credentialRevision,1);assert.equal(JSON.parse(await fs.readFile(path.join(root,'network.json'),'utf8')).length,4)
 })
 await test('actual Codex wrong callback state leaves old account revision intact and performs no token exchange',async()=>{
  await begin('Codex B');await answer('browser');await until(async()=>(await status()).prompt?.type==='manual_code');await page.locator('input[type=password]').fill('http://localhost:1455/auth/callback?code=synthetic-code&state=wrong');await page.getByRole('button',{name:'提交授权信息'}).click();await until(async()=>(await status()).state==='failed');assert.equal((await page.evaluate(()=>window.damClient.aiBackendList()))[1].credentialRevision,1);assert.equal(JSON.parse(await fs.readFile(path.join(root,'network.json'),'utf8')).length,4)
 })
 await test('actual Codex cancellation and A-B-A selection expire prior prompts without network',async()=>{
  const a=await begin('Codex A'),prompt=(await status()).prompt.id;await begin('Codex B');await begin('Codex A');await assert.rejects(page.evaluate(v=>window.damClient.aiConnections.answerLogin(v),{id:a,promptId:prompt,answer:'browser'}));await page.getByRole('button',{name:'取消订阅登录'}).click();await until(async()=>(await status()).state==='cancelled');assert.equal(JSON.parse(await fs.readFile(path.join(root,'network.json'),'utf8')).length,4)
 })
}finally{if(app)await app.close();await fs.rm(root,{recursive:true,force:true})}
