import {test} from 'node:test'
import assert from 'node:assert/strict'
import http from 'node:http'
import path from 'node:path'
import {createPiRuntimeHost} from '../src/main/ai-gateway/pi-runtime-host'
const runtime=createPiRuntimeHost({root:path.resolve('pi-runtime')}),jpeg='data:image/jpeg;base64,AQID'
async function fixture(mode='valid'){
 let calls=0,auth='';const sockets=new Set<any>();const server=http.createServer(async(req,res)=>{calls++;auth=req.headers.authorization??'';const parts=[];for await(const chunk of req)parts.push(chunk);const b=JSON.parse(Buffer.concat(parts).toString());assert.equal(b.model,'synthetic');assert.ok(b.messages.find((m:any)=>m.role==='user').content.some((c:any)=>c.type==='image_url'));if(mode==='hang')return;if(mode==='http-error'){res.writeHead(429);res.end('private response never surface');return}
 res.writeHead(200,{'Content-Type':'text/event-stream'});const content=mode==='oversize'?'x'.repeat(520000):'{"caption":"生成参考","ocrText":"","prompt":"Generated reference","tags":["蓝色"]}'
 res.write('data: '+JSON.stringify({id:'s',object:'chat.completion.chunk',choices:[{index:0,delta:{role:'assistant',content},finish_reason:null}]})+'\n\n');res.write('data: '+JSON.stringify({id:'s',object:'chat.completion.chunk',choices:[{index:0,delta:{},finish_reason:mode==='length'?'length':'stop'}]})+'\n\n');res.end('data: [DONE]\n\n')});server.on('connection',socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket))});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const a=server.address() as any
 return{get calls(){return calls},get auth(){return auth},baseUrl:`http://127.0.0.1:${a.port}/v1`,close:async()=>{for(const s of sockets)s.destroy();await new Promise<void>(r=>server.close(()=>r()))}}
}
const request=(baseUrl:string)=>({kind:'infer',connection:{id:'synthetic',providerKind:'openai-compatible',authMode:'none',baseUrl,capabilities:{vision:true}},model:'synthetic',systemPrompt:'Return JSON',userPrompt:'Generated fixture only',imageDataUrl:jpeg,temperature:.2,maxTokens:128})
await test('fixed Node and installed Pi run one image request with zero inherited credential',async()=>{const f=await fixture();try{process.env.OPENAI_API_KEY='fixture-must-not-leak';const v=await runtime.execute<any>(request(f.baseUrl),AbortSignal.timeout(15000));assert.equal(v.choices[0].finish_reason,'stop');assert.ok(v.choices[0].message.content.includes('生成参考'));assert.equal(f.calls,1);assert.equal(f.auth,'');assert.equal(runtime.inspect().unknown,0)}finally{delete process.env.OPENAI_API_KEY;await f.close()}})
await test('HTTP error is one attempt without SDK retries or raw provider body',async()=>{const f=await fixture('http-error');try{await assert.rejects(runtime.execute(request(f.baseUrl),AbortSignal.timeout(15000)),/AI_PROVIDER_FAILED/);assert.equal(f.calls,1)}finally{await f.close()}})
await test('length stop survives mapping for DAM-owned single retry',async()=>{const f=await fixture('length');try{const v=await runtime.execute<any>(request(f.baseUrl),AbortSignal.timeout(15000));assert.equal(v.choices[0].finish_reason,'length');assert.equal(f.calls,1)}finally{await f.close()}})
await test('oversized stream never becomes a successful result',async()=>{const f=await fixture('oversize');try{await assert.rejects(runtime.execute(request(f.baseUrl),AbortSignal.timeout(15000)));assert.equal(f.calls,1)}finally{await f.close()}})
await test('cancel owns and waits for the worker close without affecting another server',async()=>{const f=await fixture('hang'),a=new AbortController();try{const p=runtime.execute(request(f.baseUrl),a.signal);const outcome=p.catch(e=>e);for(let i=0;i<500&&!f.calls;i++)await new Promise(r=>setTimeout(r,10));assert.equal(f.calls,1);a.abort();assert.equal((await outcome).message,'AI_CANCELLED');assert.equal(runtime.inspect().unknown,0)}finally{a.abort();await f.close()}})
