import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

const source = await fs.readFile('scripts/windows-ai-real-evidence-validation.ps1', 'utf8')

assert.match(source, /function ConvertTo-RedactedText/)
assert.match(source, /\.Replace\(\$env:USERPROFILE, "<USERPROFILE>"\)/)
assert.match(source, /\.Replace\(\$env:TEMP, "<TEMP>"\)/)
assert.match(source, /\.Replace\(\$RepoRoot, "<REPO_ROOT>"\)/)
assert.ok(source.includes('$redacted = $redacted.Replace($RepoRoot.Replace("\\", "/"), "<REPO_ROOT>")'))
assert.ok(source.includes("[regex]::Replace($redacted, '(?i)\\b[A-Z]:[\\\\/][^\"\\r\\n]*', '<LOCAL_PATH>')"))
assert.ok(source.includes('text.replace(/\\b[A-Z]:[\\\\/][^"\\r\\n]*/gi, "<LOCAL_PATH>")'))

assert.match(source, /\$output = @\(& \$Command @Arguments 2>&1\)/)
assert.match(source, /Write-Log \(\[string\]\$item\)/)
assert.doesNotMatch(source, /dam-native-(?:stdout|stderr)/)
assert.doesNotMatch(source, /> \$stdoutPath 2> \$stderrPath/)
assert.doesNotMatch(source, /\(\$item \| Out-String\)\.TrimEnd\(\)/)
assert.match(source, /probe_ocr_real_evidence\.py", "--provider", "auto"/)
assert.match(source, /probePythonCudaRuntime/)
assert.match(source, /probeOcrRealEvidence/)
assert.match(source, /generatedFixture !== true/)
assert.match(source, /downloadsAllowed !== false/)
assert.match(source, /status !== "executed_real"/)
assert.match(source, /source === "worker_probe" && item\.code === "runtime_probe_ready"/)
assert.match(source, /tagging\?\.status !== "real_model_path"/)
assert.match(source, /llamaProbe\?\.probe\?\.success === true && prompt\?\.status !== "real_model_path"/)
assert.match(source, /ocr\?\.status === "real_model_path"/)
assert.match(source, /structured OCR missing evidence/)
assert.match(source, /OCR model artifact missing requirement/)
assert.match(source, /primary-lane model artifact/)
assert.match(source, /getByTestId\("platform-ai-branch-status"\)/)
assert.match(source, /branchStatusPanel\.scrollIntoViewIfNeeded\(\)/)
assert.match(source, /"--disable-gpu"/)
assert.match(source, /page\.bringToFront\(\)/)
assert.match(source, /branchStatusPanel\.screenshot\(\{ path: screenshot \}\)/)

console.log('windows-ai-real-evidence-validation-contract passed')
