import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { createHash } from 'node:crypto';
import Database from 'better-sqlite3';
import sharp from 'sharp';
import { createActiveLibraryHost } from '../src/main/library-lifecycle';
import { createProductionActiveLibraryHostDependencies } from '../src/main/library-lifecycle/production-active-library-dependencies';
import { createWindowsVideoRuntime } from '../src/main/work-mode/windows-video-runtime';
import { VIDEO_RUNTIME_FILE } from '../src/main/work-mode/video-identity.generated';
import { createWorkFileHandoffs } from '../src/main/work-mode/work-file-handoff';
import { createWorkMediaController } from '../src/main/work-mode/work-media-controller';
import { registerWorkMediaIpc } from '../src/main/ipc/work-media.ipc';
import { validateWorkSourceUrl, validateWorkHandoff } from '../src/shared/contracts/work-media.contract';
import type { WorkMediaWrite } from '../src/shared/contracts/work-media.contract';
const root = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'dam-work-media-'))), library = path.join(root, '素材库'), image = path.join(root, '测试 image.bat');
const video = path.resolve('.scratch/d-work-mode-20261008/sources/公开短片 Big Buck Bunny.mp4'), sha = (b: Uint8Array) => createHash('sha256').update(b).digest('hex'), videoDigest = sha(await fs.readFile(video));
assert.equal(videoDigest, 'f78f39603e6774907f2faafabf26a667f4a6fc31769ec304a8a8f7c62d280508');
await sharp({ create: { width: 80, height: 90, channels: 4, background: '#55667788' } }).png().toFile(image);
const imageDigest = sha(await fs.readFile(image));
let sources = [image], framesDecoded = 0;
const native = createWindowsVideoRuntime({ directory: path.dirname(path.resolve('build/windows-video-runtime', VIDEO_RUNTIME_FILE)) });
const runtime = { ...native, frame: async (...args: Parameters<typeof native.frame>) => { framesDecoded++; return native.frame(...args); } };
const dependencies = createProductionActiveLibraryHostDependencies({ selectLibraryDirectory: async () => ({ kind: 'selected', directory: library }), selectLocalFiles: async () => ({ kind: 'selected', files: sources.map(filePath => ({ filePath })) }) }, { videoRuntime: runtime });
let host = createActiveLibraryHost(dependencies);
const plan = await host.prepareCreate();
if (plan.kind !== 'planned')
    throw Error('CREATE_PLAN');
await host.confirmCreate(plan.plan.receipt);
let add = await host.prepareAddAssets();
if (add.kind !== 'planned')
    throw Error('ADD_PLAN');
await host.dispatchAddAssets(add.plan.receipt);
let state = host.inspect(), scope = { libraryIdentity: state.identity!, generation: state.generation! }, status = await host.workMediaStatus(scope);
await host.enableBasicAnalysis({ ...scope, sessionToken: status.sessionToken, expectedSchemaVersion: 1, allowUpgrade: true }, new AbortController().signal);
status = await host.workMediaStatus(scope);
assert.equal(status.schemaVersion, 14);
const dbFile = path.join(library, '.dam', 'library.sqlite');
// Discover only this created Library's declared control DB; this is an internal
// readback, never an alternative user entry or an arbitrary filesystem search.
const databaseName = (await fs.readdir(path.join(library, '.dam'))).find(name => name.endsWith('.sqlite') && !name.includes('lock'))!;
const snapshot = () => { const db = new Database(path.join(library, '.dam', databaseName), { readonly: true, fileMustExist: true }); try {
    return Object.fromEntries(['assets', 'capture_requests', 'asset_candidates', 'promotion_links', 'asset_lifecycle', 'basic_analysis_requests', 'basic_analysis_attempts', 'basic_analysis_evidence'].map(table => [table, db.prepare('SELECT * FROM ' + table + ' ORDER BY 1').all()]));
}
finally {
    db.close();
} };
const old = snapshot();
process.stdout.write('work-media: migration and preservation\n');
await assert.rejects(host.enableWorkMedia({ ...scope, sessionToken: status.sessionToken, expectedSchemaVersion: 14, allowUpgrade: false }));
assert.equal((await host.workMediaStatus(scope)).schemaVersion, 14);
assert.deepEqual(snapshot(), old);
await host.enableWorkMedia({ ...scope, sessionToken: status.sessionToken, expectedSchemaVersion: 14, allowUpgrade: true });
assert.equal((await host.workMediaStatus(scope)).schemaVersion, 15);
assert.deepEqual(snapshot(), old);
sources = [video];
add = await host.prepareAddAssets();
if (add.kind !== 'planned')
    throw Error('VIDEO_PLAN');
assert.equal(add.plan.items[0].detectedFormat, 'mp4');
const invalid = path.join(root, 'invalid.mp4');
await fs.writeFile(invalid, Buffer.from([0, 0, 0, 24, ...Buffer.from('ftypisom'), 0, 0, 0, 0]));
sources = [invalid];
const badPlan = await host.prepareAddAssets();
assert.equal(badPlan.kind, 'planned');
if (badPlan.kind === 'planned') {
    assert.equal(badPlan.plan.confirmable, false);
    assert.equal(badPlan.plan.items[0].eligibility.kind, 'excluded');
}
sources = [video];
await host.dispatchAddAssets(add.plan.receipt);
const assets = await host.listAssets(), clip = assets.find(a => a.fileType === 'mp4')!, picture = assets.find(a => a.fileType === 'png')!;
assert.ok(clip);
assert.equal((await host.readRetrievalCoverage()).total, 1, 'Whole-image retrieval counts the image, not the video first-frame preview');
await assert.rejects(host.searchSemanticPage({...scope, query:'', mode:'image', imageAssetId:clip.id, tagScope:'includes-pending', limit:10}), /RETRIEVAL_QUERY_VIDEO_UNSUPPORTED/);
assert.ok((await sharp(await host.readPreview(clip.id)).metadata()).width);
let catalog = await host.readWorkSets(scope, 'device:media-test');
catalog = await host.writeWorkSet({ ...scope, sessionToken: catalog.sessionToken, allowUpgrade: false, command: { kind: 'create', value: { name: '视频工作集', assetIds: [clip.id, picture.id], colors: [], columns: 2, note: '素材与帧分别保存' } } }, 'device:media-test');
const mediaScope = { ...scope, setId: catalog.sets[0].id, assetId: clip.id };
process.stdout.write('work-media: native capture and persistence\n');
let media = await host.readWorkMedia(mediaScope);
assert.equal(media.revision, 0);
const request = (command: WorkMediaWrite['command']): WorkMediaWrite => ({ ...mediaScope, sessionToken: media.sessionToken, expectedRevision: media.revision, command });
const first = request({ kind: 'capture', requestId: 'frame-request:first', requestedTicks: 15010000 });
media = await host.writeWorkMedia(first);
assert.equal(media.frames.length, 1);
assert.ok(media.frames[0].actualTicks >= 15010000);
assert.ok(media.frames[0].actualTicks - 15010000 <= 1e7 / 24 + 1);
const count = framesDecoded;
assert.deepEqual(await host.writeWorkMedia(first), media);
assert.equal(framesDecoded, count);
media = await host.writeWorkMedia(request({ kind: 'capture', requestId: 'frame-request:second', requestedTicks: 301230000 }));
const evidence = media.frames.map(frame => ({ ...frame })), frameDigests = await Promise.all(media.frames.map(async (frame) => sha((await host.readWorkMediaFile({ ...mediaScope, frameId: frame.id })).bytes)));
media = await host.writeWorkMedia(request({ kind: 'save', sourceUrl: 'https://peach.blender.org/', positionTicks: evidence[1].actualTicks, selectedFrameId: evidence[1].id, frames: [{ id: evidence[1].id, note: '第二帧 · English motion reference' }, { id: evidence[0].id, note: '第一帧 · 中文备注' }] }));
assert.equal(media.frames[0].id, evidence[1].id);
assert.equal(media.frames[0].note, '第二帧 · English motion reference');
await assert.rejects(host.writeWorkMedia({ ...first, command: { kind: 'save', sourceUrl: 'https://peach.blender.org/', positionTicks: 0, selectedFrameId: null, frames: [] } }));
await assert.rejects(host.readWorkMediaFile({ ...mediaScope, setId: 'work-set:unrelated' }));
const abort = new AbortController(), pending = host.writeWorkMedia(request({ kind: 'capture', requestId: 'frame-request:cancel', requestedTicks: 300 * 1e7 }), abort.signal);
setTimeout(() => abort.abort(), 75);
await assert.rejects(pending);
assert.deepEqual(await host.readWorkMedia(mediaScope), media);
const handoffRoot = path.join(root, '交付 copies'), trashRoot = path.join(root, 'test-trash');
await fs.mkdir(trashRoot);
process.stdout.write('work-media: handoff, rejection and restart\n');
const options = { host, root: handoffRoot, open: async () => 'receiver-rejected', trash: async (file: string) => { await fs.rename(file, path.join(trashRoot, path.basename(file))); } };
let files = createWorkFileHandoffs(options);
const receipt = await files.prepare('workspace:test', { ...mediaScope, kind: 'original', action: 'prepare' });
const imageReceipt = await files.prepare('workspace:test', { ...mediaScope, assetId: picture.id, kind: 'original', action: 'prepare' });
assert.ok(imageReceipt.fileName.endsWith('.png'));
assert.equal(imageReceipt.sha256, imageDigest);
assert.equal(receipt.sha256, videoDigest);
assert.equal(sha((await files.readFile(receipt.id)).bytes), videoDigest);
await assert.rejects(files.nativeFile('work-native:other', receipt.id));
const refused = await files.prepare('workspace:test', { ...mediaScope, kind: 'reference-frame', frameId: evidence[1].id, action: 'open' });
assert.equal(refused.status, 'open-rejected');
assert.equal(sha((await files.readFile(refused.id)).bytes), frameDigests[1]);
assert.throws(() => validateWorkSourceUrl('https://example.org/?token=fake-test-only'));
assert.throws(() => validateWorkHandoff({ ...mediaScope, kind: 'original', action: 'prepare', path: 'C:/not-a-permission' }));
const ipc = new Map<string, Function>(), owner = { sender: { id: 1 } }, controller = createWorkMediaController({ host, files, changed: () => { } });
registerWorkMediaIpc({ controller, handle: (channel, handler) => ipc.set(channel, handler), isMain: event => event === owner, owner: () => 'workspace:test' });
const cancelledWrite = controller.write('workspace:test', request({kind: 'capture', requestId: 'frame-request:controller-cancel', requestedTicks: 500 * 1e7}));
await controller.cancel('workspace:test', {});
const cancelledResult = await cancelledWrite;
assert.equal(cancelledResult.success, false);
if (!cancelledResult.success) assert.match(cancelledResult.error, /取消/);
assert.deepEqual(await host.readWorkMedia(mediaScope), media);
const cancelledSave = controller.write('workspace:test', request({kind: 'save', sourceUrl: media.sourceUrl, positionTicks: media.positionTicks, selectedFrameId: media.selectedFrameId, frames: media.frames.map(f => ({id: f.id, note: f.note}))}));
await controller.cancel('workspace:test', {});
const cancelledSaveResult = await cancelledSave;
assert.equal(cancelledSaveResult.success, false);
if (!cancelledSaveResult.success) assert.match(cancelledSaveResult.error, /取消/);
assert.equal((await ipc.get('work-media:read')!({}, mediaScope)).code, 'UNTRUSTED_SENDER');
assert.equal((await ipc.get('work-media:read')!(owner, { ...mediaScope, generation: 'stale' })).success, false);
assert.equal((await ipc.get('work-files:clear')!(owner, { id: receipt.id, receiverFinished: false })).success, false);
await host.close();
host = createActiveLibraryHost(dependencies);
await host.open();
state = host.inspect();
scope = { libraryIdentity: state.identity!, generation: state.generation! };
const reopened = await host.readWorkMedia({ ...mediaScope, ...scope });
assert.deepEqual({ ...reopened, sessionToken: '' }, { ...media, sessionToken: '' });
files = createWorkFileHandoffs({ ...options, host });
assert.equal(sha((await files.readFile(receipt.id)).bytes), videoDigest);
assert.equal((await files.list({ ...mediaScope, ...scope })).length, 2);
await files.clear(refused.id);
assert.equal(sha(await fs.readFile(path.join(trashRoot, refused.fileName))), frameDigests[1]);
media = await host.writeWorkMedia({ ...mediaScope, ...scope, sessionToken: reopened.sessionToken, expectedRevision: reopened.revision, command: { kind: 'remove', frameId: evidence[0].id } });
assert.equal(media.frames.length, 1);
assert.equal(media.frames[0].pngSha256, frameDigests[1]);
await assert.rejects(host.readWorkMediaFile({ ...mediaScope, ...scope, frameId: evidence[0].id }));
const current = await host.readWorkSets(scope, 'device:media-test');
await host.writeWorkSet({ ...scope, sessionToken: current.sessionToken, allowUpgrade: false, command: { kind: 'save', id: current.sets[0].id, expectedRevision: current.sets[0].revision, value: { name: current.sets[0].name, assetIds: [picture.id], note: '保留视频原件', colors: [], columns: 2 } } }, 'device:media-test');
await assert.rejects(host.readWorkMediaFile({ ...mediaScope, ...scope }));
assert.ok((await host.listAssets()).some(a => a.id === clip.id));
await host.close();
assert.equal(sha(await fs.readFile(video)), videoDigest);
assert.equal(sha(await fs.readFile(image)), imageDigest);
process.stdout.write(JSON.stringify({ result: 'PASS', root, videoDigest, frames: 2, actualTicks: evidence.map(f => f.actualTicks), nativeDecodes: framesDecoded, meaning: 'Real native codec + held Host/SQLite checks; not Browser/receiver acceptance' }) + '\n');
