/** Generated by seal-pi-runtime; app-bundled release identity, not user-editable runtime metadata. */
export const PI_RUNTIME_RELEASE_SHA256="27be409a4075f4bdae2cfa1a2587e6ade200ba44989b4c1d7ff4d24e8e27ba6e"
