import {WorkReferencePanel} from '../../components/gallery/WorkReferencePanel'
import {FloatingNavigation} from '../../components/gallery/FloatingNavigation'
import React, { useEffect, useMemo, useRef, useState } from 'react'
import { Search, Plus, X, ArrowUpRight, Grid2X2, PanelsTopLeft, Folder, Sparkles, SlidersHorizontal, Pin, Save, RotateCcw, Moon, Sun, Check, Image as ImageIcon, Film, Grip, Maximize2, Copy, ChevronRight, Eye, CircleHelp, Palette, Inbox, Clock, Tags, Trash2, Shuffle, FolderOpen, ChevronDown, ArrowLeft, ArrowRight, Settings2, LayoutGrid, Type } from 'lucide-react'
import { assets, starterSets, DemoAsset, WorkSet, analyzedIds, confirmedTagIds, manualFolders, aiFolders, PaletteFolder, initialPalettes } from './fixtures'
import './work-mode-prototype.css'
import { BottomDock } from './BottomDock'
import { FolderCard } from './FolderCard'
import { AnchoredGrid, captureGridAnchor, GridAnchor } from './AnchoredGrid'
import { FocusMode } from './FocusMode'
import { ColorStrip, ColorMenu, ColorEvent } from './ColorTools'
const darkColor=(color?:string)=>{if(!color)return false;const h=color.replace('#','');return parseInt(h.slice(0,2),16)*.299+parseInt(h.slice(2,4),16)*.587+parseInt(h.slice(4,6),16)*.114<145}
const PALETTE_KEY='dam-palette-prototype-v1'
function loadPalettes():PaletteFolder[]{try{const p=JSON.parse(localStorage.getItem(PALETTE_KEY)||'null');if(Array.isArray(p)&&p.length<100&&p.every(f=>typeof f.id==='string'&&typeof f.name==='string'&&Array.isArray(f.colors)&&f.colors.every((c:unknown)=>typeof c==='string'&&/^#[0-9a-f]{6}$/i.test(c))))return p}catch{}return structuredClone(initialPalettes)}

const KEY='dam-work-mode-prototype-v1'
const movie=new URL('./motion-study.mp4',import.meta.url).href
interface Saved { version:1; sets:WorkSet[]; dark:boolean; solid?:boolean; restored?:boolean }
function initial():Saved {
 try { const d=JSON.parse(localStorage.getItem(KEY)||'null'); if(d?.version===1 && Array.isArray(d.sets) && d.sets.length<40 && d.sets.every((s:WorkSet)=>typeof s.id==='string'&&typeof s.name==='string'&&typeof s.note==='string'&&Array.isArray(s.frames)&&s.frames.every(Number.isFinite)&&Array.isArray(s.ids)&&s.ids.every(id=>assets.some(a=>a.id===id))&&[s.x,s.y,s.w,s.h].every(Number.isFinite))) return {...d,restored:true} } catch { /* Only synthetic prototype storage. */ }
 return {version:1,sets:structuredClone(starterSets),dark:false,solid:false}
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}) {
 const ref=useRef<HTMLDialogElement>(null)
 useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.showModal();return()=>previous?.focus()},[])
 return <dialog ref={ref} onCancel={e=>{e.preventDefault();close()}} aria-label={title}><header><h2>{title}</h2><button className="icon" onClick={close} aria-label="关闭对话框"><X/></button></header>{children}</dialog>
}
function Motion({frames,change}:{frames:number[];change:(v:number[])=>void}) {
 const ref=useRef<HTMLVideoElement>(null);const [time,setTime]=useState(0)
 return <div className="motion-player"><video ref={ref} src={movie} controls preload="metadata" onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} aria-label="合成动效视频"/><div className="frame-tools"><span>{time.toFixed(2)} s · 合成视频</span><button onClick={()=>change([...new Set([...frames,Math.round(time*100)/100])].sort((a,b)=>a-b))}><Plus/>选为参考帧</button></div><div className="frame-list">{frames.map(t=><div key={t}><button onClick={()=>{if(ref.current){ref.current.currentTime=t;ref.current.pause()}}}>↳ {t.toFixed(2)}s</button><button aria-label={`移除 ${t.toFixed(2)} 秒参考帧`} onClick={()=>change(frames.filter(x=>x!==t))}><X size={12}/></button></div>)}</div></div>
}
function WindowPanel({set,update,inspect,offline,onSave,dirty,onTransfer,preview,copyColor,colorMenu}:{set:WorkSet;update:(p:Partial<WorkSet>)=>void;inspect:(id:string)=>void;offline:boolean;onSave:()=>void;dirty:boolean;onTransfer:(id:string)=>void;preview:(id:string)=>void;copyColor:(c:string)=>void;colorMenu:(e:ColorEvent,c:string)=>void}) {
 const root=useRef<HTMLElement>(null)
 const drag=(event:React.PointerEvent,resize=false)=>{
  const control=(event.target as HTMLElement).closest('button,input,textarea,select');if(!resize&&control&&!control.classList.contains('grip'))return
  if(event.button!==0)return
  const target=event.currentTarget as HTMLElement;target.setPointerCapture(event.pointerId)
  const x=event.clientX,y=event.clientY,start={...set},parent=root.current?.parentElement
  const move=(e:PointerEvent)=>{const maxW=parent?.clientWidth||1000,maxH=parent?.clientHeight||800;update(resize?{w:Math.max(290,Math.min(maxW-start.x,start.w+e.clientX-x)),h:Math.max(310,Math.min(maxH-start.y,start.h+e.clientY-y))}:{x:Math.max(0,Math.min(maxW-start.w,start.x+e.clientX-x)),y:Math.max(0,Math.min(maxH-80,start.y+e.clientY-y))})}
  const stop=()=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',stop);target.removeEventListener('pointercancel',stop)}
  target.addEventListener('pointermove',move);target.addEventListener('pointerup',stop);target.addEventListener('pointercancel',stop)
 }
 return <div ref={root as React.RefObject<HTMLDivElement>} style={{display:'contents'}}><WorkReferencePanel name={set.name} items={set.ids.map(id=>{const a=assets.find(x=>x.id===id)!;return{id,title:a.title,src:a.src,unavailable:offline&&id==='a0'}})} note={set.note} colors={set.swatches||[]} pinned={set.pinned} dirty={dirty} style={{left:set.x,top:set.y,width:set.w,height:set.h,zIndex:set.pinned?4:2}} onHeaderPointerDown={e=>drag(e)}
 grip={<button className="icon grip" aria-label={`移动 ${set.name}`} onKeyDown={e=>{const d:{[key:string]:number[]}={ArrowLeft:[-16,0],ArrowRight:[16,0],ArrowUp:[0,-16],ArrowDown:[0,16]};if(d[e.key]){e.preventDefault();update({x:Math.max(0,set.x+d[e.key][0]),y:Math.max(0,set.y+d[e.key][1])})}}}><Grip size={16}/></button>}
 onInspect={inspect} onPreview={preview} onRemove={id=>update({ids:set.ids.filter(x=>x!==id)})} onNote={note=>update({note})} onColors={swatches=>update({swatches})} onPin={()=>update({pinned:!set.pinned})} onHide={()=>update({open:false})} onSave={onSave} onCopyColor={copyColor} colorMenu={colorMenu} onTransfer={onTransfer} transferLabel="演示交接" onDragStart={(e,id)=>{e.dataTransfer.setData('application/x-dam-demo',id);e.dataTransfer.effectAllowed='copy'}}
 extra={set.ids.includes('a3')?<Motion frames={set.frames} change={frames=>update({frames})}/>:undefined}
 resizeGrip={<button className="resize-grip" aria-label={`调整 ${set.name} 尺寸`} onPointerDown={e=>drag(e,true)} onKeyDown={e=>{if(e.key.startsWith('Arrow')){e.preventDefault();update({w:Math.max(290,set.w+(e.key==='ArrowRight'?16:e.key==='ArrowLeft'?-16:0)),h:Math.max(310,set.h+(e.key==='ArrowDown'?16:e.key==='ArrowUp'?-16:0))})}}}><span>⌟</span></button>}/></div>
}
export default function WorkModePrototype(){
 const [loaded]=useState(initial);const [sets,setSets]=useState<WorkSet[]>(loaded.sets);const [dark,setDark]=useState(loaded.dark);const [showInfo,setShowInfo]=useState(false)
 const [mode,setMode]=useState<'library'|'work'>('library');const [screen,setScreen]=useState<'assets'|'folders'|'sets'|'palettes'|'tags'>('assets');const [query,setQuery]=useState('');const [category,setCategory]=useState('全部素材');const [selected,setSelected]=useState<string[]>([]);const [inspected,setInspected]=useState<string|null>(null);const [focus,setFocus]=useState<string|null>(null);const [focusOrder,setFocusOrder]=useState<string[]>([]);const [gridAnchor,setGridAnchor]=useState<GridAnchor|null>(null)
 const [dirty,setDirty]=useState<string[]>(loaded.restored?[]:loaded.sets.map(s=>s.id));const [toast,setToast]=useState('');const [create,setCreate]=useState(false);const [name,setName]=useState('');const [target,setTarget]=useState('new');const [offline,setOffline]=useState(false);const [saveFail,setSaveFail]=useState(false);const [loadFail,setLoadFail]=useState(false);const [noModel,setNoModel]=useState(false);const [lab,setLab]=useState(false);const [received,setReceived]=useState<string[]>([]);const [showPrompt,setShowPrompt]=useState(false);const [frames,setFrames]=useState<number[]>([])
 const [tileSize,setTileSize]=useState(330);const [chosenTags,setChosenTags]=useState<string[]>([]);const [quick,setQuick]=useState<string[]>([]);const [shuffleOrder,setShuffleOrder]=useState<string[]>([]);const [trashIds,setTrashIds]=useState<string[]>(['a7']);
 const [history,setHistory]=useState<{screen:'assets'|'folders'|'palettes';view:string;palette:string;q:string;tags:string[]}[]>([{screen:'assets',view:'all',palette:'all',q:'',tags:[]}]);const [historyIndex,setHistoryIndex]=useState(0)
 const [libraryView,setLibraryView]=useState('all');const [recent,setRecent]=useState<string[]>(['a1','a3']);const [expanded,setExpanded]=useState<string[]>(['brand'])
 const [palettes,setPalettes]=useState<PaletteFolder[]>(loadPalettes);const [paletteDirty,setPaletteDirty]=useState(false);const [paletteFilter,setPaletteFilter]=useState('all')
 const [colorContext,setColorContext]=useState<{color:string;x:number;y:number}|null>(null);const [colorDestination,setColorDestination]=useState<'palette'|'window'|null>(null);const [pickedColor,setPickedColor]=useState('');const [destinationId,setDestinationId]=useState('');const [folderName,setFolderName]=useState('');const [newPaletteOpen,setNewPaletteOpen]=useState(false)
 const navigate=(screen:'assets'|'folders'|'palettes',view='all',palette='all')=>{const current={screen:screenState(),view:libraryView,palette:paletteFilter,q:query,tags:chosenTags};const target={screen,view,palette,q:'',tags:[] as string[]};setHistory(h=>[...h.slice(0,historyIndex),current,target]);setHistoryIndex(historyIndex+1);setMode('library');setScreen(screen);setLibraryView(view);setPaletteFilter(palette);setQuery('');setChosenTags([]);setQuick([]);setCategory('全部素材');setInspected(null)}
 const screenState=(): 'assets'|'folders'|'palettes'=>screen==='palettes'?'palettes':screen==='folders'?'folders':'assets'
 const travel=(direction:number)=>{const i=historyIndex+direction;if(i<0||i>=history.length)return;setHistory(h=>h.map((r,n)=>n===historyIndex?{screen:screenState(),view:libraryView,palette:paletteFilter,q:query,tags:chosenTags}:r));const r=history[i];setHistoryIndex(i);setMode('library');setScreen(r.screen);setLibraryView(r.view);setPaletteFilter(r.palette);setQuery(r.q);setChosenTags(r.tags);setQuick([]);setInspected(null)}
 const browse=(view:string)=>navigate('assets',view)
 const shuffle=()=>{const ids=assets.map(a=>a.id);for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}setShuffleOrder(ids)}
 const viewIds=(view:string):string[]=>{if(view==='all')return assets.filter(a=>!trashIds.includes(a.id)).map(a=>a.id);if(view==='unclassified')return assets.filter(a=>!manualFolders.some(f=>[...f.ids,...f.children.flatMap(c=>c.ids)].includes(a.id))).map(a=>a.id);if(view==='untagged')return assets.filter(a=>!confirmedTagIds.includes(a.id)).map(a=>a.id);if(view==='recent')return recent;if(view==='trash')return trashIds;const ai=aiFolders.find(f=>f.id===view);if(ai)return assets.filter(a=>analyzedIds.includes(a.id)&&(view!=='pending'||!confirmedTagIds.includes(a.id))&&(!ai.tag||a.tags.includes(ai.tag))).map(a=>a.id);return manualFolders.flatMap(f=>[f,...f.children]).find(f=>f.id===view)?.ids||[]}
 const activeTitle=({all:'全部素材',unclassified:'未分类',untagged:'未标签',recent:'最近使用',trash:'回收站'} as Record<string,string>)[libraryView]||[...aiFolders,...manualFolders.flatMap(f=>[f,...f.children])].find(f=>f.id===libraryView)?.name||'全部素材'
 const openColorMenu=(e:ColorEvent,color:string)=>{e.preventDefault();e.stopPropagation();e.currentTarget.focus();const r=e.currentTarget.getBoundingClientRect();setPickedColor(color);setColorContext({color,x:'clientX' in e&&e.clientX?e.clientX:r.left,y:'clientY' in e&&e.clientY?e.clientY:r.bottom})}
 const persistPalettes=(next:PaletteFolder[])=>{setPalettes(next);if(saveFail){setPaletteDirty(true);notice('色板保存失败，更改保留在页面中，请重试。');return}try{localStorage.setItem(PALETTE_KEY,JSON.stringify(next));setPaletteDirty(false);notice('色板已保存到原型专用存储。')}catch{setPaletteDirty(true);notice('色板存储不可用，请重试。')}}
 const collectColor=()=>{if(colorDestination==='palette'){if(destinationId==='new'){const name=folderName.trim();if(!name)return;if(palettes.some(f=>f.name===name)){notice('已有同名色板文件夹，请选择已有文件夹。');return}persistPalettes([...palettes,{id:`palette-${Date.now()}`,name,colors:[pickedColor]}])}else{persistPalettes(palettes.map(f=>f.id===destinationId?{...f,colors:[...new Set([...f.colors,pickedColor])]}:f))}}else{const work=sets.find(w=>w.id===destinationId);if(!work)return;update(work.id,{swatches:[...new Set([...(work.swatches||[]),pickedColor])]});notice(`已添加到「${work.name}」的色板，请保存工作集。`)}setColorDestination(null)}
 const stage=useRef<HTMLDivElement>(null)
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t)},[toast])
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='f'){e.preventDefault();const search=document.getElementById('prototype-search') as HTMLInputElement|null;if(search){search.focus();search.select()}else{setMode('library');setScreen('assets');setLibraryView('all');setTimeout(()=>document.getElementById('prototype-search')?.focus(),0)}}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[])
 const notice=(v:string)=>setToast(v)
 const update=(id:string,p:Partial<WorkSet>)=>{setSets(all=>all.map(s=>s.id===id?{...s,...p}:s));setDirty(d=>[...new Set([...d,id])])}
 const fit=()=>{const w=stage.current?.clientWidth||900;setSets(all=>all.map((s,i)=>({...s,x:w<700?8:(i%2)*(Math.min(380,(w-80)/2)+24)+20,y:28+Math.floor(i/2)*38,w:Math.min(380,w-28),h:Math.min(520,Math.max(360,(stage.current?.clientHeight||650)-65)),open:true})));setDirty(sets.map(s=>s.id))}
 const enterWork=()=>{setMode('work');setInspected(null)}
 useEffect(()=>{if(mode!=='work')return;const recover=()=>{const area=stage.current;if(!area)return;setSets(all=>all.map(s=>{const w=Math.max(290,Math.min(s.w,area.clientWidth-16)),h=Math.max(310,Math.min(s.h,area.clientHeight-28));return {...s,w,h,x:Math.max(0,Math.min(s.x,area.clientWidth-w)),y:Math.max(0,Math.min(s.y,area.clientHeight-h))}}))};recover();window.addEventListener('resize',recover);return()=>window.removeEventListener('resize',recover)},[mode])
 const save=()=>{if(saveFail){notice('保存失败：演示存储不可写。更改仍在，请关闭故障开关后重试。');return}try{localStorage.setItem(KEY,JSON.stringify({version:1,sets,dark}));setDirty([]);notice('工作集和窗口设置已保存到原型专用存储，可刷新验证恢复。')}catch{notice('浏览器存储不可用，更改仍在当前页面，请重试。')}}
 const transfer=(id:string)=>{if(offline&&id==='a0'){notice('素材离线，不能交接。');return}setReceived(r=>[...new Set([...r,id])]);notice('演示接收区已收到引用；未向外部软件传输文件。')}
 const addToSet=()=>{if(!selected.length)return;if(target==='new'){if(!name.trim())return;const id=`set-${Date.now()}`;setSets(all=>[...all,{id,name:name.trim(),ids:[...selected],note:'',x:40,y:40,w:380,h:480,pinned:true,open:true,frames:[]}]);setDirty(d=>[...d,id])}else{const s=sets.find(x=>x.id===target);if(!s)return;update(target,{ids:[...new Set([...s.ids,...selected])],open:true})}setCreate(false);setSelected([]);notice('已加入工作集。素材原件与分类保持不变。')}
 const matched=useMemo(()=>{const list=assets.filter(a=>viewIds(libraryView).includes(a.id)&&(libraryView==='trash'||!trashIds.includes(a.id))&&chosenTags.every(t=>a.tags.includes(t))&&(!quick.includes('untagged')||!confirmedTagIds.includes(a.id))&&(!quick.includes('unclassified')||viewIds('unclassified').includes(a.id))&&(category==='全部素材'||category==='图片'&&a.kind==='image'||category==='视频'&&a.kind==='video'||category==='文字'&&a.kind==='text'||category==='字体'&&a.kind==='font'||category==='文档'&&a.kind==='document'||a.category===category)&&[a.title,...a.tags,a.description,a.prompt].join(' ').toLowerCase().includes(query.toLowerCase().trim()));return shuffleOrder.length?list.sort((a,b)=>shuffleOrder.indexOf(a.id)-shuffleOrder.indexOf(b.id)):list},[query,category,libraryView,recent,chosenTags,quick,shuffleOrder,trashIds])
 const folderCovers=(ids:string[])=>ids.filter(id=>!trashIds.includes(id)).slice(0,3).map(id=>assets.find(a=>a.id===id)?.src).filter(Boolean) as string[]
 const folderMatch=(name:string)=>name.toLowerCase().includes(query.toLowerCase())
 const dockMenu=(id:string)=>{if(id==='clear'){setQuery('');setChosenTags([]);setQuick([]);setCategory('全部素材')}if(id==='palettes')navigate('folders','palette-root');if(id==='tags'){setMode('library');setScreen('tags')}if(id==='theme')setDark(!dark);if(id==='lab')setLab(true);if(id==='new-set'){if(!selected.length){notice('先选择素材，再加入工作集。');return}setTarget('new');setName('');setCreate(true)}}

 const current=assets.find(a=>a.id===inspected)
 const matchText=(a:DemoAsset)=>{const q=query.trim().toLowerCase();if(!q)return a.category;if(a.title.toLowerCase().includes(q))return '命中：素材名称';if(a.tags.some(t=>t.includes(q)))return '命中：标签';if(a.description.toLowerCase().includes(q))return '命中：画面描述';return '命中：反推提示词'}
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);notice('已复制演示内容')}catch{notice('剪贴板不可用，请选择文字手动复制。')}}
 const inspect=(id:string)=>{setGridAnchor(captureGridAnchor(id));setInspected(id);setShowPrompt(false);setRecent(r=>[id,...r.filter(v=>v!==id)].slice(0,8))}
 const openFocus=(id:string,order?:string[])=>{const ids=order||matched.map(a=>a.id);setFocusOrder(ids.includes(id)?ids:[id]);setFocus(id);setShowPrompt(false);setColorContext(null)}
 const focusAsset=assets.find(a=>a.id===focus)
 const focusItems=focusOrder.map(id=>assets.find(a=>a.id===id)).filter((a):a is DemoAsset=>Boolean(a))
 const closeInspector=()=>{if(inspected)captureGridAnchor(inspected);setGridAnchor(null);setInspected(null)}
 const renderDetails=(detail:DemoAsset,withPreview=true)=>(<div className="inspector-scroll">{withPreview&&<button className="inspector-preview" onClick={()=>openFocus(detail.id)} aria-label="专注查看"><img src={detail.src} alt={detail.title}/><span><Maximize2 size={14}/>专注查看</span></button>}{detail.colors.length>0&&<ColorStrip colors={detail.colors} copy={copy} menu={openColorMenu}/>}<p className="subtle">{detail.kind==='video'?'合成视频 · 5 秒':detail.kind==='text'?'可检索的文字样例':detail.kind==='font'?'系统字体样张 · 未安装外部字体':detail.kind==='document'?'文档预览示意 · 非真实PDF解码':'原创合成 SVG · 480 × 560'}</p><div className="detail-section"><h3><Sparkles size={15}/>素材理解 <span className="sample">预置示例</span></h3><p>{detail.description}</p><div className="tags">{detail.tags.map(t=><button key={t} onClick={()=>{setQuery(t);setMode('library');setScreen('assets')}}>{t}</button>)}</div></div>{(detail.kind==='image'||detail.kind==='video')&&<div className="detail-section"><h3>提示词反推</h3><p className="subtle">提供创作方向，不等同于原始提示词。</p>{showPrompt?<><textarea aria-label="演示反推提示词" readOnly value={detail.prompt}/><button onClick={()=>copy(detail.prompt)}><Copy size={14}/>复制提示词</button></>:<button className="wide" disabled={noModel} onClick={()=>setShowPrompt(true)}><Sparkles size={14}/>{noModel?'演示：模型尚未就绪':'展开示例反推'}</button>}</div>}{detail.kind==='video'&&<div className="detail-section"><h3>视频与参考帧</h3><Motion frames={frames} change={setFrames}/><a href="https://example.com" target="_blank" rel="noreferrer">来源网址 · 示例域名 ↗</a></div>}<button className="wide" onClick={()=>{setSelected([detail.id]);setName('');setTarget('new');setCreate(true)}}><Plus size={14}/>加入工作集</button></div>)
 const renderColorMenu=()=>(colorContext&&<ColorMenu {...colorContext} close={()=>setColorContext(null)} copy={()=>{void copy(colorContext.color);setColorContext(null)}} collect={()=>{setPickedColor(colorContext.color);setDestinationId(palettes[0]?.id||'new');setFolderName('');setColorContext(null);setColorDestination('palette')}} addWindow={()=>{setPickedColor(colorContext.color);setDestinationId(sets[0]?.id||'');setColorContext(null);setColorDestination('window')}}/>)
 return <div className={`gallery-design work-prototype minimal-prototype ${dark?'dark':''} ${showInfo?'with-preview-info':'clean-preview'}`}>
  {showInfo&&<div className="prototype-ribbon"><span><span className="live-dot"/> GALLERY & GLASS <b>交互原型</b></span><span className="ribbon-detail">合成素材 · 预置 AI 结果 · 浏览器内窗口演示</span><button onClick={()=>setLab(!lab)} aria-expanded={lab}><SlidersHorizontal size={13}/>演示设置</button></div>}
  <div className={`app-shell ${current?'has-side-inspector':''}`}>
   <aside className="icon-rail" aria-label="主导航"><a className="rail-brand" href="#" aria-label="素材工作台" onClick={e=>{e.preventDefault();browse('all')}}><span className="brand-symbol"><PanelsTopLeft size={21}/></span></a><nav>{[{name:'全部',Icon:Inbox,active:mode==='library'&&screen==='assets'&&libraryView==='all',run:()=>browse('all')},{name:'文件夹',Icon:Folder,active:mode==='library'&&(screen==='folders'||screen==='palettes'||screen==='assets'&&!['all','trash'].includes(libraryView)),run:()=>navigate('folders')},{name:'工作模式',Icon:PanelsTopLeft,active:mode==='work'||screen==='sets',run:()=>{setMode('library');setScreen('sets');setInspected(null);setQuery('')}},{name:'回收站',Icon:Trash2,active:mode==='library'&&screen==='assets'&&libraryView==='trash',run:()=>browse('trash')}].map(({name,Icon,active,run})=><button key={name} aria-label={name} title={name} className={active?'active':''} onClick={run}><Icon size={22}/><span className="rail-tooltip">{name}</span></button>)}</nav><div className="rail-bottom"><button aria-label="切换明暗外观" title="切换明暗外观" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button aria-label="原型验证设置" title="原型验证设置" onClick={()=>setLab(true)}><Settings2/></button></div></aside>
   <main className={`main-view ${mode==='work'?'work-view':''}`}>
    <FloatingNavigation back={()=>travel(-1)} forward={()=>travel(1)} canBack={historyIndex>0} canForward={historyIndex<history.length-1} add={()=>notice('这是合成素材原型；正式应用的添加图片入口会打开文件选择器。')}>{screen==='sets'&&mode==='library'&&<button onClick={enterWork}><PanelsTopLeft size={15}/>恢复工作窗口</button>}{mode==='work'&&<button onClick={save}><Save size={15}/>保存工作空间</button>}{screen==='palettes'&&mode==='library'&&<button onClick={()=>{setFolderName('');setNewPaletteOpen(true)}}><Plus size={15}/>新建色板文件夹</button>}</FloatingNavigation>
    {mode==='library'&&screen==='assets'&&<>{selected.length>0&&<div className="selectionbar glass"><span><Check size={15}/>已选择 {selected.length} 份</span><button onClick={()=>{setTarget('new');setName('');setCreate(true)}}><Plus size={14}/>加入工作集</button><button onClick={()=>setSelected([])}>取消选择</button></div>}<div className="library-content">{manualFolders.find(f=>f.id===libraryView)?.children.map(f=><FolderCard key={f.id} name={f.name} count={f.ids.length} covers={folderCovers(f.ids)} onOpen={()=>navigate('assets',f.id)}/>)}{loadFail?<div className="empty"><CircleHelp/><h2>素材暂时没有加载出来</h2><p>演示读取失败。你的选择仍然保留。</p><button onClick={()=>setLoadFail(false)}>重新加载</button></div>:matched.length===0?<div className="empty"><Search/><h2>还没有找到匹配的参考</h2><p>试试“蓝色”“留白”，或清除当前筛选。</p><button onClick={()=>{setQuery('');setCategory('全部素材');setChosenTags([]);setQuick([])}}>清除搜索与筛选</button></div>:<AnchoredGrid items={matched} tileSize={tileSize} anchor={current?gridAnchor:null} render={a=>(<article className={`asset-tile ${selected.includes(a.id)?'selected':''} ${inspected===a.id?'inspected':''}`} key={a.id}><div className="asset-art"><button className="asset-open" aria-label={`查看 ${a.title}`} onClick={()=>inspect(a.id)} onDoubleClick={()=>openFocus(a.id)} onKeyDown={e=>{if(e.code==='Space'){e.preventDefault();e.stopPropagation();if(!e.repeat)openFocus(a.id)}}} onKeyUp={e=>{if(e.code==='Space')e.preventDefault()}}>{offline&&a.id==='a0'?<div className="missing">素材暂时离线<br/><small>保留记录与工作集引用</small></div>:<img src={a.src} alt={a.title} draggable={false}/>}</button><label className="select-asset"><input aria-label={`选择 ${a.title}`} type="checkbox" checked={selected.includes(a.id)} onChange={()=>setSelected(v=>v.includes(a.id)?v.filter(x=>x!==a.id):[...v,a.id])}/><span><Check size={13}/></span></label>{a.tags.length>0&&<div className="asset-overlay-tags" aria-label={`${a.title} 标签`}>{a.tags.slice(0,3).map(t=><button key={t} data-tone={darkColor(a.colors[0])?'dark':'light'} className={`glass ${chosenTags.includes(t)?'active':''}`} aria-label={`筛选标签 ${t}`} aria-pressed={chosenTags.includes(t)} onClick={()=>setChosenTags(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t])}><span>{t}</span></button>)}</div>}<span className="asset-format">{a.kind==='video'?<Film size={12}/>:<ImageIcon size={12}/>} {a.kind==='video'?'00:05':a.format||'SVG'}</span></div><div className="asset-meta"><strong>{a.title}</strong><span>{matchText(a)}</span>{libraryView==='trash'&&<button className="restore-demo" onClick={()=>{setTrashIds(ids=>ids.filter(id=>id!==a.id));notice('已恢复合成样例引用；未操作真实回收站。')}}>恢复素材</button>}</div></article>)}/>}</div></>}
    {mode==='library'&&screen==='folders'&&<div className="folder-landing"><div className="folder-gallery">{libraryView!=='palette-root'&&manualFolders.filter(f=>folderMatch(f.name)).map(f=><FolderCard key={f.id} name={f.name} count={viewIds(f.id).filter(id=>!trashIds.includes(id)).length} covers={folderCovers(f.ids)} onOpen={()=>navigate('assets',f.id)}/>)}{libraryView!=='palette-root'&&aiFolders.filter(f=>folderMatch(f.name)).map(f=><FolderCard key={f.id} name={f.name} ai count={viewIds(f.id).filter(id=>!trashIds.includes(id)).length} covers={folderCovers(viewIds(f.id))} onOpen={()=>navigate('assets',f.id)}/>)}{palettes.filter(f=>folderMatch(f.name)).map(f=><FolderCard key={f.id} name={f.name} count={f.colors.length} colors={f.colors} onOpen={()=>navigate('palettes','all',f.id)}/>)}</div>{query&&![...manualFolders,...aiFolders].some(f=>folderMatch(f.name))&&!palettes.some(f=>folderMatch(f.name))&&<div className="empty">没有匹配的文件夹<button onClick={()=>setQuery('')}>清除搜索</button></div>}</div>}
    {mode==='library'&&screen==='palettes'&&<div className="palette-library"><div className="palette-library-toolbar"><label>色板文件夹<select aria-label="筛选色板文件夹" value={paletteFilter} onChange={e=>setPaletteFilter(e.target.value)}><option value="all">全部色板</option>{palettes.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><span>{paletteDirty?'尚未保存':'已载入原型色板'}</span><button onClick={()=>persistPalettes(palettes)}><Save size={14}/>保存色板</button></div><p className="subtle">单击复制颜色代码；右键可收藏至其他色板或添加到工作窗口。</p><div className="palette-folder-grid">{palettes.filter(f=>paletteFilter==='all'||f.id===paletteFilter).map(f=><section key={f.id} aria-label={`色板文件夹 ${f.name}`}><h2><Folder size={16}/>{f.name}<small>{f.colors.length} 色</small></h2><div className="palette-color-grid">{f.colors.filter(c=>!query||c.toLowerCase().includes(query.toLowerCase())).map(c=><div key={c}><button className="swatch" style={{background:c}} aria-label={`复制收藏颜色 ${c}`} aria-haspopup="menu" onClick={()=>copy(c)} onContextMenu={e=>openColorMenu(e,c)} onKeyDown={e=>{if(e.key==='ContextMenu'||e.shiftKey&&e.key==='F10')openColorMenu(e,c)}}/><span>{c}</span><button className="icon" aria-label={`从色板 ${f.name} 移除 ${c}`} onClick={()=>persistPalettes(palettes.map(p=>p.id===f.id?{...p,colors:p.colors.filter(v=>v!==c)}:p))}><X size={13}/></button></div>)}</div>{!f.colors.length&&<p className="subtle">在图片配色上右键，收藏到这里。</p>}</section>)}</div></div>}
    {mode==='library'&&screen==='tags'&&<div className="tag-overview"><p>原型只展示标签依据与筛选；全局标签编辑尚未接线。</p><div className="tags">{[...new Set(assets.flatMap(a=>a.tags))].map(tag=><button key={tag} onClick={()=>{browse('all');setQuery(tag)}}>{tag}<span>{assets.filter(a=>a.tags.includes(tag)).length}</span></button>)}</div><div className="empty compact"><Sparkles/><p>AI 标签保持建议状态</p><small>{analyzedIds.length} 份素材有预置分析 · {confirmedTagIds.length} 份有用户确认标签</small></div></div>}
    {mode==='library'&&screen==='sets'&&<div className="folder-landing"><div className="work-landing-intro"><h1>让参考，回到手边。</h1><p>保存你的工作集，在设计时随时展开。</p></div><div className="folder-gallery">{sets.filter(s=>folderMatch(s.name)).map(s=><FolderCard key={s.id} name={s.name} count={s.ids.length} covers={folderCovers(s.ids)} onOpen={()=>{update(s.id,{open:true});enterWork()}}/>)}</div></div>}
    {mode==='work'&&<><div className="work-toolbar glass"><span><PanelsTopLeft size={16}/>{sets.filter(s=>s.open).length} 个参考窗口</span><button onClick={fit}><RotateCcw size={15}/>找回并排列窗口</button><button onClick={()=>{setMode('library');setScreen('assets')}}><Plus size={15}/>添加素材</button></div><div className="work-stage" ref={stage}><div className="design-receiver" onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-dam-demo')){e.preventDefault();e.dataTransfer.dropEffect='copy'}}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('application/x-dam-demo');if(assets.some(a=>a.id===id))transfer(id)}}><span className="receiver-toolbar"><span className="window-dots">● ● ●</span> DESIGN CANVAS · 接收区演示</span><div className="design-sheet"><span>STUDIO / 2026</span><h2>Ideas<br/>take shape.</h2><div className="sheet-sphere"/><p>A quiet space for a new perspective.</p></div><div className="received"><span>{received.length?'已接收的演示引用':'把窗口中的素材拖到这里'}</span>{received.map(id=><img key={id} src={assets.find(a=>a.id===id)!.src} alt={`已接收 ${assets.find(a=>a.id===id)!.title}`}/>)}</div></div>{sets.filter(s=>s.open).map(s=><WindowPanel key={s.id} set={s} update={p=>update(s.id,p)} inspect={inspect} offline={offline} onSave={save} dirty={dirty.includes(s.id)} onTransfer={transfer} preview={id=>openFocus(id,s.ids)} copyColor={copy} colorMenu={openColorMenu}/>)}</div></>}
    {mode==='library'&&<BottomDock assetActions={screen==='assets'} query={query} setQuery={setQuery} tags={[...new Set(assets.flatMap(a=>a.tags))]} chosen={chosenTags} toggleTag={t=>setChosenTags(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t])} quick={quick} toggleQuick={t=>setQuick(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t])} shuffle={shuffle} category={category} setCategory={setCategory} menuAction={dockMenu}/>}
    {mode==='library'&&screen==='assets'&&<label className="layout-slider" title="调整素材布局大小"><input type="range" min="150" max="430" step="10" value={tileSize} onChange={e=>{setGridAnchor(null);setTileSize(Number(e.target.value))}} aria-label="素材布局大小" title="调整布局大小"/><span className="slider-value">{tileSize}</span></label>}
   </main>
   {current&&<aside className={`inspector side-inspector ${mode==='work'?'work-side-inspector':''}`} aria-label="素材检查器"><header><span>素材详情</span><button className="icon" onClick={closeInspector} aria-label="关闭检查器"><X size={18}/></button></header>{renderDetails(current)}</aside>}
  </div>
  {showInfo&&<footer className="prototype-footer"><span>Gallery & Glass / v0.1</span><span>{dirty.length?`${dirty.length} 个工作集尚未保存`:'保存仅用于原型验证'} · 玻璃控制层</span><button onClick={()=>setLab(!lab)}><CircleHelp size={13}/>查看验证边界</button></footer>}
  {toast&&<div className="toast glass" role="status"><Check size={17}/>{toast}</div>}
  {create&&<Modal title="加入工作集" close={()=>setCreate(false)}><p className="subtle">已选择 {selected.length} 份素材，只添加引用。</p><label>目标工作集<select aria-label="目标工作集" value={target} onChange={e=>setTarget(e.target.value)}><option value="new">新建工作集</option>{sets.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{target==='new'&&<label>工作集名称<input autoFocus aria-label="工作集名称" placeholder="例如：品牌提案 · 第一方向" maxLength={60} value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addToSet()}}/></label>}<div className="dialog-actions"><button onClick={()=>setCreate(false)}>取消</button><button className="primary" disabled={target==='new'&&!name.trim()} onClick={addToSet}>加入工作集</button></div></Modal>}
  {!focus&&renderColorMenu()}
  {colorDestination&&<Modal title={colorDestination==='palette'?'添加到色板':'添加到工作窗口'} close={()=>setColorDestination(null)}><div className="chosen-color"><span style={{background:pickedColor}}/>{pickedColor.toUpperCase()}</div><label>{colorDestination==='palette'?'色板文件夹':'目标工作窗口'}<select aria-label="颜色保存位置" value={destinationId} onChange={e=>setDestinationId(e.target.value)}>{colorDestination==='palette'?<>{palettes.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}<option value="new">新建色板文件夹…</option></>:sets.map(w=><option key={w.id} value={w.id}>{w.name}{w.open?'':'（已隐藏）'}</option>)}</select></label>{destinationId==='new'&&<label>色板文件夹名称<input autoFocus aria-label="色板文件夹名称" maxLength={60} value={folderName} onChange={e=>setFolderName(e.target.value)}/></label>}<p className="subtle">相同颜色在同一位置只收藏一次，不改变图片与原始配色。</p><div className="dialog-actions"><button onClick={()=>setColorDestination(null)}>取消</button><button className="primary" disabled={!destinationId||destinationId==='new'&&!folderName.trim()} onClick={collectColor}>添加颜色</button></div></Modal>}
  {newPaletteOpen&&<Modal title="新建色板文件夹" close={()=>setNewPaletteOpen(false)}><label>文件夹名称<input autoFocus aria-label="色板文件夹名称" maxLength={60} value={folderName} onChange={e=>setFolderName(e.target.value)}/></label><div className="dialog-actions"><button onClick={()=>setNewPaletteOpen(false)}>取消</button><button className="primary" disabled={!folderName.trim()} onClick={()=>{if(palettes.some(f=>f.name===folderName.trim())){notice('已有同名色板文件夹');return}persistPalettes([...palettes,{id:`palette-${Date.now()}`,name:folderName.trim(),colors:[]}]);setNewPaletteOpen(false)}}>创建文件夹</button></div></Modal>}
  {focusAsset&&<FocusMode asset={focusAsset} items={focusItems} change={id=>{setFocus(id);setShowPrompt(false);setColorContext(null)}} close={()=>setFocus(null)} details={renderDetails(focusAsset,false)} video={<Motion frames={frames} change={setFrames}/>} overlay={renderColorMenu()}/>}
  {lab&&<Modal title="原型验证设置" close={()=>setLab(false)}><p>这些设置只影响合成演示。没有接入素材库、模型或操作系统置顶/文件拖放。</p><div className="lab-options">{[['素材离线',offline,setOffline],['模拟保存失败',saveFail,setSaveFail],['模拟读取失败',loadFail,setLoadFail],['模型未就绪',noModel,setNoModel],['显示预览说明条',showInfo,setShowInfo]] .map(([label,value,setter])=><label key={String(label)}><input type="checkbox" checked={Boolean(value)} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/>{String(label)}</label>)}</div><p className="subtle">窗口拖动/缩放和接收区验证浏览器交互；原生多窗口、外部应用交接、模型质量与真实库恢复仍待单独验证。保存使用此预览地址下的专用localStorage；更换地址不会迁移。</p><details><summary>当前交互状态</summary><pre>{JSON.stringify({mode,selected,query,sets:sets.map(({id,name,ids,open,x,y,w,h,frames})=>({id,name,ids,open,x,y,w,h,frames})),dirty,received},null,2)}</pre></details><button className="wide" onClick={()=>{localStorage.removeItem(KEY);localStorage.removeItem(PALETTE_KEY);setPalettes(structuredClone(initialPalettes));setPaletteDirty(false);setSets(structuredClone(starterSets));setDirty(starterSets.map(s=>s.id));setReceived([]);notice('已恢复合成样例，原型保存记录已清除。')}}>重置原型样例</button></Modal>}
 </div>
}
