// Generated by the offline native Runtime builder. Never generated by Runtime.
export const WINDOWS_BACKUP_RUNTIME_DIRECTORY = "bundle-JpWnRg"
export const WINDOWS_BACKUP_RUNTIME_MANIFEST_SHA256 = "48f0b934737da1664507a8a7b8c4cb19607d3b44884c71acbdb2993c059fbcb9"
export const WINDOWS_BACKUP_RUNTIME_SOURCE_DIGEST = "797a7559042a6a420cbed00f95d605b0a4342069c301d660d4d9c9af6532a48c"
